### DISCUSSION TITLE
CUDA error with AMD GPU?

### DISCUSSION THREAD

**Discussion by mikeperalta1** [ggml-org/llama.cpp#7867] [General]
Hey all,

Trying to figure out what I'm doing wrong. Trying to run llama with an AMD GPU (6600XT) spits out a confusing error, as I don't have an NVIDIA GPU:
```
ggml_cuda_compute_forward: RMS_NORM failed
CUDA error: invalid device function
  current device: 0, in function ggml_cuda_compute_forward at ggml-cuda.cu:2320
  err
GGML_ASSERT: ggml-cuda.cu:100: !"CUDA error"
Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
No stack.
The program is not being run.
/home/llm/bin/chat: line 43: 48298 Aborted                 (core dumped) HSA_OVERRIDE_GFX_VERSION=10.3.0 /home/llm/opt/llama.cpp/main --model "/home/llm/opt/llama.cpp/models/downloaded/llama-2-13b-chat.Q4_K_M.gguf" --interactive --main-gpu 0
```

It does detect my GPU:
```
ggml_cuda_init: found 1 ROCm devices:
  Device 0: AMD Radeon RX 6600 XT, compute capability 10.3, VMM: no
```

Currently building with `make LLAMA_HIPBLAS=1 LLAMA_HIP_UMA=1 AMDGPU_TARGETS=gfx1032 -j8` but I've tried other variants to no avail. Here's my build script:
```
#!/bin/bash


DIR="$HOME/opt/llama.cpp"

cd "$DIR" || exit $?

make clean || exit $?

#make LLAMA_OPENBLAS=1 LLAMA_CLBLAST=1 LLAMA_HIPBLAS=1 -j4
#make LLAMA_HIPBLAS=1 LLAMA_HIP_UMA=1 AMDGPU_TARGETS=gfx1101 -j16

#make LLAMA_OPENBLAS=1 LLAMA_HIPBLAS=1 AMDGPU_TARGETS=gfx1032 -j8
#make LLAMA_HIPBLAS=1 AMDGPU_TARGETS=gfx1032 -j8
#make LLAMA_HIPBLAS=ON AMDGPU_TARGETS=gfx1032 -j8
make LLAMA_HIPBLAS=1 LLAMA_HIP_UMA=1 AMDGPU_TARGETS=gfx1032 -j8

exit $?

```

Clearly I'm just brute-forcing and don't know how this is supposed to work. Any advice?

**Comment by airpods69** [comment]
Same here, commenting to bump 

I am trying to run it on an AMD RX7700XT


Logs below
```
 Log start
main: build = 3175 (5326bcce)
main: built with cc (GCC) 14.1.1 20240522 for x86_64-pc-linux-gnu
main: seed  = 1719059849
llama_model_loader: loaded meta data with 24 key-value pairs and 291 tensors from ../Utils/Models/mistral-7b-instruct-v0.2.Q5_K_S.gguf?download=true (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = mistralai_mistral-7b-instruct-v0.2
llama_model_loader: - kv   2:                       llama.context_length u32              = 32768
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   4:                          llama.block_count u32              = 32
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                       llama.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv  11:                          general.file_type u32              = 16
llama_model_loader: - kv  12:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  13:                      tokenizer.ggml.tokens arr[str,32000]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
llama_model_loader: - kv  14:                      tokenizer.ggml.scores arr[f32,32000]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  15:                  tokenizer.ggml.token_type arr[i32,32000]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  16:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  17:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  18:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  19:            tokenizer.ggml.padding_token_id u32              = 0
llama_model_loader: - kv  20:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  21:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  22:                    tokenizer.chat_template str              = {{ bos_token }}{% for message in mess...
llama_model_loader: - kv  23:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type q5_K:  225 tensors
llama_model_loader: - type q6_K:    1 tensors
llm_load_vocab: special tokens cache size = 259
llm_load_vocab: token to piece cache size = 0.1637 MB
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 32768
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 4
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 1000000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_ctx_orig_yarn  = 32768
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: model type       = 7B
llm_load_print_meta: model ftype      = Q5_K - Small
llm_load_print_meta: model params     = 7.24 B
llm_load_print_meta: model size       = 4.65 GiB (5.52 BPW) 
llm_load_print_meta: general.name     = mistralai_mistral-7b-instruct-v0.2
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: PAD token        = 0 '<unk>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:   no
ggml_cuda_init: CUDA_USE_TENSOR_CORES: yes
ggml_cuda_init: found 2 ROCm devices:
  Device 0: AMD Radeon RX 7700 XT, compute capability 11.0, VMM: no
  Device 1: AMD Radeon Graphics, compute capability 10.3, VMM: no
llm_load_tensors: ggml ctx size =    0.44 MiB
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 33/33 layers to GPU
llm_load_tensors:      ROCm0 buffer size =  4577.00 MiB
llm_load_tensors:      ROCm1 buffer size =   102.55 MiB
llm_load_tensors:        CPU buffer size =    85.94 MiB
..................................................................................................
llama_new_context_with_model: n_ctx      = 32768
llama_new_context_with_model: n_batch    = 2048
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: flash_attn = 0
llama_new_context_with_model: freq_base  = 1000000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:      ROCm0 KV buffer size =  4096.00 MiB
llama_new_context_with_model: KV self size  = 4096.00 MiB, K (f16): 2048.00 MiB, V (f16): 2048.00 MiB
llama_new_context_with_model:  ROCm_Host  output buffer size =     0.12 MiB
llama_new_context_with_model: pipeline parallelism enabled (n_copies=4)
llama_new_context_with_model:      ROCm0 compute buffer size =  2368.02 MiB
llama_new_context_with_model:      ROCm1 compute buffer size =   102.50 MiB
llama_new_context_with_model:  ROCm_Host compute buffer size =   264.02 MiB
llama_new_context_with_model: graph nodes  = 1030
llama_new_context_with_model: graph splits = 3
ggml_cuda_compute_forward: RMS_NORM failed
CUDA error: shared object initialization failed
  current device: 0, in function ggml_cuda_compute_forward at ggml-cuda.cu:2313
  err
GGML_ASSERT: ggml-cuda.cu:100: !"CUDA error"
[1]    10478 IOT instruction  sudo ./llama-cli -m  -ngl 33 -p "hey there, my name is Pablo Escobar"
```

**Reply by rudiservo** [reply]
Are you using docker?

**Reply by airpods69** [reply]
This yes I believe was in a docker (had distrobox running)

**Reply by rudiservo** [reply]
Well I tried metal compiled with ROCm 6.1.2 and it works. But I have been trying with Docker build for the past 7 days or so, I tried ROCm 5.6, 5.7.1 and 6.1.2 and always crashes.

the latest ones I get this error

`llamacpp_1  | llama_new_context_with_model:  ROCm_Host compute buffer size =     9.01 MiB
llamacpp_1  | llama_new_context_with_model: graph nodes  = 1030
llamacpp_1  | llama_new_context_with_model: graph splits = 2
llamacpp_1  | ggml_cuda_compute_forward: RMS_NORM failed
llamacpp_1  | CUDA error: invalid device function
llamacpp_1  |   current device: 0, in function ggml_cuda_compute_forward at ggml/src/ggml-cuda.cu:2285
llamacpp_1  |   err
llamacpp_1  | GGML_ASSERT: ggml/src/ggml-cuda.cu:100: !"CUDA error"
`

**Comment by unoexperto** [comment]
Have you solved this problem ?

**Reply by rudiservo** [reply]
yes, it was a compile configuration issue with AMDGPU variable for make and cmake, if you check the Dockerfile for ROCm it should work.
FYI I have tested with the latest 6.3.2 on the 7900XTX with no issues.

**Comment by MarioIshac** [comment]
Running into this exact same issue on docker `ubuntu:24.04` 7900 GRE (GFX 1100) ROCm versions 6.2 to 6.4, whereas host works completely fine. Would appreciate any guidance on how to what could be cause of discrepancy given same build commands.

```
ROCm error: invalid device function
  current device: 0, in function ggml_cuda_compute_forward at /llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:2366
  err
/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:75: ROCm error
/llama.cpp/build/bin/libggml-base.so(+0x1588b)[0x7167c03e488b]
/llama.cpp/build/bin/libggml-base.so(ggml_print_backtrace+0x21c)[0x7167c03e4cec]
/llama.cpp/build/bin/libggml-base.so(ggml_abort+0xef)[0x7167c03e4e3f]
/llama.cpp/build/bin/libggml-hip.so(+0x60a02)[0x7167bd472a02]
/llama.cpp/build/bin/libggml-hip.so(+0x66fa6)[0x7167bd478fa6]
/llama.cpp/build/bin/libggml-base.so(ggml_backend_sched_graph_compute_async+0x483)[0x7167c03fac93]
/llama.cpp/build/bin/libllama.so(_ZN13llama_context13graph_computeEP11ggml_cgraphb+0xa1)[0x7167c0532f91]
/llama.cpp/build/bin/libllama.so(_ZN13llama_context14process_ubatchERK12llama_ubatch14llm_graph_typeP20llama_memory_state_iR11ggml_status+0x103)[0x7167c0533583]
/llama.cpp/build/bin/libllama.so(_ZN13llama_context6decodeER11llama_batch+0x88e)[0x7167c053761e]
/llama.cpp/build/bin/libllama.so(llama_decode+0xf)[0x7167c05387df]
build/bin/llama-cli(+0x12dc8a)[0x651bd5f72c8a]
build/bin/llama-cli(+0x3bcc5)[0x651bd5e80cc5]
/lib/x86_64-linux-gnu/libc.so.6(+0x2a1ca)[0x7167bfd8b1ca]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b)[0x7167bfd8b28b]
build/bin/llama-cli(+0x41905)[0x651bd5e86905]
Aborted (core dumped)
```
