### ISSUE TITLE
Misc. bug: AMD Rcom command error only with cli tools

### ISSUE THREAD

**Issue by pcfreak30** [ggml-org/llama.cpp#11509]
### Name and Version

b636228c0ad0db95bf73008094c6145a05615cf6

RCOM 6.3.2, ubuntu 24.04.

### Operating systems

Linux

### Which llama.cpp modules do you know to be affected?

llama-cli, llama-server, llama-bench

### Command line

```shell
./llama.cpp/build/bin/llama-cli -m ggml-model-q4_0.gguf -ngl 5
```

### Problem description & steps to reproduce

I am requesting help from anyone who know the code base well or at-least knows more then me.

I have spent a day or two already doing research and experimentation. Im using older AMD hardware, starting with a vega 56, rcom target `gtx900`.

The bizarre thing about  this is:

* Using https://github.com/abetlen/llama-cpp-python works
* Using ollama works
* Using LocalAI works

All of these embed or otherwise use `llama.cpp` as an engine driver and they all properly offload the model to the memory of GPU. I have spent a lot of time trying to isolate and see if I get any leads but unless I start debugging the code of each directly, i don't see getting any more info.

So this isn't a case of `my driver is broken or not working`. But that almost every layer ontop of llama that uses llama internally works, but *llama itself doesn't*. And I see no obvious mistakes ive made to explain it.

### Relevant log output

```shell
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 ROCm devices:
  Device 0: Radeon RX Vega, compute capability 9.0, VMM: no
build: 4419 (46e3556e) with cc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0 for x86_64-linux-gnu
main: llama backend init
main: load the model and apply lora adapter, if any
llama_load_model_from_file: using device ROCm0 (Radeon RX Vega) - 7802 MiB free
llama_model_loader: loaded meta data with 20 key-value pairs and 201 tensors from ggml-model-q4_0.gguf (version GGUF V2)
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = ..
llama_model_loader: - kv   2:                       llama.context_length u32              = 2048
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 2048
llama_model_loader: - kv   4:                          llama.block_count u32              = 22
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 5632
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 64
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 4
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                       llama.rope.freq_base f32              = 10000.000000
llama_model_loader: - kv  11:                          general.file_type u32              = 2
llama_new_context_with_model: n_seq_max     = 1
llama_new_context_with_model: n_ctx         = 4096
llama_new_context_with_model: n_ctx_per_seq = 4096
llama_new_context_with_model: n_batch       = 2048
llama_new_context_with_model: n_ubatch      = 512
llama_new_context_with_model: flash_attn    = 0
llama_new_context_with_model: freq_base     = 10000.0
llama_new_context_with_model: freq_scale    = 1
llama_new_context_with_model: n_ctx_pre_seq (4096) > n_ctx_train (2048) -- possible training context overflow
llama_kv_cache_init: kv_size = 4096, offload = 1, type_k = 'f16', type_v = 'f16', n_layer = 22, can_shift = 1
llama_kv_cache_init:      ROCm0 KV buffer size =    20.00 MiB
llama_kv_cache_init:        CPU KV buffer size =    68.00 MiB
llama_new_context_with_model: KV self size  =   88.00 MiB, K (f16):   44.00 MiB, V (f16):   44.00 MiB
llama_new_context_with_model:        CPU  output buffer size =     0.12 MiB
llama_new_context_with_model:      ROCm0 compute buffer size =   286.25 MiB
llama_new_context_with_model:  ROCm_Host compute buffer size =    12.01 MiB
llama_new_context_with_model: graph nodes  = 710
llama_new_context_with_model: graph splits = 191 (with bs=512), 3 (with bs=1)
common_init_from_params: setting dry_penalty_last_n to ctx_size = 4096
common_init_from_params: warming up the model with an empty run - please wait ... (--no-warmup to disable)
ggml_cuda_compute_forward: ADD failed
ROCm error: invalid device function
  current device: 0, in function ggml_cuda_compute_forward at /home/user/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:2192
  err
```

**Comment by IMbackK** [comment]
Add not working is weird since that kernel not changed in a very long time
Could you try b4545? also try building against an older llvm, maybe the one from rocm 6.2.

**Comment by pcfreak30** [comment]
> also try building against an older llvm,

` also try building against an older llvm,` can you please clarify.

Also I figured I would ask, but do you know anything off you head that would cause every model to produce gibberish in a multi-gpu setup? ive tested several cards and ONLY when 2 are used so far does any efforts break, but it always works with a single card. This is on ollama.

Currently doing troubleshooting on this.

**Comment by IMbackK** [comment]
> > also try building against an older llvm,
> 
> ` also try building against an older llvm,` can you please clarify.

essentially build llamacpp against rocm 6.2

> Also I figured I would ask, but do you know anything off you head that would cause every model to produce gibberish in a multi-gpu setup? ive tested several cards and ONLY when 2 are used so far does any efforts break, but it always works with a single card. This is on ollama.

Rocm p2p shared memory is broken without a kernel with downstream KFD patches
You could:
1. Build and install a kernel with downstream kdf patches
2. disable the AMDHSA PCIE P2P config in your kernel and rebuild
3. disable p2p in llamacpp via GGML_CUDA_NO_PEER_COPY

I also noticed that your trace is from a old version of llamacpp please do these steps:

1. build llamacpp from current git on your current setup and try that.
2. build llamacpp git against rocm 6.2 to reduce the chance that it is a change in the compiler breaking it
    * gfx900 has not been supported by amd for years so its not unlikely that a compiler change might break it
3. build b4545 and try this.

**Comment by pcfreak30** [comment]
> > > also try building against an older llvm,
> > 
> > 
> > ` also try building against an older llvm,` can you please clarify.
> 
> essentially build llamacpp against rocm 6.2
> 
> > Also I figured I would ask, but do you know anything off you head that would cause every model to produce gibberish in a multi-gpu setup? ive tested several cards and ONLY when 2 are used so far does any efforts break, but it always works with a single card. This is on ollama.
> 
> Rocm p2p shared memory is broken without a kernel with downstream KFD patches You could:
> 
> 1. Build and install a kernel with downstream kdf patches
> 2. disable the AMDHSA PCIE P2P config in your kernel and rebuild
> 3. disable p2p in llamacpp via GGML_CUDA_NO_PEER_COPY
> 
> I also noticed that your trace is from a old version of llamacpp. Please do these steps:
> 
> 1. build llamacpp from current git on your current setup and try that.
> 2. build llamacpp git against rocm 6.2 to reduce the chance that it is a change in the compiler breaking it
>    
>    * gfx900 has not been supported by amd for years so its not unlikely that a compiler change might break it
> 3. build b4545 and try this.

```
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 2 ROCm devices:
  Device 0: Radeon RX Vega, compute capability 9.0, VMM: no
  Device 1: Radeon RX Vega, compute capability 9.0, VMM: no
build: 4545 (9755129c) with cc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0 for x86_64-linux-gnu
main: llama backend init
main: load the model and apply lora adapter, if any
common_download_file: previous metadata file found /root/.cache/llama.cpp/TheBloke_openbuddy-llama2-34b-v11.1-bf16-GGUF_openbuddy-llama2-34b-v11.1-bf16.Q2_K.gguf.json: {"etag":"\"3a89c88290f47e19000df45ffc6b9302-892\"","lastModified":"Sun, 24 Sep 2023 09:44:18 GMT","url":"https://huggingface.co/TheBloke/openbuddy-llama2-34b-v11.1-bf16-GGUF/resolve/main/openbuddy-llama2-34b-v11.1-bf16.Q2_K.gguf"}
curl_perform_with_retry: Trying to download from https://huggingface.co/TheBloke/openbuddy-llama2-34b-v11.1-bf16-GGUF/resolve/main/openbuddy-llama2-34b-v11.1-bf16.Q2_K.gguf (attempt 1 of 3)...
llama_model_load_from_file_impl: using device ROCm0 (Radeon RX Vega) - 7802 MiB free
llama_model_load_from_file_impl: using device ROCm1 (Radeon RX Vega) - 8160 MiB free
llama_model_loader: loaded meta data with 20 key-value pairs and 435 tensors from /root/.cache/llama.cpp/TheBloke_openbuddy-llama2-34b-v11.1-bf16-GGUF_openbuddy-llama2-34b-v11.1-bf16.Q2_K.gguf (version GGUF V2)
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = openbuddy_openbuddy-llama2-34b-v11.1-...
llama_model_loader: - kv   2:                       llama.context_length u32              = 16384
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 8192
llama_model_loader: - kv   4:                          llama.block_count u32              = 48
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 22016
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 64
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                       llama.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv  11:                          general.file_type u32              = 10
llama_model_loader: - kv  12:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  13:                      tokenizer.ggml.tokens arr[str,37632]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
llama_model_loader: - kv  14:                      tokenizer.ggml.scores arr[f32,37632]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  15:                  tokenizer.ggml.token_type arr[i32,37632]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  16:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  17:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  18:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  19:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   97 tensors
llama_model_loader: - type q2_K:   97 tensors
llama_model_loader: - type q3_K:  240 tensors
llama_model_loader: - type q6_K:    1 tensors
print_info: file format = GGUF V2
print_info: file type   = Q2_K - Medium
print_info: file size   = 13.28 GiB (3.37 BPW) 
load: special_eos_id is not in special_eog_ids - the tokenizer config may be incorrect
load: special tokens cache size = 3
load: token to piece cache size = 0.1854 MB
print_info: arch             = llama
print_info: vocab_only       = 0
print_info: n_ctx_train      = 16384
print_info: n_embd           = 8192
print_info: n_layer          = 48
print_info: n_head           = 64
print_info: n_head_kv        = 8
print_info: n_rot            = 128
print_info: n_swa            = 0
print_info: n_embd_head_k    = 128
print_info: n_embd_head_v    = 128
print_info: n_gqa            = 8
print_info: n_embd_k_gqa     = 1024
print_info: n_embd_v_gqa     = 1024
print_info: f_norm_eps       = 0.0e+00
print_info: f_norm_rms_eps   = 1.0e-05
print_info: f_clamp_kqv      = 0.0e+00
print_info: f_max_alibi_bias = 0.0e+00
print_info: f_logit_scale    = 0.0e+00
print_info: n_ff             = 22016
print_info: n_expert         = 0
print_info: n_expert_used    = 0
print_info: causal attn      = 1
print_info: pooling type     = 0
print_info: rope type        = 0
print_info: rope scaling     = linear
print_info: freq_base_train  = 1000000.0
print_info: freq_scale_train = 1
print_info: n_ctx_orig_yarn  = 16384
print_info: rope_finetuned   = unknown
print_info: ssm_d_conv       = 0
print_info: ssm_d_inner      = 0
print_info: ssm_d_state      = 0
print_info: ssm_dt_rank      = 0
print_info: ssm_dt_b_c_rms   = 0
print_info: model type       = 34B
print_info: model params     = 33.84 B
print_info: general.name     = openbuddy_openbuddy-llama2-34b-v11.1-bf16
print_info: vocab type       = SPM
print_info: n_vocab          = 37632
print_info: n_merges         = 0
print_info: BOS token        = 1 '<s>'
print_info: EOS token        = 2 '</s>'
print_info: UNK token        = 0 '<unk>'
print_info: LF token         = 13 '<0x0A>'
print_info: EOG token        = 2 '</s>'
print_info: max token length = 48
load_tensors: offloading 20 repeating layers to GPU
load_tensors: offloaded 20/49 layers to GPU
load_tensors:        ROCm0 model buffer size =  2763.44 MiB
load_tensors:        ROCm1 model buffer size =  2763.44 MiB
load_tensors:   CPU_Mapped model buffer size = 13602.17 MiB
llama_init_from_model: n_seq_max     = 1
llama_init_from_model: n_ctx         = 4096
llama_init_from_model: n_ctx_per_seq = 4096
llama_init_from_model: n_batch       = 2048
llama_init_from_model: n_ubatch      = 512
llama_init_from_model: flash_attn    = 0
llama_init_from_model: freq_base     = 1000000.0
llama_init_from_model: freq_scale    = 1
llama_init_from_model: n_ctx_per_seq (4096) < n_ctx_train (16384) -- the full capacity of the model will not be utilized
llama_kv_cache_init: kv_size = 4096, offload = 1, type_k = 'f16', type_v = 'f16', n_layer = 48, can_shift = 1
llama_kv_cache_init:      ROCm0 KV buffer size =   160.00 MiB
llama_kv_cache_init:      ROCm1 KV buffer size =   160.00 MiB
llama_kv_cache_init:        CPU KV buffer size =   448.00 MiB
llama_init_from_model: KV self size  =  768.00 MiB, K (f16):  384.00 MiB, V (f16):  384.00 MiB
llama_init_from_model:        CPU  output buffer size =     0.14 MiB
llama_init_from_model:      ROCm0 compute buffer size =   597.00 MiB
llama_init_from_model:      ROCm1 compute buffer size =   584.00 MiB
llama_init_from_model:  ROCm_Host compute buffer size =    24.01 MiB
llama_init_from_model: graph nodes  = 1542
llama_init_from_model: graph splits = 313 (with bs=512), 4 (with bs=1)
common_init_from_params: setting dry_penalty_last_n to ctx_size = 4096
main: llama threadpool init, n_threads = 8

system_info: n_threads = 8 (n_threads_batch = 8) / 16 | ROCm : PEER_MAX_BATCH_SIZE = 128 | CPU : SSE3 = 1 | SSSE3 = 1 | AVX = 1 | AVX2 = 1 | F16C = 1 | FMA = 1 | LLAMAFILE = 1 | OPENMP = 1 | AARCH64_REPACK = 1 | 

sampler seed: 1438474870
sampler params: 
	repeat_last_n = 64, repeat_penalty = 1.000, frequency_penalty = 0.000, presence_penalty = 0.000
	dry_multiplier = 0.000, dry_base = 1.750, dry_allowed_length = 2, dry_penalty_last_n = 4096
	top_k = 40, top_p = 0.950, min_p = 0.050, xtc_probability = 0.000, xtc_threshold = 0.100, typical_p = 1.000, temp = 0.800
	mirostat = 0, mirostat_lr = 0.100, mirostat_ent = 5.000
sampler chain: logits -> logit-bias -> penalties -> dry -> top-k -> typical -> top-p -> min-p -> xtc -> temp-ext -> dist 
generate: n_ctx = 4096, n_batch = 2048, n_predict = -1, n_keep = 1

 Once upon a time,

```

`b4545` seems to make it farther and not crash. im intentionally trying larger models that force use of 2 gpus. though it does hang, though IDK if that b/c it needs a lot of cpu or what.

```
========================================== ROCm System Management Interface ==========================================
==================================================== Concise Info ====================================================
Device  Node  IDs              Temp    Power     Partitions          SCLK    MCLK    Fan  Perf  PwrCap  VRAM%  GPU%  
              (DID,     GUID)  (Edge)  (Socket)  (Mem, Compute, ID)                                                  
======================================================================================================================
0       1     0x687f,   29424  42.0°C  9.0W      N/A, N/A, 0         852Mhz  167Mhz  0%   auto  185.0W  47%    0%    
1       2     0x687f,   1087   35.0°C  4.0W      N/A, N/A, 0         852Mhz  167Mhz  0%   auto  260.0W  47%    0%    
======================================================================================================================
================================================ End of ROCm SMI Log =================================================
```

**Comment by pcfreak30** [comment]
When trying to offload 30 layers though, with `strace` I get

```
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x4b, 0x20, 0x28), 0x7ffe5107f310) = -1 ENOMEM (Cannot allocate memory)
mmap(NULL, 79601664, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x745c19400000
munmap(0x745c19400000, 2097152)         = 0
munmap(0x745c1dfe9000, 4096)            = 0
ioctl(3, AMDKFD_IOC_ALLOC_MEMORY_OF_GPU, 0x7ffe5107f2a0) = -1 ENOMEM (Cannot allocate memory)
mbind(0x745c19600000, 77500416, MPOL_DEFAULT, NULL, 0, 0) = 0

```

then.

```
ioctl(3, AMDKFD_IOC_ALLOC_MEMORY_OF_GPU, 0x7ffe51080c70) = -1 ENOMEM (Cannot allocate memory)
mbind(0x745c0dc00000, 19582976, MPOL_DEFAULT, NULL, 0, 0) = 0
munmap(0x745c0dc00000, 19582976)        = 0
ioctl(3, AMDKFD_IOC_UNMAP_MEMORY_FROM_GPU, 0x7ffe51080d20) = 0
ioctl(3, AMDKFD_IOC_FREE_MEMORY_OF_GPU, 0x7ffe51080d60) = 0
mbind(0x7463a3b7e000, 4096, MPOL_DEFAULT, NULL, 0, 0) = 0
munmap(0x7463a3b7e000, 4096)            = 0
ioctl(3, AMDKFD_IOC_UNMAP_MEMORY_FROM_GPU, 0x7ffe51080d20) = 0
ioctl(3, AMDKFD_IOC_FREE_MEMORY_OF_GPU, 0x7ffe51080d90) = 0
mbind(0x7463a3bfc000, 4096, MPOL_DEFAULT, NULL, 0, 0) = 0
munmap(0x7463a3bfc000, 4096)            = 0
ioctl(3, AMDKFD_IOC_UNMAP_MEMORY_FROM_GPU, 0x7ffe51081020) = 0
ioctl(3, AMDKFD_IOC_FREE_MEMORY_OF_GPU, 0x7ffe51081060) = 0
mbind(0x7463a3bfe000, 4096, MPOL_DEFAULT, NULL, 0, 0) = 0
munmap(0x7463a3bfe000, 4096)            = 0
ioctl(3, AMDKFD_IOC_UNMAP_MEMORY_FROM_GPU, 0x7ffe51081050) = 0
ioctl(3, AMDKFD_IOC_FREE_MEMORY_OF_GPU, 0x7ffe51081090) = 0
mbind(0x7463a410a000, 4096, MPOL_DEFAULT, NULL, 0, 0) = 0
munmap(0x7463a410a000, 4096)            = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x18} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
```

**Comment by IMbackK** [comment]
Did you build with GGML_CUDA_NO_PEER_COPY=On ? what model are you trying to run? what command?
please try current git first not b4545 and build with GGML_CUDA_NO_PEER_COPY=On

all in all please follow the order i mentioned above

**Comment by IMbackK** [comment]
are you on a system that supports pcie atomics?

**Comment by pcfreak30** [comment]
@IMbackK 

I am now running on master and can confirm it works without the gpu kernel add problem.

`-DGGML_CUDA_NO_PEER_COPY=on` seems to fix the garbled output after some A/B testing. I have not touched the kernel or `AMDHSA PCIE P2P config` yet. Plus im not sure where to find those patches you refer to to begin with.

more than 20 or so layers causes a memory issue and you get a segfault from a free()? call?

im running `HIPCXX="$(hipconfig -l)/clang" HIP_PATH="$(hipconfig -R)"     cmake -S . -B build -DGGML_HIP=ON -DAMDGPU_TARGETS=gfx900 -DCMAKE_BUILD_TYPE=Release  -DGGML_CUDA_NO_PEER_COPY=on -DLLAMA_CURL=ON && cmake  --build build --config Release -- -j 16`

I am also using `./build/bin/llama-cli -hf  MaziyarPanahi/Meta-Llama-3-8B-Instruct-GGUF:Q8_0 -p "Once upon a time," -ngl 20 --no-warmup`

The initial message returns no response, then `say hello` returns something real. However, something is up where it only does like 1 token every 30+ seconds. the CPU is a i9-9900K so its not the worst (15 logical cores).

`are you on a system that supports pcie atomics` Sorry I have never heard of this, no idea what that is.

So right now im am interested to know: 

* If there are GPU memory issues that exist here and if so what to look at.
* Why the tps is worse then dialup when ~50% is offloaded.
* Why I cannot seem to offload everything when the model is 8 GB, and I have 16 gb of GPU ram, or if there is overhead preventing it, it seems llama is segfaulting.
* why llama seems to segfault trying to do roughly 30 or more layers.

Kudos

**Comment by IMbackK** [comment]
Your system supports pcie atomics.

The reason this runs out of memory is because llama 3 has a very large context window which uses a lot of vram over the size of the model you can try

`./build/bin/llama-cli -hf  MaziyarPanahi/Meta-Llama-3-8B-Instruct-GGUF:Q8_0 -p "Once upon a time," -ngl 99 --no-warmup - c 4096`
which should work and be fairly fast

anyhow llamacpp should not segfault, it should rather abort with an error when it runs out of vram.

Please try running this reproducer:

```
#include <hip/hip_runtime.h>
#include <stdio.h>

int main()
{
	while(true)
	{
		void* leak;
		hipError_t err = hipMalloc(&leak, 1024*1024*1024);
		if(err != hipSuccess)
		{
			fprintf(stderr, "Hip Error: %s: %s\n", hipGetErrorName(err), hipGetErrorString(err));
			break;
		}
	}
	
	return 0;
}
```

you can compile it with: `hipcc hipmallocrepo.cpp -o hipmallocrepo`
running hipmallocrepo should result in `Hip Error: hipErrorOutOfMemory: out of memory` please report if this segfaults for you instead.

**Comment by pcfreak30** [comment]
@IMbackK 

````
/hipmallocrepo
Hip Error: hipErrorOutOfMemory: out of memory
```

`./build/bin/llama-cli -hf  MaziyarPanahi/Meta-Llama-3-8B-Instruct-GGUF:Q8_0 -p "Once upon a time," -ngl 99 --no-warmup - c 4096`

```
print_info: max token length = 256
load_tensors: offloading 32 repeating layers to GPU
load_tensors: offloading output layer to GPU
load_tensors: offloaded 33/33 layers to GPU
load_tensors:        ROCm0 model buffer size =  3757.53 MiB
load_tensors:        ROCm1 model buffer size =  3847.80 MiB
load_tensors:   CPU_Mapped model buffer size =   532.31 MiB
free(): invalid pointer
Aborted (core dumped)
```

**Comment by pcfreak30** [comment]
@IMbackK can you also please explain what `GGML_CUDA_NO_PEER_COPY` *does* exactly?

**Comment by pcfreak30** [comment]
Another detail. Trying to load all layers and limiting to 1 gpu device does error vs panic:

```
llama_init_from_model:  ROCm_Host  output buffer size =     0.49 MiB
ggml_backend_cuda_buffer_type_alloc_buffer: allocating 296.00 MiB on device 1: cudaMalloc failed: out of memory
ggml_gallocr_reserve_n: failed to allocate ROCm1 buffer of size 310382592
ggml_backend_cuda_buffer_type_alloc_buffer: allocating 296.00 MiB on device 1: cudaMalloc failed: out of memory
ggml_gallocr_reserve_n: failed to allocate ROCm1 buffer of size 310382592
llama_init_from_model: failed to allocate compute buffers
common_init_from_params: failed to create context with model '/root/.cache/llama.cpp/MaziyarPanahi_Meta-Llama-3-8B-Instruct-GGUF_Meta-Llama-3-8B-Instruct.Q8_0.gguf'
main: error: unable to load model
```

**Comment by IMbackK** [comment]
> ```
> print_info: max token length = 256
> load_tensors: offloading 32 repeating layers to GPU
> load_tensors: offloading output layer to GPU
> load_tensors: offloaded 33/33 layers to GPU
> load_tensors:        ROCm0 model buffer size =  3757.53 MiB
> load_tensors:        ROCm1 model buffer size =  3847.80 MiB
> load_tensors:   CPU_Mapped model buffer size =   532.31 MiB
> free(): invalid pointer
> Aborted (core dumped)
> ```

1. Please rebuild llamacpp with -DCMAKE_BUILD_TYPE=Debug and get a backtrace of this from gdb

2. Please download a 8b 4_k_m model to disk, mask away all but one gpu with ROCR_VISIBLE_DEVICES and try it with -c 1024 while loading the model from disk.

3. Please try this attempt at a reproducer:

```
#include <hip/hip_runtime.h>
#include <stdio.h>

int main()      
{               
        int device = 0;
        while(true)
        {               
                hipError_t err = hipSetDevice(device);
                if(err != hipSuccess)
                {
                        fprintf(stderr, "Hip Error: %s: %s\n", hipGetErrorName(err), hipGetErrorString(err));
                        break;
                }
                
                device = !device;
        
                void* leak;
                err = hipMalloc(&leak, 1024*1024*1024);
                if(err != hipSuccess)
                {
                        fprintf(stderr, "Hip Error: %s: %s\n", hipGetErrorName(err), hipGetErrorString(err));
                        break;
                }
                        
                err = hipMalloc(&leak, 1024*1024*1024);
                if(err != hipSuccess)
                {
                        fprintf(stderr, "Hip Error: %s: %s\n", hipGetErrorName(err), hipGetErrorString(err));
                        break;
                }
                        
                err = hipFree(leak);
                if(err != hipSuccess)
                {
                        fprintf(stderr, "Hip Error: %s: %s\n", hipGetErrorName(err), hipGetErrorString(err));
                        break;
                }
        }

        return 0;
}

```

**Comment by Diablo-D3** [comment]
Hey, I'm also in the same boat with this.

9800x3D + 7900XTX on Windows, using the released HIP gfx1101 binaries, I also get same error on any recent builds.

For b4607:

```console
ROCm error: invalid device function
  current device: 0, in function ggml_cuda_compute_forward at D:/a/llama.cpp/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:2313
  err
D:/a/llama.cpp/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:72: ROCm error
```

The Vulkan build, however, seems to work fine.

A suggestion of trying b4545 (earlier in the thread) doesn't fix this.

**Comment by pcfreak30** [comment]
> Hey, I'm also in the same boat with this.
> 
> 9800x3D + 7900XTX on Windows, using the released HIP gfx1101 binaries, I also get same error on any recent builds.
> 
> For b4607, using Gemma 1.1 7B Q4_K_M (a known working common model):
> 
> ROCm error: invalid device function
>   current device: 0, in function ggml_cuda_compute_forward at D:/a/llama.cpp/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:2313
>   err
> D:/a/llama.cpp/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:72: ROCm error
> The Vulkan build, however, seems to work fine.
> 
> A suggestion of trying b4545 (earlier in the thread) doesn't fix this.

Don't use a tag, just try  git master 🤷 .

**Comment by pcfreak30** [comment]
1.

> > ```
> > print_info: max token length = 256
> > load_tensors: offloading 32 repeating layers to GPU
> > load_tensors: offloading output layer to GPU
> > load_tensors: offloaded 33/33 layers to GPU
> > load_tensors:        ROCm0 model buffer size =  3757.53 MiB
> > load_tensors:        ROCm1 model buffer size =  3847.80 MiB
> > load_tensors:   CPU_Mapped model buffer size =   532.31 MiB
> > free(): invalid pointer
> > Aborted (core dumped)
> > ```
> 
> 1. Please rebuild llamacpp with -DCMAKE_BUILD_TYPE=Debug and get a backtrace of this from gdb
> 2. Please download a 8b 4_k_m model to disk, mask away all but one gpu with ROCR_VISIBLE_DEVICES and try it with -ngl 99 and -c 1024 while loading the model from disk.
> 3. Please try this attempt at a reproducer:
> 
> ```
> #include <hip/hip_runtime.h>
> #include <stdio.h>
> 
> int main()      
> {               
>         int device = 0;
>         while(true)
>         {               
>                 hipError_t err = hipSetDevice(device);
>                 if(err != hipSuccess)
>                 {
>                         fprintf(stderr, "Hip Error: %s: %s\n", hipGetErrorName(err), hipGetErrorString(err));
>                         break;
>                 }
>                 
>                 device = !device;
>         
>                 void* leak;
>                 err = hipMalloc(&leak, 1024*1024*1024);
>                 if(err != hipSuccess)
>                 {
>                         fprintf(stderr, "Hip Error: %s: %s\n", hipGetErrorName(err), hipGetErrorString(err));
>                         break;
>                 }
>                         
>                 err = hipMalloc(&leak, 1024*1024*1024);
>                 if(err != hipSuccess)
>                 {
>                         fprintf(stderr, "Hip Error: %s: %s\n", hipGetErrorName(err), hipGetErrorString(err));
>                         break;
>                 }
>                         
>                 err = hipFree(leak);
>                 if(err != hipSuccess)
>                 {
>                         fprintf(stderr, "Hip Error: %s: %s\n", hipGetErrorName(err), hipGetErrorString(err));
>                         break;
>                 }
>         }
> 
>         return 0;
> }
> ```

```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff704526e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff70288ff in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff70297b6 in __libc_message_impl (fmt=fmt@entry=0x7ffff71ce8d7 "%s\n") at ../sysdeps/posix/libc_fatal.c:132
#6  0x00007ffff70a8fe5 in malloc_printerr (str=str@entry=0x7ffff71cc672 "free(): invalid pointer") at ./malloc/malloc.c:5772
#7  0x00007ffff70ab37c in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at ./malloc/malloc.c:4507
#8  0x00007ffff70add9e in __GI___libc_free (mem=0x555555fd5958) at ./malloc/malloc.c:3398
#9  0x00007fffecdd84dc in ?? () from /opt/rocm-6.3.2/lib/llvm/bin/../../../lib/libamdhip64.so.6
#10 0x00007fffece26830 in ?? () from /opt/rocm-6.3.2/lib/llvm/bin/../../../lib/libamdhip64.so.6
#11 0x00007fffece26c9a in ?? () from /opt/rocm-6.3.2/lib/llvm/bin/../../../lib/libamdhip64.so.6
#12 0x00007fffecde69b6 in ?? () from /opt/rocm-6.3.2/lib/llvm/bin/../../../lib/libamdhip64.so.6
#13 0x00007fffecdacc95 in ?? () from /opt/rocm-6.3.2/lib/llvm/bin/../../../lib/libamdhip64.so.6
#14 0x00007fffecc171fb in ?? () from /opt/rocm-6.3.2/lib/llvm/bin/../../../lib/libamdhip64.so.6
#15 0x00007fffecc1aa01 in ?? () from /opt/rocm-6.3.2/lib/llvm/bin/../../../lib/libamdhip64.so.6
#16 0x00007fffecc1caf4 in ?? () from /opt/rocm-6.3.2/lib/llvm/bin/../../../lib/libamdhip64.so.6
#17 0x00007ffff2c8cf80 in ggml_backend_cuda_buffer_set_tensor (buffer=<optimized out>, tensor=0x55555e295220, data=0x7ffce1bce4e0, offset=<optimized out>, size=4456448) at /home/user/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:568
#18 0x00007ffff7822bd6 in ggml_backend_tensor_set (tensor=0x55555e295220, data=0x7ffce1bce4e0, offset=0, size=4456448) at /home/user/llama.cpp/ggml/src/ggml-backend.cpp:266
#19 0x00007ffff7d17d52 in llama_model_loader::load_all_data (this=0x7fffffffa510, ctx=0x55555e28f010, bufs=std::unordered_map with 1 element = {...}, lmlocks=0x0, progress_callback=0x0, progress_callback_user_data=0x0) at /home/user/llama.cpp/src/llama-model-loader.cpp:1020
#20 0x00007ffff7d5b5a1 in llama_model::load_tensors (this=0x555557fa8100, ml=...) at /home/user/llama.cpp/src/llama-model.cpp:3524
#21 0x00007ffff7c64610 in llama_model_load (fname="/root/.cache/llama.cpp/MaziyarPanahi_Meta-Llama-3-8B-Instruct-GGUF_Meta-Llama-3-8B-Instruct.Q8_0.gguf", splits=std::vector of length 0, capacity 0, model=..., params=...) at /home/user/llama.cpp/src/llama.cpp:73
#22 0x00007ffff7c6d095 in llama_model_load_from_file_impl (path_model="/root/.cache/llama.cpp/MaziyarPanahi_Meta-Llama-3-8B-Instruct-GGUF_Meta-Llama-3-8B-Instruct.Q8_0.gguf", splits=std::vector of length 0, capacity 0, params=...) at /home/user/llama.cpp/src/llama.cpp:9485
#23 0x00007ffff7c6d345 in llama_model_load_from_file (path_model=0x5555562dc9a0 "/root/.cache/llama.cpp/MaziyarPanahi_Meta-Llama-3-8B-Instruct-GGUF_Meta-Llama-3-8B-Instruct.Q8_0.gguf", params=...) at /home/user/llama.cpp/src/llama.cpp:9512
#24 0x000055555567634a in common_load_model_from_url (model_url="https://huggingface.co/MaziyarPanahi/Meta-Llama-3-8B-Instruct-GGUF/resolve/main/Meta-Llama-3-8B-Instruct.Q8_0.gguf", local_path="/root/.cache/llama.cpp/MaziyarPanahi_Meta-Llama-3-8B-Instruct-GGUF_Meta-Llama-3-8B-Instruct.Q8_0.gguf", hf_token="", params=...) at /home/user/llama.cpp/common/common.cpp:1479
#25 0x0000555555676490 in common_load_model_from_hf (repo="MaziyarPanahi/Meta-Llama-3-8B-Instruct-GGUF", remote_path="Meta-Llama-3-8B-Instruct.Q8_0.gguf", local_path="/root/.cache/llama.cpp/MaziyarPanahi_Meta-Llama-3-8B-Instruct-GGUF_Meta-Llama-3-8B-Instruct.Q8_0.gguf", hf_token="", params=...) at /home/user/llama.cpp/common/common.cpp:1502
#26 0x0000555555672613 in common_init_from_params (params=...) at /home/user/llama.cpp/common/common.cpp:908
#27 0x00005555555c35f5 in main (argc=8, argv=0x7fffffffe3e8) at /home/user/llama.cpp/examples/main/main.cpp:150
__pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
warning: 44	./nptl/pthread_kill.c: No such file or directory
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff704526e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff70288ff in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff70297b6 in __libc_message_impl (fmt=fmt@entry=0x7ffff71ce8d7 "%s\n") at ../sysdeps/posix/libc_fatal.c:132
#6  0x00007ffff70a8fe5 in malloc_printerr (str=str@entry=0x7ffff71cc672 "free(): invalid pointer") at ./malloc/malloc.c:5772
#7  0x00007ffff70ab37c in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at ./malloc/malloc.c:4507
#8  0x00007ffff70add9e in __GI___libc_free (mem=0x555555fd5958) at ./malloc/malloc.c:3398
#9  0x00007fffecdd84dc in ?? () from /opt/rocm-6.3.2/lib/llvm/bin/../../../lib/libamdhip64.so.6
#10 0x00007fffece26830 in ?? () from /opt/rocm-6.3.2/lib/llvm/bin/../../../lib/libamdhip64.so.6
#11 0x00007fffece26c9a in ?? () from /opt/rocm-6.3.2/lib/llvm/bin/../../../lib/libamdhip64.so.6
#12 0x00007fffecde69b6 in ?? () from /opt/rocm-6.3.2/lib/llvm/bin/../../../lib/libamdhip64.so.6
#13 0x00007fffecdacc95 in ?? () from /opt/rocm-6.3.2/lib/llvm/bin/../../../lib/libamdhip64.so.6
#14 0x00007fffecc171fb in ?? () from /opt/rocm-6.3.2/lib/llvm/bin/../../../lib/libamdhip64.so.6
#15 0x00007fffecc1aa01 in ?? () from /opt/rocm-6.3.2/lib/llvm/bin/../../../lib/libamdhip64.so.6
#16 0x00007fffecc1caf4 in ?? () from /opt/rocm-6.3.2/lib/llvm/bin/../../../lib/libamdhip64.so.6
#17 0x00007ffff2c8cf80 in ggml_backend_cuda_buffer_set_tensor (buffer=<optimized out>, tensor=0x55555e295220, data=0x7ffce1bce4e0, offset=<optimized out>, size=4456448) at /home/user/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:568
#18 0x00007ffff7822bd6 in ggml_backend_tensor_set (tensor=0x55555e295220, data=0x7ffce1bce4e0, offset=0, size=4456448) at /home/user/llama.cpp/ggml/src/ggml-backend.cpp:266
#19 0x00007ffff7d17d52 in llama_model_loader::load_all_data (this=0x7fffffffa510, ctx=0x55555e28f010, bufs=std::unordered_map with 1 element = {...}, lmlocks=0x0, progress_callback=0x0, progress_callback_user_data=0x0) at /home/user/llama.cpp/src/llama-model-loader.cpp:1020
#20 0x00007ffff7d5b5a1 in llama_model::load_tensors (this=0x555557fa8100, ml=...) at /home/user/llama.cpp/src/llama-model.cpp:3524
#21 0x00007ffff7c64610 in llama_model_load (fname="/root/.cache/llama.cpp/MaziyarPanahi_Meta-Llama-3-8B-Instruct-GGUF_Meta-Llama-3-8B-Instruct.Q8_0.gguf", splits=std::vector of length 0, capacity 0, model=..., params=...) at /home/user/llama.cpp/src/llama.cpp:73
#22 0x00007ffff7c6d095 in llama_model_load_from_file_impl (path_model="/root/.cache/llama.cpp/MaziyarPanahi_Meta-Llama-3-8B-Instruct-GGUF_Meta-Llama-3-8B-Instruct.Q8_0.gguf", splits=std::vector of length 0, capacity 0, params=...) at /home/user/llama.cpp/src/llama.cpp:9485
#23 0x00007ffff7c6d345 in llama_model_load_from_file (path_model=0x5555562dc9a0 "/root/.cache/llama.cpp/MaziyarPanahi_Meta-Llama-3-8B-Instruct-GGUF_Meta-Llama-3-8B-Instruct.Q8_0.gguf", params=...) at /home/user/llama.cpp/src/llama.cpp:9512
#24 0x000055555567634a in common_load_model_from_url (model_url="https://huggingface.co/MaziyarPanahi/Meta-Llama-3-8B-Instruct-GGUF/resolve/main/Meta-Llama-3-8B-Instruct.Q8_0.gguf", local_path="/root/.cache/llama.cpp/MaziyarPanahi_Meta-Llama-3-8B-Instruct-GGUF_Meta-Llama-3-8B-Instruct.Q8_0.gguf", hf_token="", params=...) at /home/user/llama.cpp/common/common.cpp:1479
#25 0x0000555555676490 in common_load_model_from_hf (repo="MaziyarPanahi/Meta-Llama-3-8B-Instruct-GGUF", remote_path="Meta-Llama-3-8B-Instruct.Q8_0.gguf", local_path="/root/.cache/llama.cpp/MaziyarPanahi_Meta-Llama-3-8B-Instruct-GGUF_Meta-Llama-3-8B-Instruct.Q8_0.gguf", hf_token="", params=...) at /home/user/llama.cpp/common/common.cpp:1502
#26 0x0000555555672613 in common_init_from_params (params=...) at /home/user/llama.cpp/common/common.cpp:908
#27 0x00005555555c35f5 in main (argc=8, argv=0x7fffffffe3e8) at /home/user/llama.cpp/examples/main/main.cpp:150

```
2. a 8 gb 4_k_m model works with all layers offloaded, 1024 context, and only 1 gpu made visible at the driver level.

3. the reproducer does not panic
```
./hipmallocrepo
Hip Error: hipErrorOutOfMemory: out of memory
```

**Comment by IMbackK** [comment]
What are all the gpus in your system (not just the ones used)? (`rocminfo | grep amdgcn-amd`) 

Looks like it crashes when trying to copy a buffer to device, not malloc a buffer, i can try and make a reproducer for that later.
It looks very unlikely that this is a bug in llamacpp, but rather a bug in rocm or the kernel. While your gpus are no longer supported, amd folks are usually quite ready to fix sutch things even in out of support devices if you bring it to them with a reproducer.
To give me an idea what to try and reproduce please install debug symbols for libamdhip64/ rocm generally and grab the backtrace again.

**Comment by pcfreak30** [comment]
> What are all the gpus in your system (not just the ones used)? (`rocminfo | grep amdgcn-amd`)
> 
> Looks like it crashes when trying to copy a buffer to device, not malloc a buffer, i can try and make a reproducer for that later. It looks very unlikely that this is a bug in llamacpp, but rather a bug in rocm or the kernel. While your gpus are no longer supported, amd folks are usually quite ready to fix sutch things even in out of support devices if you bring it to them with a reproducer. To give me an idea what to try and reproduce please install debug symbols for libamdhip64/ rocm generally and grab the backtrace again.

```
      Name:                    amdgcn-amd-amdhsa--gfx900:xnack-   
      Name:                    amdgcn-amd-amdhsa--gfx900:xnack- 
```

What packages do you want me to install? https://repo.radeon.com/rocm/apt/6.3.2/pool/main/r/

**Comment by IMbackK** [comment]
please install all the *-dbgsym packages that correspond to the rocm packages that you have installed

**Comment by pcfreak30** [comment]
> please install all the *-dbgsym packages that correspond to the rocm packages that you have installed

```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff704526e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff70288ff in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff70297b6 in __libc_message_impl (fmt=fmt@entry=0x7ffff71ce8d7 "%s\n") at ../sysdeps/posix/libc_fatal.c:132
#6  0x00007ffff70a8fe5 in malloc_printerr (str=str@entry=0x7ffff71cc672 "free(): invalid pointer") at ./malloc/malloc.c:5772
#7  0x00007ffff70ab37c in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at ./malloc/malloc.c:4507
#8  0x00007ffff70add9e in __GI___libc_free (mem=0x555555fd5958) at ./malloc/malloc.c:3398
#9  0x00007fffecdd84dc in std::__new_allocator<std::_List_node<amd::roc::Memory*> >::deallocate (this=0x555555fd5958, __n=1, __p=0x555555fd5958) at /usr/include/c++/13/bits/new_allocator.h:156
#10 std::allocator_traits<std::allocator<std::_List_node<amd::roc::Memory*> > >::deallocate (__n=1, __p=0x555555fd5958, __a=...) at /usr/include/c++/13/bits/alloc_traits.h:517
#11 std::__cxx11::_List_base<amd::roc::Memory*, std::allocator<amd::roc::Memory*> >::_M_put_node (__p=0x555555fd5958, this=0x555555fd5958) at /usr/include/c++/13/bits/stl_list.h:522
#12 std::__cxx11::list<amd::roc::Memory*, std::allocator<amd::roc::Memory*> >::_M_erase (__position=..., this=0x555555fd5958) at /usr/include/c++/13/bits/stl_list.h:2024
#13 std::__cxx11::list<amd::roc::Memory*, std::allocator<amd::roc::Memory*> >::erase (__position=..., this=0x555555fd5958) at /usr/include/c++/13/bits/list.tcc:158
#14 amd::roc::Device::XferBuffers::acquire (this=0x555555fd5950) at /long_pathname_so_that_rpms_can_package_the_debug_info/src/clr/rocclr/device/rocm/rocdevice.cpp:450
#15 0x00007fffece26830 in amd::roc::DmaBlitManager::writeBuffer (this=this@entry=0x55555e878aa0, srcHost=srcHost@entry=0x7ffce1bce4e0, dstMemory=..., origin=..., size=..., entire=entire@entry=false, copyMetadata=...) at /long_pathname_so_that_rpms_can_package_the_debug_info/src/clr/rocclr/device/rocm/rocblit.cpp:311
#16 0x00007fffece26c9a in amd::roc::KernelBlitManager::writeBuffer (this=this@entry=0x55555e878aa0, srcHost=srcHost@entry=0x7ffce1bce4e0, dstMemory=..., origin=..., size=..., entire=<optimized out>, copyMetadata=...) at /long_pathname_so_that_rpms_can_package_the_debug_info/src/clr/rocclr/device/rocm/rocblit.cpp:1951
#17 0x00007fffecde69b6 in amd::roc::VirtualGPU::submitWriteMemory (this=0x5555599f6fe0, cmd=...) at /long_pathname_so_that_rpms_can_package_the_debug_info/src/clr/rocclr/device/rocm/rocvirtual.cpp:1770
#18 0x00007fffecdacc95 in amd::Command::enqueue (this=0x55555e5806f0) at /long_pathname_so_that_rpms_can_package_the_debug_info/src/clr/rocclr/platform/command.cpp:392
#19 0x00007fffecc171fb in hip::ihipMemcpy (dst=0x7ffa0e8d0000, src=0x7ffce1bce4e0, sizeBytes=4456448, kind=<optimized out>, stream=..., isHostAsync=false, isHostAsync@entry=true, isGPUAsync=true) at /long_pathname_so_that_rpms_can_package_the_debug_info/src/clr/hipamd/src/hip_memory.cpp:637
#20 0x00007fffecc1aa01 in hip::hipMemcpyAsync_common (dst=<optimized out>, dst@entry=0x7ffa0e8d0000, src=<optimized out>, src@entry=0x7ffce1bce4e0, sizeBytes=<optimized out>, sizeBytes@entry=4456448, kind=<optimized out>, kind@entry=hipMemcpyHostToDevice, stream=<optimized out>, stream@entry=0x2) at /long_pathname_so_that_rpms_can_package_the_debug_info/src/clr/hipamd/src/hip_memory.cpp:1567
#21 0x00007fffecc1caf4 in hip::hipMemcpyAsync (dst=0x7ffa0e8d0000, src=<optimized out>, sizeBytes=4456448, kind=hipMemcpyHostToDevice, stream=0x2) at /long_pathname_so_that_rpms_can_package_the_debug_info/src/clr/hipamd/src/hip_memory.cpp:1573
#22 0x00007ffff2c8cf80 in ggml_backend_cuda_buffer_set_tensor (buffer=<optimized out>, tensor=0x55555e2951a0, data=0x7ffce1bce4e0, offset=<optimized out>, size=4456448) at /home/user/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:568
#23 0x00007ffff7822bd6 in ggml_backend_tensor_set (tensor=0x55555e2951a0, data=0x7ffce1bce4e0, offset=0, size=4456448) at /home/user/llama.cpp/ggml/src/ggml-backend.cpp:266
#24 0x00007ffff7d17d52 in llama_model_loader::load_all_data (this=0x7fffffffa510, ctx=0x55555e28ef90, bufs=..., lmlocks=0x0, progress_callback=0x0, progress_callback_user_data=0x0) at /home/user/llama.cpp/src/llama-model-loader.cpp:1020
#25 0x00007ffff7d5b5a1 in llama_model::load_tensors (this=0x555557fa8100, ml=...) at /home/user/llama.cpp/src/llama-model.cpp:3524
#26 0x00007ffff7c64610 in llama_model_load (fname=..., splits=..., model=..., params=...) at /home/user/llama.cpp/src/llama.cpp:73
#27 0x00007ffff7c6d095 in llama_model_load_from_file_impl (path_model=..., splits=..., params=...) at /home/user/llama.cpp/src/llama.cpp:9485
#28 0x00007ffff7c6d345 in llama_model_load_from_file (path_model=0x5555562dc9a0 "/root/.cache/llama.cpp/MaziyarPanahi_Meta-Llama-3-8B-Instruct-GGUF_Meta-Llama-3-8B-Instruct.Q8_0.gguf", params=...) at /home/user/llama.cpp/src/llama.cpp:9512
#29 0x000055555567634a in common_load_model_from_url (model_url=..., local_path=..., hf_token=..., params=...) at /home/user/llama.cpp/common/common.cpp:1479
#30 0x0000555555676490 in common_load_model_from_hf (repo=..., remote_path=..., local_path=..., hf_token=..., params=...) at /home/user/llama.cpp/common/common.cpp:1502
#31 0x0000555555672613 in common_init_from_params (params=...) at /home/user/llama.cpp/common/common.cpp:908
#32 0x00005555555c35f5 in main (argc=8, argv=0x7fffffffe3e8) at /home/user/llama.cpp/examples/main/main.cpp:150
__pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
warning: 44	./nptl/pthread_kill.c: No such file or directory
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff704526e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff70288ff in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff70297b6 in __libc_message_impl (fmt=fmt@entry=0x7ffff71ce8d7 "%s\n") at ../sysdeps/posix/libc_fatal.c:132
#6  0x00007ffff70a8fe5 in malloc_printerr (str=str@entry=0x7ffff71cc672 "free(): invalid pointer") at ./malloc/malloc.c:5772
#7  0x00007ffff70ab37c in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at ./malloc/malloc.c:4507
#8  0x00007ffff70add9e in __GI___libc_free (mem=0x555555fd5958) at ./malloc/malloc.c:3398
#9  0x00007fffecdd84dc in std::__new_allocator<std::_List_node<amd::roc::Memory*> >::deallocate (this=0x555555fd5958, __n=1, __p=0x555555fd5958) at /usr/include/c++/13/bits/new_allocator.h:156
#10 std::allocator_traits<std::allocator<std::_List_node<amd::roc::Memory*> > >::deallocate (__n=1, __p=0x555555fd5958, __a=...) at /usr/include/c++/13/bits/alloc_traits.h:517
#11 std::__cxx11::_List_base<amd::roc::Memory*, std::allocator<amd::roc::Memory*> >::_M_put_node (__p=0x555555fd5958, this=0x555555fd5958) at /usr/include/c++/13/bits/stl_list.h:522
#12 std::__cxx11::list<amd::roc::Memory*, std::allocator<amd::roc::Memory*> >::_M_erase (__position=..., this=0x555555fd5958) at /usr/include/c++/13/bits/stl_list.h:2024
#13 std::__cxx11::list<amd::roc::Memory*, std::allocator<amd::roc::Memory*> >::erase (__position=..., this=0x555555fd5958) at /usr/include/c++/13/bits/list.tcc:158
#14 amd::roc::Device::XferBuffers::acquire (this=0x555555fd5950) at /long_pathname_so_that_rpms_can_package_the_debug_info/src/clr/rocclr/device/rocm/rocdevice.cpp:450
#15 0x00007fffece26830 in amd::roc::DmaBlitManager::writeBuffer (this=this@entry=0x55555e878aa0, srcHost=srcHost@entry=0x7ffce1bce4e0, dstMemory=..., origin=..., size=..., entire=entire@entry=false, copyMetadata=...) at /long_pathname_so_that_rpms_can_package_the_debug_info/src/clr/rocclr/device/rocm/rocblit.cpp:311
#16 0x00007fffece26c9a in amd::roc::KernelBlitManager::writeBuffer (this=this@entry=0x55555e878aa0, srcHost=srcHost@entry=0x7ffce1bce4e0, dstMemory=..., origin=..., size=..., entire=<optimized out>, copyMetadata=...) at /long_pathname_so_that_rpms_can_package_the_debug_info/src/clr/rocclr/device/rocm/rocblit.cpp:1951
#17 0x00007fffecde69b6 in amd::roc::VirtualGPU::submitWriteMemory (this=0x5555599f6fe0, cmd=...) at /long_pathname_so_that_rpms_can_package_the_debug_info/src/clr/rocclr/device/rocm/rocvirtual.cpp:1770
#18 0x00007fffecdacc95 in amd::Command::enqueue (this=0x55555e5806f0) at /long_pathname_so_that_rpms_can_package_the_debug_info/src/clr/rocclr/platform/command.cpp:392
#19 0x00007fffecc171fb in hip::ihipMemcpy (dst=0x7ffa0e8d0000, src=0x7ffce1bce4e0, sizeBytes=4456448, kind=<optimized out>, stream=..., isHostAsync=false, isHostAsync@entry=true, isGPUAsync=true) at /long_pathname_so_that_rpms_can_package_the_debug_info/src/clr/hipamd/src/hip_memory.cpp:637
#20 0x00007fffecc1aa01 in hip::hipMemcpyAsync_common (dst=<optimized out>, dst@entry=0x7ffa0e8d0000, src=<optimized out>, src@entry=0x7ffce1bce4e0, sizeBytes=<optimized out>, sizeBytes@entry=4456448, kind=<optimized out>, kind@entry=hipMemcpyHostToDevice, stream=<optimized out>, stream@entry=0x2) at /long_pathname_so_that_rpms_can_package_the_debug_info/src/clr/hipamd/src/hip_memory.cpp:1567
#21 0x00007fffecc1caf4 in hip::hipMemcpyAsync (dst=0x7ffa0e8d0000, src=<optimized out>, sizeBytes=4456448, kind=hipMemcpyHostToDevice, stream=0x2) at /long_pathname_so_that_rpms_can_package_the_debug_info/src/clr/hipamd/src/hip_memory.cpp:1573
#22 0x00007ffff2c8cf80 in ggml_backend_cuda_buffer_set_tensor (buffer=<optimized out>, tensor=0x55555e2951a0, data=0x7ffce1bce4e0, offset=<optimized out>, size=4456448) at /home/user/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:568
#23 0x00007ffff7822bd6 in ggml_backend_tensor_set (tensor=0x55555e2951a0, data=0x7ffce1bce4e0, offset=0, size=4456448) at /home/user/llama.cpp/ggml/src/ggml-backend.cpp:266
#24 0x00007ffff7d17d52 in llama_model_loader::load_all_data (this=0x7fffffffa510, ctx=0x55555e28ef90, bufs=..., lmlocks=0x0, progress_callback=0x0, progress_callback_user_data=0x0) at /home/user/llama.cpp/src/llama-model-loader.cpp:1020
#25 0x00007ffff7d5b5a1 in llama_model::load_tensors (this=0x555557fa8100, ml=...) at /home/user/llama.cpp/src/llama-model.cpp:3524
#26 0x00007ffff7c64610 in llama_model_load (fname=..., splits=..., model=..., params=...) at /home/user/llama.cpp/src/llama.cpp:73
#27 0x00007ffff7c6d095 in llama_model_load_from_file_impl (path_model=..., splits=..., params=...) at /home/user/llama.cpp/src/llama.cpp:9485
#28 0x00007ffff7c6d345 in llama_model_load_from_file (path_model=0x5555562dc9a0 "/root/.cache/llama.cpp/MaziyarPanahi_Meta-Llama-3-8B-Instruct-GGUF_Meta-Llama-3-8B-Instruct.Q8_0.gguf", params=...) at /home/user/llama.cpp/src/llama.cpp:9512
#29 0x000055555567634a in common_load_model_from_url (model_url=..., local_path=..., hf_token=..., params=...) at /home/user/llama.cpp/common/common.cpp:1479
#30 0x0000555555676490 in common_load_model_from_hf (repo=..., remote_path=..., local_path=..., hf_token=..., params=...) at /home/user/llama.cpp/common/common.cpp:1502
#31 0x0000555555672613 in common_init_from_params (params=...) at /home/user/llama.cpp/common/common.cpp:908
#32 0x00005555555c35f5 in main (argc=8, argv=0x7fffffffe3e8) at /home/user/llama.cpp/examples/main/main.cpp:150

```

For anyone reading. need to install `hip-runtime-amd-dbgsym`

**Comment by IMbackK** [comment]
Here is another attempt at a repoducer for you to try:

```
#include <hip/hip_runtime.h>
#include <iostream>

#define HIP_CHECK(fn) { hipError_t err = fn; if(err != hipSuccess){fprintf(stderr, "Error: %s: %s at %d\n", hipGetErrorName(err), hipGetErrorString(err), __LINE__); exit(1);} }
static constexpr size_t size = 1024*1024*1024;

int main()
{
	float* hostBuffer = new float[size];

	for(size_t i = 0; i < size; ++i)
		hostBuffer[i] = i;

	float* deviceBuffers[8];

	for(size_t i = 0; i < 8; ++i)
	{
		HIP_CHECK(hipSetDevice(i % 2));
		HIP_CHECK(hipMalloc(&(deviceBuffers[i]), size));
		HIP_CHECK(hipMemcpyAsync(deviceBuffers[i], hostBuffer, size, hipMemcpyHostToDevice, hipStreamPerThread));
	}

	HIP_CHECK(hipSetDevice(0));
	HIP_CHECK(hipMemcpy(hostBuffer, deviceBuffers[0], size, hipMemcpyDeviceToHost));
	for(size_t i = 0; i < 16; ++i)
		std::cout<<hostBuffer[i]<<'\n';

	HIP_CHECK(hipSetDevice(1));
	HIP_CHECK(hipMemcpy(hostBuffer, deviceBuffers[1], size, hipMemcpyDeviceToHost));
	for(size_t i = 0; i < 16; ++i)
		std::cout<<hostBuffer[i]<<'\n';

	delete[] hostBuffer;

	for(size_t i = 0; i < 8; ++i)
		HIP_CHECK(hipFree(deviceBuffers[i]));
	
	return 0;
}
```

also since its crashing in the sdma path. Please try with `export HSA_ENABLE_SDMA=0`
