### ISSUE TITLE
Eval bug: [CANN]AutoDL Ascend 910B instance running DeepSeek-r1 32B_Q8 error

### ISSUE THREAD

**Issue by murarduino** [ggml-org/llama.cpp#14291]
### Name and Version

root@autodl-container-3e45438682-122ae01a:~/autodl-tmp/llama.cpp# build/bin/llama-cli --version
version: 5711 (8f71d0f3)
built with cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 for aarch64-linux-gnu

### Operating systems

Linux

### GGML backends

CUDA

### Hardware

CPU:24 vCPU Kunpeng-920
NPU:910B2xKunpeng920(64GB) * 1

btw: I don't understand why GGML backends doesn't have CANN, so I can only choose CUDA.

### Models

unsloth/DeepSeek-R1-Distill-Qwen-32B-Q8_0.gguf download by modelscope

### Problem description & steps to reproduce

During the compilation process, two compilation warnings occur:
[  4%] Built target ggml-base
[  4%] Building CXX object ggml/src/ggml-cann/CMakeFiles/ggml-cann.dir/acl_tensor.cpp.o
[  5%] Building CXX object ggml/src/ggml-cann/CMakeFiles/ggml-cann.dir/aclnn_ops.cpp.o
[  5%] Building CXX object ggml/src/ggml-cann/CMakeFiles/ggml-cann.dir/ggml-cann.cpp.o
/root/autodl-tmp/llama.cpp/ggml/src/ggml-cann/ggml-cann.cpp: In function ‘bool ggml_backend_cann_supports_op(ggml_backend_dev_t, const ggml_tensor*)’:
/root/autodl-tmp/llama.cpp/ggml/src/ggml-cann/ggml-cann.cpp:2234:36: warning: cast from type ‘const int32_t*’ {aka ‘const int*’} to type ‘float*’ casts away qualifiers [-Wcast-qual]
 2234 |             memcpy(&logitSoftcap,  (float*)op->op_params + 2, sizeof(float));
      |                                    ^~~~~~~~~~~~~~~~~~~~~
[  6%] Linking CXX shared library ../../../bin/libggml-cann.so
.......
[ 89%] Building CXX object tools/perplexity/CMakeFiles/llama-perplexity.dir/perplexity.cpp.o
/root/autodl-tmp/llama.cpp/tools/perplexity/perplexity.cpp: In lambda function:
/root/autodl-tmp/llama.cpp/tools/perplexity/perplexity.cpp:1753:41: note: parameter passing for argument of type ‘std::pair<double, double>’ when C++17 is enabled changed to match C++14 in GCC 10.1
 1753 |             return std::make_pair(0., 0.);
      |                                         ^
[ 89%] Linking CXX executable ../../bin/llama-perplexity

Despite these two caveats, the compilation process is complete.

starting llama-server:
llama.cpp/build/bin/llama-server -m model/DeepSeek-R1-Distill-Qwen-32B-Q8_0.gguf --host 0.0.0.0 --port 8008 --temp 0.8 --cache-type-k q8_0 -t 24 -tb 48 --ctx-size 4096 -ngl 99 --chat-template-file llama.cpp/models/templates/llama-cpp-deepseek-r1.jinja

Shows that all transformers layers have been offload into the GPU. However, an error was reported when the ggml-backend.cpp was called later
‘pre-allocated tensor (cache_k_l0 (view) (copy of Kcur-0)) in a buffer (CANN0) that cannot run the operation (CPY)
’

Then the system terminates the llama-server command.The specific operation record is put into the Relevant log output

### Relevant log output

```shell
root@autodl-container-3e45438682-122ae01a:~/autodl-tmp# llama.cpp/build/bin/llama-server -m model/DeepSeek-R1-Distill-Qwen-32B-Q8_0.gguf --host 0.0.0.0 --port 8008 --temp 0.8 --cache-type-k q8_0 -t 24 -tb 48 --ctx-size 4096 -ngl 99 --chat-template-file llama.cpp/models/templates/llama-cpp-deepseek-r1.jinja
build: 5711 (8f71d0f3) with cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 for aarch64-linux-gnu
system info: n_threads = 24, n_threads_batch = 48, total_threads = 192

system_info: n_threads = 24 (n_threads_batch = 48) / 192 | CPU : NEON = 1 | ARM_FMA = 1 | FP16_VA = 1 | DOTPROD = 1 | LLAMAFILE = 1 | OPENMP = 1 | REPACK = 1 | 

main: binding port with default address family
main: HTTP server is listening, hostname: 0.0.0.0, port: 8008, http threads: 191
main: loading model
srv    load_model: loading model 'model/DeepSeek-R1-Distill-Qwen-32B-Q8_0.gguf'
llama_model_load_from_file_impl: using device CANN0 (Ascend910B2) - 62146 MiB free
llama_model_loader: loaded meta data with 27 key-value pairs and 771 tensors from model/DeepSeek-R1-Distill-Qwen-32B-Q8_0.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = qwen2
llama_model_loader: - kv   1:                               general.type str              = model
llama_model_loader: - kv   2:                               general.name str              = DeepSeek R1 Distill Qwen 32B
llama_model_loader: - kv   3:                       general.organization str              = Deepseek Ai
llama_model_loader: - kv   4:                           general.basename str              = DeepSeek-R1-Distill-Qwen
llama_model_loader: - kv   5:                         general.size_label str              = 32B
llama_model_loader: - kv   6:                          qwen2.block_count u32              = 64
llama_model_loader: - kv   7:                       qwen2.context_length u32              = 131072
llama_model_loader: - kv   8:                     qwen2.embedding_length u32              = 5120
llama_model_loader: - kv   9:                  qwen2.feed_forward_length u32              = 27648
llama_model_loader: - kv  10:                 qwen2.attention.head_count u32              = 40
llama_model_loader: - kv  11:              qwen2.attention.head_count_kv u32              = 8
llama_model_loader: - kv  12:                       qwen2.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv  13:     qwen2.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  14:                          general.file_type u32              = 7
llama_model_loader: - kv  15:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  16:                         tokenizer.ggml.pre str              = deepseek-r1-qwen
llama_model_loader: - kv  17:                      tokenizer.ggml.tokens arr[str,152064]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  18:                  tokenizer.ggml.token_type arr[i32,152064]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  19:                      tokenizer.ggml.merges arr[str,151387]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
llama_model_loader: - kv  20:                tokenizer.ggml.bos_token_id u32              = 151646
llama_model_loader: - kv  21:                tokenizer.ggml.eos_token_id u32              = 151643
llama_model_loader: - kv  22:            tokenizer.ggml.padding_token_id u32              = 151654
llama_model_loader: - kv  23:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  24:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  25:                    tokenizer.chat_template str              = {% if not add_generation_prompt is de...
llama_model_loader: - kv  26:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:  321 tensors
llama_model_loader: - type q8_0:  450 tensors
print_info: file format = GGUF V3 (latest)
print_info: file type   = Q8_0
print_info: file size   = 32.42 GiB (8.50 BPW) 
load: special_eos_id is not in special_eog_ids - the tokenizer config may be incorrect
load: special tokens cache size = 22
load: token to piece cache size = 0.9310 MB
print_info: arch             = qwen2
print_info: vocab_only       = 0
print_info: n_ctx_train      = 131072
print_info: n_embd           = 5120
print_info: n_layer          = 64
print_info: n_head           = 40
print_info: n_head_kv        = 8
print_info: n_rot            = 128
print_info: n_swa            = 0
print_info: is_swa_any       = 0
print_info: n_embd_head_k    = 128
print_info: n_embd_head_v    = 128
print_info: n_gqa            = 5
print_info: n_embd_k_gqa     = 1024
print_info: n_embd_v_gqa     = 1024
print_info: f_norm_eps       = 0.0e+00
print_info: f_norm_rms_eps   = 1.0e-05
print_info: f_clamp_kqv      = 0.0e+00
print_info: f_max_alibi_bias = 0.0e+00
print_info: f_logit_scale    = 0.0e+00
print_info: f_attn_scale     = 0.0e+00
print_info: n_ff             = 27648
print_info: n_expert         = 0
print_info: n_expert_used    = 0
print_info: causal attn      = 1
print_info: pooling type     = -1
print_info: rope type        = 2
print_info: rope scaling     = linear
print_info: freq_base_train  = 1000000.0
print_info: freq_scale_train = 1
print_info: n_ctx_orig_yarn  = 131072
print_info: rope_finetuned   = unknown
print_info: ssm_d_conv       = 0
print_info: ssm_d_inner      = 0
print_info: ssm_d_state      = 0
print_info: ssm_dt_rank      = 0
print_info: ssm_dt_b_c_rms   = 0
print_info: model type       = 32B
print_info: model params     = 32.76 B
print_info: general.name     = DeepSeek R1 Distill Qwen 32B
print_info: vocab type       = BPE
print_info: n_vocab          = 152064
print_info: n_merges         = 151387
print_info: BOS token        = 151646 '<｜begin▁of▁sentence｜>'
print_info: EOS token        = 151643 '<｜end▁of▁sentence｜>'
print_info: EOT token        = 151643 '<｜end▁of▁sentence｜>'
print_info: PAD token        = 151654 '<|vision_pad|>'
print_info: LF token         = 198 'Ċ'
print_info: FIM PRE token    = 151659 '<|fim_prefix|>'
print_info: FIM SUF token    = 151661 '<|fim_suffix|>'
print_info: FIM MID token    = 151660 '<|fim_middle|>'
print_info: FIM PAD token    = 151662 '<|fim_pad|>'
print_info: FIM REP token    = 151663 '<|repo_name|>'
print_info: FIM SEP token    = 151664 '<|file_sep|>'
print_info: EOG token        = 151643 '<｜end▁of▁sentence｜>'
print_info: EOG token        = 151662 '<|fim_pad|>'
print_info: EOG token        = 151663 '<|repo_name|>'
print_info: EOG token        = 151664 '<|file_sep|>'
print_info: max token length = 256
load_tensors: loading model tensors, this can take a while... (mmap = true)
load_tensors: offloading 64 repeating layers to GPU
load_tensors: offloading output layer to GPU
load_tensors: offloaded 65/65 layers to GPU
load_tensors:        CANN0 model buffer size = 32413.18 MiB
load_tensors:   CPU_Mapped model buffer size =   788.91 MiB
.................................................................................................
llama_context: constructing llama_context
llama_context: n_seq_max     = 1
llama_context: n_ctx         = 4096
llama_context: n_ctx_per_seq = 4096
llama_context: n_batch       = 2048
llama_context: n_ubatch      = 512
llama_context: causal_attn   = 1
llama_context: flash_attn    = 0
llama_context: freq_base     = 1000000.0
llama_context: freq_scale    = 1
llama_context: n_ctx_per_seq (4096) < n_ctx_train (131072) -- the full capacity of the model will not be utilized
ggml_backend_cann_context: device 0 async operator submission is OFF
llama_context:  CANN_Host  output buffer size =     0.58 MiB
llama_kv_cache_unified:      CANN0 KV buffer size =   784.00 MiB
llama_kv_cache_unified: size =  784.00 MiB (  4096 cells,  64 layers,  1 seqs), K (q8_0):  272.00 MiB, V (f16):  512.00 MiB
/root/autodl-tmp/llama.cpp/ggml/src/ggml-backend.cpp:750: pre-allocated tensor (cache_k_l0 (view) (copy of Kcur-0)) in a buffer (CANN0) that cannot run the operation (CPY)
/root/autodl-tmp/llama.cpp/build/bin/libggml-base.so(+0x13064)[0xffffa3dc3064]
/root/autodl-tmp/llama.cpp/build/bin/libggml-base.so(ggml_print_backtrace+0x21c)[0xffffa3dc346c]
/root/autodl-tmp/llama.cpp/build/bin/libggml-base.so(ggml_abort+0xe4)[0xffffa3dc35c8]
/root/autodl-tmp/llama.cpp/build/bin/libggml-base.so(+0x25058)[0xffffa3dd5058]
/root/autodl-tmp/llama.cpp/build/bin/libggml-base.so(+0x26720)[0xffffa3dd6720]
/root/autodl-tmp/llama.cpp/build/bin/libggml-base.so(ggml_backend_sched_reserve+0x7c)[0xffffa3dd7dbc]
/root/autodl-tmp/llama.cpp/build/bin/libllama.so(_ZN13llama_context13graph_reserveEjjjPK20llama_memory_state_i+0x148)[0xffffa3f198dc]
/root/autodl-tmp/llama.cpp/build/bin/libllama.so(_ZN13llama_contextC2ERK11llama_model20llama_context_params+0x9a0)[0xffffa3f1fe10]
/root/autodl-tmp/llama.cpp/build/bin/libllama.so(llama_init_from_model+0xc4)[0xffffa3f208c4]
llama.cpp/build/bin/llama-server(+0x17cfc8)[0xaaaad02ecfc8]
llama.cpp/build/bin/llama-server(+0x80f28)[0xaaaad01f0f28]
llama.cpp/build/bin/llama-server(+0x26fb0)[0xaaaad0196fb0]
/lib/aarch64-linux-gnu/libc.so.6(+0x273fc)[0xffffa39273fc]
/lib/aarch64-linux-gnu/libc.so.6(__libc_start_main+0x98)[0xffffa39274cc]
llama.cpp/build/bin/llama-server(+0x293f0)[0xaaaad01993f0]
Aborted (core dumped)
```

**Comment by murarduino** [comment]
Remove the--cache-type-k option, it can run normally, the problem is solved
I think it may be because ascend NPU is sensitive to KVCache quantization accuracy
