### ISSUE TITLE
Eval bug: Illegal memory access and extreme perplexity on GPT-OSS-20B

### ISSUE THREAD

**Issue by pt13762104** [ggml-org/llama.cpp#15390]
### Name and Version

build: 6183 (65349f26) with cc (GCC) 15.2.1 20250808 (Red Hat 15.2.1-1) for x86_64-redhat-linux

### Operating systems

Linux

### GGML backends

CUDA

### Hardware

GTX 1660 Ti + i7-10750H

### Models

https://huggingface.co/unsloth/gpt-oss-20b-GGUF/blob/main/gpt-oss-20b-Q8_0.gguf

### Problem description & steps to reproduce

I tried to measure perplexity of gpt-oss using this command: `~/l2/build/bin/llama-perplexity -m /run/media/yoshi_likes_e4/DATA/gpt-oss-20b-Q8_0.gguf -ot ".*(up|down).exps.weight=CPU" -fa -f wiki.test.raw -ngl 99 --swa-full`, but it crashed with an illegal memory access. Also the perplexity seems wrong (500+), this also happens on Vulkan.

### Relevant log output

```shell
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    yes
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce GTX 1660 Ti, compute capability 7.5, VMM: yes
build: 6183 (65349f26) with cc (GCC) 15.2.1 20250808 (Red Hat 15.2.1-1) for x86_64-redhat-linux
llama_model_load_from_file_impl: using device CUDA0 (NVIDIA GeForce GTX 1660 Ti) - 5642 MiB free
llama_model_loader: loaded meta data with 37 key-value pairs and 459 tensors from /run/media/yoshi_likes_e4/DATA/gpt-oss-20b-Q8_0.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = gpt-oss
llama_model_loader: - kv   1:                               general.type str              = model
llama_model_loader: - kv   2:                               general.name str              = Gpt-Oss-20B
llama_model_loader: - kv   3:                           general.basename str              = Gpt-Oss-20B
llama_model_loader: - kv   4:                       general.quantized_by str              = Unsloth
llama_model_loader: - kv   5:                         general.size_label str              = 20B
llama_model_loader: - kv   6:                            general.license str              = apache-2.0
llama_model_loader: - kv   7:                           general.repo_url str              = https://huggingface.co/unsloth
llama_model_loader: - kv   8:                               general.tags arr[str,2]       = ["vllm", "text-generation"]
llama_model_loader: - kv   9:                        gpt-oss.block_count u32              = 24
llama_model_loader: - kv  10:                     gpt-oss.context_length u32              = 131072
llama_model_loader: - kv  11:                   gpt-oss.embedding_length u32              = 2880
llama_model_loader: - kv  12:                gpt-oss.feed_forward_length u32              = 2880
llama_model_loader: - kv  13:               gpt-oss.attention.head_count u32              = 64
llama_model_loader: - kv  14:            gpt-oss.attention.head_count_kv u32              = 8
llama_model_loader: - kv  15:                     gpt-oss.rope.freq_base f32              = 150000.000000
llama_model_loader: - kv  16:   gpt-oss.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  17:                       gpt-oss.expert_count u32              = 32
llama_model_loader: - kv  18:                  gpt-oss.expert_used_count u32              = 4
llama_model_loader: - kv  19:               gpt-oss.attention.key_length u32              = 64
llama_model_loader: - kv  20:             gpt-oss.attention.value_length u32              = 64
llama_model_loader: - kv  21:           gpt-oss.attention.sliding_window u32              = 128
llama_model_loader: - kv  22:         gpt-oss.expert_feed_forward_length u32              = 2880
llama_model_loader: - kv  23:                  gpt-oss.rope.scaling.type str              = yarn
llama_model_loader: - kv  24:                gpt-oss.rope.scaling.factor f32              = 32.000000
llama_model_loader: - kv  25: gpt-oss.rope.scaling.original_context_length u32              = 4096
llama_model_loader: - kv  26:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  27:                         tokenizer.ggml.pre str              = gpt-4o
llama_model_loader: - kv  28:                      tokenizer.ggml.tokens arr[str,201088]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  29:                  tokenizer.ggml.token_type arr[i32,201088]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  30:                      tokenizer.ggml.merges arr[str,446189]  = ["Ġ Ġ", "Ġ ĠĠĠ", "ĠĠ ĠĠ", "...
llama_model_loader: - kv  31:                tokenizer.ggml.bos_token_id u32              = 199998
llama_model_loader: - kv  32:                tokenizer.ggml.eos_token_id u32              = 200002
llama_model_loader: - kv  33:            tokenizer.ggml.padding_token_id u32              = 200017
llama_model_loader: - kv  34:                    tokenizer.chat_template str              = {# Chat template fixes by Unsloth #}\n...
llama_model_loader: - kv  35:               general.quantization_version u32              = 2
llama_model_loader: - kv  36:                          general.file_type u32              = 7
llama_model_loader: - type  f32:  289 tensors
llama_model_loader: - type q8_0:   98 tensors
llama_model_loader: - type mxfp4:   72 tensors
print_info: file format = GGUF V3 (latest)
print_info: file type   = Q8_0
print_info: file size   = 11.27 GiB (4.63 BPW) 
load: printing all EOG tokens:
load:   - 199999 ('<|endoftext|>')
load:   - 200002 ('<|return|>')
load:   - 200007 ('<|end|>')
load:   - 200012 ('<|call|>')
load: special_eog_ids contains both '<|return|>' and '<|call|>' tokens, removing '<|end|>' token from EOG list
load: special tokens cache size = 21
load: token to piece cache size = 1.3332 MB
print_info: arch             = gpt-oss
print_info: vocab_only       = 0
print_info: n_ctx_train      = 131072
print_info: n_embd           = 2880
print_info: n_layer          = 24
print_info: n_head           = 64
print_info: n_head_kv        = 8
print_info: n_rot            = 64
print_info: n_swa            = 128
print_info: is_swa_any       = 1
print_info: n_embd_head_k    = 64
print_info: n_embd_head_v    = 64
print_info: n_gqa            = 8
print_info: n_embd_k_gqa     = 512
print_info: n_embd_v_gqa     = 512
print_info: f_norm_eps       = 0.0e+00
print_info: f_norm_rms_eps   = 1.0e-05
print_info: f_clamp_kqv      = 0.0e+00
print_info: f_max_alibi_bias = 0.0e+00
print_info: f_logit_scale    = 0.0e+00
print_info: f_attn_scale     = 0.0e+00
print_info: n_ff             = 2880
print_info: n_expert         = 32
print_info: n_expert_used    = 4
print_info: causal attn      = 1
print_info: pooling type     = 0
print_info: rope type        = 2
print_info: rope scaling     = yarn
print_info: freq_base_train  = 150000.0
print_info: freq_scale_train = 0.03125
print_info: n_ctx_orig_yarn  = 4096
print_info: rope_finetuned   = unknown
print_info: model type       = ?B
print_info: model params     = 20.91 B
print_info: general.name     = Gpt-Oss-20B
print_info: n_ff_exp         = 2880
print_info: vocab type       = BPE
print_info: n_vocab          = 201088
print_info: n_merges         = 446189
print_info: BOS token        = 199998 '<|startoftext|>'
print_info: EOS token        = 200002 '<|return|>'
print_info: EOT token        = 199999 '<|endoftext|>'
print_info: PAD token        = 200017 '<|reserved_200017|>'
print_info: LF token         = 198 'Ċ'
print_info: EOG token        = 199999 '<|endoftext|>'
print_info: EOG token        = 200002 '<|return|>'
print_info: EOG token        = 200012 '<|call|>'
print_info: max token length = 256
load_tensors: loading model tensors, this can take a while... (mmap = true)
load_tensors: offloading 24 repeating layers to GPU
load_tensors: offloading output layer to GPU
load_tensors: offloaded 25/25 layers to GPU
load_tensors:        CUDA0 model buffer size =  4494.69 MiB
load_tensors:   CPU_Mapped model buffer size = 10949.33 MiB
...............................................................................
llama_context: constructing llama_context
llama_context: n_seq_max     = 4
llama_context: n_ctx         = 2048
llama_context: n_ctx_per_seq = 512
llama_context: n_batch       = 2048
llama_context: n_ubatch      = 512
llama_context: causal_attn   = 1
llama_context: flash_attn    = 1
llama_context: kv_unified    = false
llama_context: freq_base     = 150000.0
llama_context: freq_scale    = 0.03125
llama_context: n_ctx_per_seq (512) < n_ctx_train (131072) -- the full capacity of the model will not be utilized
llama_context:  CUDA_Host  output buffer size =     3.07 MiB
llama_kv_cache_unified_iswa: using full-size SWA cache (ref: https://github.com/ggml-org/llama.cpp/pull/13194#issuecomment-2868343055)
llama_kv_cache_unified_iswa: creating non-SWA KV cache, size = 512 cells
llama_kv_cache_unified:      CUDA0 KV buffer size =    48.00 MiB
llama_kv_cache_unified: size =   48.00 MiB (   512 cells,  12 layers,  4/4 seqs), K (f16):   24.00 MiB, V (f16):   24.00 MiB
llama_kv_cache_unified_iswa: creating     SWA KV cache, size = 512 cells
llama_kv_cache_unified:      CUDA0 KV buffer size =    48.00 MiB
llama_kv_cache_unified: size =   48.00 MiB (   512 cells,  12 layers,  4/4 seqs), K (f16):   24.00 MiB, V (f16):   24.00 MiB
llama_context:      CUDA0 compute buffer size =   398.38 MiB
llama_context:  CUDA_Host compute buffer size =     7.65 MiB
llama_context: graph nodes  = 1352
llama_context: graph splits = 50 (with bs=512), 98 (with bs=1)
common_init_from_params: added <|endoftext|> logit bias = -inf
common_init_from_params: added <|return|> logit bias = -inf
common_init_from_params: added <|call|> logit bias = -inf
common_init_from_params: setting dry_penalty_last_n to ctx_size = 2048
common_init_from_params: warming up the model with an empty run - please wait ... (--no-warmup to disable)

system_info: n_threads = 6 (n_threads_batch = 6) / 12 | CUDA : ARCHS = 610 | FORCE_MMQ = 1 | USE_GRAPHS = 1 | PEER_MAX_BATCH_SIZE = 128 | CPU : SSE3 = 1 | SSSE3 = 1 | AVX = 1 | AVX2 = 1 | F16C = 1 | FMA = 1 | BMI2 = 1 | LLAMAFILE = 1 | OPENMP = 1 | REPACK = 1 | 
perplexity: tokenizing the input ..
perplexity: tokenization took 1196.83 ms
perplexity: calculating perplexity over 560 chunks, n_ctx=512, batch_size=2048, n_seq=4
perplexity: 6.37 seconds per pass - ETA 14.87 minutes
[1]201.4275,[2]233.9770,[3]535.8361,[4]445.0433,[5]356.0965,[6]377.0466,[7]382.8672,[8]442.2841,[9]435.1295,[10]454.7228,[11]426.8687,[12]380.0832,[13]398.8903,[14]404.4476,[15]382.6302,[16]368.7136,[17]385.1854,[18]386.3125,[19]400.9673,[20]387.5534,[21]366.9188,[22]351.9600,[23]321.5445,[24]309.8093,[25]287.1762,[26]282.1817,[27]271.4813,[28]261.0657,[29]253.9762,[30]237.4417,[31]230.8849,[32]228.4118,[33]217.6375,[34]207.0425,[35]208.2165,[36]207.1379,[37]209.9399,[38]207.7408,[39]207.9156,[40]207.5824,[41]212.9646,[42]212.3341,[43]212.5071,[44]206.5990,[45]207.6088,[46]206.0619,[47]218.4572,[48]215.4472,[49]218.3896,[50]220.2490,[51]217.2802,[52]212.4003,[53]213.3204,[54]212.2340,[55]210.4339,[56]208.6665,[57]204.5456,[58]204.0907,[59]200.2716,[60]198.8764,[61]200.9045,[62]204.1366,[63]204.8727,[64]204.8797,[65]203.0441,[66]204.1785,[67]202.5812,[68]202.2917,[69]203.1618,[70]203.1101,[71]205.9327,[72]205.1144,[73]206.0215,[74]208.2685,[75]208.4956,[76]214.2304,[77]213.4387,[78]213.6643,[79]213.6657,[80]213.2381,/home/yoshi_likes_e4/l2/ggml/src/ggml-cuda/ggml-cuda.cu:85: CUDA error
CUDA error: an illegal memory access was encountered
  current device: 0, in function ggml_backend_cuda_synchronize at /home/yoshi_likes_e4/l2/ggml/src/ggml-cuda/ggml-cuda.cu:2592
  cudaStreamSynchronize(cuda_ctx->stream())
```

**Comment by JohannesGaessler** [comment]
I am unable to reproduce the illegal memory access using an RTX 4090 and the ggml-org mxfp4 variant of gpt-oss 20b. Did you compile with the flags `-DCMAKE_CUDA_ARCHITECTURES=61 -DGGML_CUDA_FORCE_MMQ=ON`? (I also tested those.)

**Comment by pt13762104** [comment]
Yes, I did. I will try the ggml-org variant soon... Could you provide the download link?

**Comment by JohannesGaessler** [comment]
I was using this model: https://huggingface.co/ggml-org/gpt-oss-20b-GGUF

**Comment by pt13762104** [comment]
So, I tested it. I also didn't got the illegal memory access, but here's the test results:
```
perplexity: 8.64 seconds per pass - ETA 20.15 minutes
[1]197.4209,[2]231.3839,[3]529.1866,[4]435.4140,[5]348.9435,[6]371.7908,[7]381.8022,[8]438.1654,[9]432.3680,[10]457.5803,[11]429.6307,[12]384.3503,[13]401.6958,[14]406.8646,[15]384.6544,[16]370.1565,[17]389.2777,[18]389.7444,[19]405.1628,[20]389.4985,[21]369.2914,[22]354.6417,[23]322.9062,[24]310.2449,[25]287.3021,[26]282.4043,[27]271.6106,[28]261.4133,[29]254.0466,[30]237.1560,[31]230.7824,[32]228.3596,[33]217.8131,[34]207.3114,[35]208.5586,[36]207.5924,[37]210.3549,[38]208.1864,[39]208.3410,[40]207.8669,[41]213.1948,[42]211.9397,[43]212.2803,[44]206.3161,[45]207.4519,[46]206.0051,[47]218.6414,[48]215.6777,[49]218.6424,[50]220.5442,[51]217.5890,[52]212.7924,[53]213.8178,[54]212.6659,[55]210.4421,[56]208.7145,[57]204.6334,[58]204.1545,[59]200.4212,[60]198.9037,[61]200.8830,[62]204.0619,[63]204.6652,[64]204.5388,[65]202.7309,[66]204.0356,[67]202.3334,[68]202.1327,[69]202.9200,[70]202.9075,[71]205.3454,[72]204.6717,[73]205.5908,[74]207.9518,[75]208.3944,[76]214.0413,[77]213.2363,[78]213.5633,[79]213.5025,[80]213.0663,[81]212.2082,[82]212.5074,[83]213.6888,[84]214.3768,[85]212.3687,[86]212.6813,[87]213.3503,[88]213.8906,[89]213.6952,[90]212.3638,[91]214.0907,[92]212.3620,[93]211.3541,[94]211.5763,[95]211.3375,[96]212.7371,[97]211.0478,[98]210.4721,[99]207.8963,[100]208.9644,[101]210.7778,[102]211.4419,[103]213.1603,[104]215.0423,[105]218.0680,[106]221.7521,[107]223.7899,[108]225.4567,[109]227.7318,[110]229.0252,[111]228.9610,[112]227.4899,[113]223.8823,[114]220.9270,[115]220.2155,[116]218.2144,[117]215.5801,[118]212.8741,[119]211.0182,[120]209.8739,[121]208.0912,[122]206.0608,[123]205.0993,[124]203.4171,[125]201.5602,[126]199.6373,[127]197.6655,[128]196.4110,[129]195.2959,[130]194.2913,[131]192.1202,[132]191.2846,[133]191.6582,[134]192.2433,[135]194.5097,[136]194.1381,[137]192.8026,[138]193.5394,[139]193.4149,[140]193.6317,[141]196.3921,[142]195.8852,[143]195.8244,[144]196.0393,[145]198.3796,[146]199.3166,[147]199.8366,[148]200.2012,[149]200.5137,[150]198.6960,[151]197.6795,[152]196.9066,[153]196.6705,[154]196.6656,[155]196.4557,[156]196.6083,[157]195.8794,[158]195.9272,[159]198.3128,[160]199.7860,[161]201.8527,[162]202.1188,[163]202.6007,[164]203.2130,[165]203.8638,[166]204.5271,[167]206.0197,[168]206.9802,[169]207.4810,[170]208.4846,[171]209.4576,[172]211.3563,[173]212.1301,[174]212.4783,[175]213.0400,[176]213.9382,[177]213.5201,[178]213.5550,[179]214.1660,[180]214.4332,[181]214.7450,[182]214.8988,[183]214.8364,[184]214.2904,[185]213.6179,[186]213.1249,[187]213.3736,[188]213.8030,[189]213.9195,[190]214.3924,[191]213.9776,[192]213.5273,[193]216.3341,[194]217.4980,[195]218.0059,[196]218.3946,[197]218.3840,[198]216.8142,[199]216.0653,[200]214.9902,[201]215.0264,[202]215.8434,[203]214.7810,[204]213.6059,[205]212.5578,[206]211.0182,[207]210.3619,[208]210.4525,[209]209.7635,[210]208.8524,[211]208.2764,[212]207.6996,[213]207.2547,[214]206.6754,[215]206.3994,[216]206.1870,[217]205.8849,[218]204.8435,[219]204.4111,[220]204.6031,[221]204.0141,[222]203.4962,[223]203.5813,[224]202.7393,[225]201.9465,[226]201.7286,[227]202.6723,[228]202.3469,[229]201.4818,[230]200.3085,[231]199.2661,[232]199.3286,[233]199.7447,[234]200.7243,[235]200.4686,[236]200.6514,[237]201.6940,[238]202.0042,[239]202.4558,[240]202.5559,[241]202.7509,[242]202.8647,[243]203.3261,[244]203.8659,[245]203.7598,[246]204.3355,[247]205.2178,[248]206.3817,[249]206.2128,[250]206.9251,[251]207.1447,[252]207.1747,[253]206.9135,[254]207.2588,[255]207.8475,[256]208.5531,[257]208.6845,[258]209.0832,[259]209.1219,[260]208.7722,[261]209.7966,[262]210.2953,[263]210.4897,[264]210.9241,[265]210.9652,[266]210.9296,[267]210.5622,[268]210.9464,[269]211.7022,[270]212.4632,[271]213.7699,[272]213.4574,[273]214.8469,[274]214.4290,[275]213.0925,[276]212.8110,[277]216.6252,[278]217.0101,[279]217.4988,[280]218.4730,[281]218.5744,[282]219.1868,[283]218.9981,[284]218.7834,[285]219.2939,[286]219.0403,[287]219.5970,[288]219.3924,[289]218.2565,[290]218.5752,[291]217.9272,[292]217.1507,[293]217.0960,[294]216.6548,[295]216.2258,[296]215.5612,[297]215.4093,[298]215.1302,[299]214.9035,[300]213.7001,[301]212.7872,[302]212.2003,[303]211.5665,[304]212.6287,[305]213.3529,[306]214.1690,[307]214.6792,[308]215.9909,[309]216.4067,[310]215.7857,[311]215.7930,[312]215.0869,[313]214.8872,[314]214.5595,[315]213.8025,[316]213.4497,[317]213.1499,[318]212.8167,[319]212.7033,[320]212.6808,[321]212.5629,[322]211.9406,[323]211.8194,[324]212.0168,[325]211.9736,[326]211.7271,[327]211.8249,[328]212.4201,[329]213.0216,[330]213.2676,[331]213.9947,[332]214.2721,[333]214.3475,[334]214.5251,[335]214.5973,[336]214.8449,[337]215.0482,[338]215.4424,[339]215.7169,[340]215.4616,[341]216.1985,[342]216.3625,[343]216.7265,[344]217.6759,[345]217.7448,[346]218.2063,[347]218.2043,[348]219.6058,[349]220.1305,[350]221.1236,[351]221.9091,[352]222.6731,[353]223.3624,[354]224.0114,[355]224.6986,[356]224.9298,[357]225.3022,[358]226.1075,[359]226.6348,[360]226.9265,[361]227.3155,[362]227.2362,[363]227.8463,[364]228.4361,[365]228.8172,[366]228.8926,[367]229.0837,[368]229.5213,[369]229.7722,[370]230.0682,[371]230.1014,[372]229.9309,[373]229.8029,[374]229.8568,[375]230.6829,[376]230.3015,[377]230.2059,[378]230.5260,[379]231.6566,[380]232.0542,[381]232.1008,[382]232.0738,[383]232.2624,[384]232.0728,[385]232.6186,[386]232.9435,[387]232.7075,[388]233.6988,[389]234.1551,[390]234.4819,[391]235.8580,[392]236.0326,[393]236.3541,[394]236.4462,[395]236.9170,[396]236.8281,[397]237.0769,[398]238.2182,[399]238.5171,[400]238.5389,[401]239.2463,[402]240.1291,[403]240.1795,[404]240.4557,[405]240.6494,[406]240.4040,[407]241.1900,[408]241.3893,[409]241.4611,[410]242.3233,[411]242.1382,[412]241.4335,[413]241.3098,[414]241.3104,[415]241.4437,[416]241.3972,[417]242.0712,[418]242.7048,[419]242.8860,[420]243.3417,[421]243.6153,[422]243.8344,[423]243.7181,[424]243.4941,[425]243.5184,[426]243.8843,[427]244.0868,[428]244.1331,[429]243.5843,[430]243.5187,[431]243.1641,[432]243.5171,[433]243.1689,[434]243.7991,[435]243.6467,[436]242.8991,[437]242.4578,[438]242.2552,[439]242.4593,[440]243.1260,[441]243.0239,[442]243.8248,[443]243.4414,[444]243.1539,[445]243.6720,[446]243.7108,[447]243.9197,[448]244.0429,[449]243.9498,[450]243.7105,[451]243.6495,[452]243.7704,[453]243.8587,[454]243.9227,[455]243.4016,[456]243.3442,[457]243.6919,[458]243.0362,[459]242.9395,[460]242.7432,[461]244.1183,[462]244.2919,[463]244.5036,[464]244.8343,[465]245.0152,[466]245.2505,[467]245.0237,[468]244.4860,[469]244.1041,[470]243.9719,[471]242.8926,[472]243.1733,[473]242.5936,[474]241.6607,[475]241.6331,[476]241.7065,[477]240.6646,[478]240.9653,[479]241.0645,[480]241.5826,[481]241.8034,[482]240.7176,[483]241.9510,[484]242.1597,[485]242.2591,[486]243.2632,[487]243.0955,[488]243.1433,[489]243.7257,[490]243.9501,[491]243.7731,[492]243.7045,[493]243.7281,[494]243.4544,[495]243.3638,[496]243.0877,[497]242.9496,[498]242.3442,[499]243.0492,[500]243.2244,[501]243.4703,[502]242.7804,[503]243.1130,[504]243.0907,[505]243.5841,[506]243.8369,[507]243.6631,[508]244.1204,[509]243.9659,[510]243.4444,[511]243.1714,[512]243.1989,[513]242.8966,[514]242.7306,[515]242.4313,[516]242.1618,[517]242.4434,[518]242.2324,[519]242.5114,[520]242.6562,[521]242.3588,[522]242.0291,[523]242.6622,[524]242.5645,[525]242.0583,[526]240.6575,[527]240.3771,[528]240.1288,[529]239.6028,[530]239.2047,[531]238.7132,[532]239.2005,[533]239.3119,[534]239.4026,[535]239.2429,[536]239.0022,[537]238.8191,[538]238.9295,[539]238.6505,[540]238.7244,[541]238.9620,[542]239.5017,[543]239.7116,[544]239.8148,[545]239.8544,[546]240.4714,[547]240.6715,[548]240.7953,[549]241.3622,[550]241.7289,[551]241.8485,[552]241.8582,[553]241.9530,[554]242.9605,[555]243.2711,[556]243.7679,[557]243.8878,[558]244.3778,[559]244.7384,[560]244.9008,
Final estimate: PPL = 244.9008 +/- 2.08964
```
(And I think I found the reason for the illegal memory access. it was due to overclocking)

**Comment by JohannesGaessler** [comment]
The high perplexity values are a known issue. I'm not sure that it is actually indicative of something being wrong since it's an instruct model.
