### ISSUE TITLE
Misc. bug: GGML_CUDA_ENABLE_UNIFIED_MEMORY Does not work

### ISSUE THREAD

**Issue by XZVB12** [ggml-org/llama.cpp#16197]
### Name and Version

```
./llama-server --version
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
Device 0: NVIDIA GeForce RTX 3060, compute capability 8.6, VMM: yes
version: 6557 (f6b4af3d0)
built with cc (GCC) 15.2.1 20250813 for x86_64-pc-linux-gnu

CUDA: 13.0.1
NVIDIA driver: 580.82.09
```

### Operating systems

Linux

### Which llama.cpp modules do you know to be affected?

llama-server

### Command line

```shell
GGML_CUDA_ENABLE_UNIFIED_MEMORY=1 ./llama-server -t 6 -c 32768 -m model-name-Q5_K_M.gguf
```

### Problem description & steps to reproduce

Hello, Today I decided to try `GGML_CUDA_ENABLE_UNIFIED_MEMORY` instead of `-ngl` and announced that it doesn’t work.
This problem has already been described [here](https://github.com/ggml-org/llama.cpp/issues/10091), discussion was automatically closed, but the problem still exists. Here is a brief description of the problem from the previous discussion.

`GGML_CUDA_ENABLE_UNIFIED_MEMORY` is documented as automatically swapping out VRAM under pressure automatically, letting you run any model as long as it fits within available RAM. I tried running it but I still get a CUDA OOM error.

[This](https://github.com/ggml-org/llama.cpp/issues/10091#issuecomment-2679610580) comment may be useful in solving the problem.

### Relevant log output

```shell
common_init_from_params: added </s> logit bias = -inf
common_init_from_params: setting dry_penalty_last_n to ctx_size = 32768
common_init_from_params: warming up the model with an empty run - please wait ... (--no-warmup to disable)
/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:87: CUDA error
CUDA error: out of memory
current device: 0, in function alloc at /llama/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:455
cuMemCreate(&handle, reserve_size, &prop, 0)
[New LWP 129334]
[New LWP 129333]
[New LWP 129332]
[New LWP 129331]
[New LWP 129330]
[New LWP 129329]
[New LWP 129328]
[New LWP 129327]
[New LWP 129326]
[New LWP 129325]
[New LWP 129324]
[New LWP 129323]
[New LWP 129322]
[New LWP 129321]
[New LWP 129320]
[New LWP 129315]

This GDB supports auto-downloading debuginfo from the following URLs:
<https://debuginfod.archlinux.org>
Enable debuginfod for this session? (y or [n]) [answered N; input not from terminal]
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0x00007efeb3e9f042 in ?? () from /usr/lib/libc.so.6
#0  0x00007efeb3e9f042 in ?? () from /usr/lib/libc.so.6
#1  0x00007efeb3e931ac in ?? () from /usr/lib/libc.so.6
#2  0x00007efeb3e931f4 in ?? () from /usr/lib/libc.so.6
#3  0x00007efeb3f03dcf in wait4 () from /usr/lib/libc.so.6
#4  0x00007efeba36fb2b in ggml_print_backtrace () from /llama/llama.cpp/b/bin/libggml-base.so
#5  0x00007efeba36fc90 in ggml_abort () from /llama/llama.cpp/b/bin/libggml-base.so
#6  0x00007efebb25cb31 in ggml_cuda_error(char const*, char const*, char const*, int, char const*) () from /llama/llama.cpp/b/bin/libggml-cuda.so
#7  0x00007efebb26fa7d in ggml_cuda_pool_vmm::alloc(unsigned long, unsigned long*) () from /llama/llama.cpp/b/bin/libggml-cuda.so
#8  0x00007efebb335434 in ggml_cuda_mul_mat_vec_q(ggml_backend_cuda_context&, ggml_tensor const*, ggml_tensor const*, ggml_tensor const*, ggml_tensor*) () from /llama.cpp/b/bin/libggml-cuda.so
#9  0x00007efebb26b55a in ggml_backend_cuda_graph_compute(ggml_backend*, ggml_cgraph*) () from /llama.cpp/b/bin/libggml-cuda.so
#10 0x00007efeba389af3 in ggml_backend_sched_graph_compute_async () from /llama.cpp/b/bin/libggml-base.so
#11 0x00007efebbc94440 in llama_context::graph_compute(ggml_cgraph*, bool) () from /llama.cpp/b/bin/libllama.so
#12 0x00007efebbc95cc3 in llama_context::process_ubatch(llama_ubatch const&, llm_graph_type, llama_memory_context_i*, ggml_status&) () from /llama.cpp/b/bin/libllama.so
#13 0x00007efebbc9accf in llama_context::decode(llama_batch const&) () from /llama.cpp/b/bin/libllama.so
#14 0x00007efebbc9bc6e in llama_decode () from /run/media/anon/STORAGE/AI/llama/llama.cpp/b/bin/libllama.so
#15 0x000055e7d8189d08 in common_init_from_params(common_params&) ()
#16 0x000055e7d8064e1e in server_context::load_model(common_params const&) ()
#17 0x000055e7d7ffe0b2 in main ()
[Inferior 1 (process 129314) detached]
fish: Job 1, 'GGML_CUDA_ENABLE_UNIFIED_MEMORY…' terminated by signal SIGABRT (Abort)
```

If this feature is not planned to be supported, it should probably be removed from the documentation.

**Comment by IMbackK** [comment]
I dont do CUDA but at least for ROCM/HIP the avialbilty of managed memory depends on platform details such as OS (windows is not supported) bar size and iommu state.

I could be that like rocm, cuda simply dosent support managed memory in all configurations.

From a performance standpoint, using managed memory on a dgpu as opposed to offloading fewer tensors is a terrible proposition and not worth it.

**Comment by XZVB12** [comment]
> the avialbilty of managed memory depends on platform details such as OS

My system should supports this mechanism, at least I didn’t find any other requirements than the nvidia [documentation](https://docs.nvidia.cn/cuda/cuda-c-programming-guide/index.html#unified-memory-programming) And as far as I understand my system fits these requirements.

<img width="1150" height="137" alt="Image" src="https://github.com/user-attachments/assets/69ba025a-c38a-4ec3-9f7f-b33c3c18d1f5" />



> From a performance standpoint, using managed memory on a dgpu as opposed to offloading fewer tensors is a terrible proposition and not worth it.

You may be right, but I assume that the performance will be higher than when splitting the computation between dGPU and CPU via `-ngl`

**Comment by IMbackK** [comment]
no the performance will be lower, much much lower.

However i guess it should work, yes

**Comment by IMbackK** [comment]
I can confirm that it works correctly on a ROCM dgpu, however it is extremely slow as expected.

**Comment by XZVB12** [comment]
It seems this is a nvidia bug and does not work: https://github.com/NVIDIA/open-gpu-kernel-modules/issues/758
Although they indicate in their documentation this functional as working, it seems not. This is crazy.
Also the description of requirements from this [message](https://github.com/NVIDIA/open-gpu-kernel-modules/issues/758#issuecomment-3217042110) does not match what is stated in their documentation.

@matteoserva As the author of this [change](https://github.com/ggml-org/llama.cpp/pull/8035) Can you please answer if this feature works and what requirements for it? In your tests everything worked, which contradicts other [reports](https://github.com/NVIDIA/open-gpu-kernel-modules/issues/663) that this functionally broke and never worked.

**Comment by IMbackK** [comment]
@XZVB12 besides the very high cpu requirements its pretty much like i expected and exactly the same as on rocm.
Without large sized bar implementing managed memory would be pretty hard and of poor performance so both amd and nivida dont bother.

NVIDIA needs to document this better it seams.

**Comment by IMbackK** [comment]
ROCM and CUDA (i think) both include an api to check if HMM is available, what we should do is print a warning to the user that GGML_CUDA_ENABLE_UNIFIED_MEMORY=1 is not effective in the cases where HMM is not available.

**Comment by slaren** [comment]
It may work if you build with `GGML_CUDA_NO_VMM`.

**Comment by matteoserva** [comment]
From skimming the code I see that with VMM it uses cuMemCreate, skipping the managed memory allocation:
https://github.com/ggml-org/llama.cpp/blob/f2a789e33490deb483a2694b066b37e45524bb79/ggml/src/ggml-cuda/ggml-cuda.cu#L455

**Comment by XZVB12** [comment]
> It may work if you build with `GGML_CUDA_NO_VMM`.

i try build with `GGML_CUDA_NO_VMM` flag, Unfortunately I get all the same cuda oom error.
```
./llama-server --version
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
Device 0: NVIDIA GeForce RTX 3060, compute capability 8.6, VMM: no
version: 6567 (3a5997196)
built with cc (GCC) 15.2.1 20250813 for x86_64-pc-linux-gnu
```

> print a warning to the user that GGML_CUDA_ENABLE_UNIFIED_MEMORY=1 is not effective in the cases where HMM is not available.

This is a good idea, maybe also worth mentioning in the documentation that it will have extremely low performance and has no clear status with Nvidia

**Comment by IMbackK** [comment]
I'd like to note that its only expected to be slow on dgpus on igpus (apus) using gtt (system ram) is fast.

**Comment by ah2014** [comment]
> no the performance will be lower, much much lower.
> 
> However i guess it should work, yes

On my system the performance is much higher (almost 2x for GPT-OSS 20B) using `-ngl 999` and letting `GGML_CUDA_ENABLE_UNIFIED_MEMORY=1` take care of splitting between CPU and dGPU.

**Comment by yunwei37** [comment]
Seems like it's a bug in driver/else where? 

Here is a hack commit to make it work by adding ` cudaMemAdvise(*ptr, size, cudaMemAdviseSetPreferredLocation, cudaCpuDeviceId);` https://github.com/ggml-org/llama.cpp/commit/da3f59fe5d21f8c77346a98eaf8b1dc9c17cedb7

**Comment by opsec-ai** [comment]
GGML_CUDA_ENABLE_UNIFIED_MEMORY=1 is working for me with RTX 3070 mobile

...after rolling back video driver from beta to the supported one for platform; Fedora43

ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: yes
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3070 Laptop GPU, compute capability 8.6, VMM: yes

I understand now that some older cards do not support unified memory. Try [AirLLM](https://github.com/lyogavin/airllm).
