### ISSUE TITLE
Eval bug: Using llama.cpp with ROCm produces garbage output with --split-mode layer

### ISSUE THREAD

**Issue by thor171** [ggml-org/llama.cpp#16424]
### Name and Version

llama-cli --version

```
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 3 ROCm devices:
  Device 0: AMD Instinct MI50/MI60, gfx906:sramecc+:xnack- (0x906), VMM: no, Wave Size: 64
  Device 1: AMD Instinct MI50/MI60, gfx906:sramecc+:xnack- (0x906), VMM: no, Wave Size: 64
  Device 2: AMD Instinct MI50/MI60, gfx906:sramecc+:xnack- (0x906), VMM: no, Wave Size: 64
version: 6688 (898acba6)
built with cc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0 for x86_64-linux-gnu
```

ROCm Version

rocm-6.4.3

Operating System

Ubuntu 24.04.3 LTS (Noble Numbat)

### Operating systems

Linux

### GGML backends

HIP

### Hardware

CPU

2x Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz

GPU

3x AMD Instinct MI50/MI60

### Models

Using other models than gpt-oss-120b produces garbage, too.

However, when using a small model which fits in the memory of just one graphic card and setting --split-mode none, everything is working well.

### Problem description & steps to reproduce

Hi,
usually I am using llama.cpp with Vulkan which works without any problems. However, recently llama.cpp got some optimizations so the performance of ROCm seemed to me worth the trouble.
I installed ROCm from apt, built llama.cpp with HIP support for gfx906 (according to the build instructions in the documentation).
I tested it using my default settings:

```
#!/bin/bash

MODEL="unsloth/gpt-oss-120b-GGUF/UD-Q4_K_XL/gpt-oss-120b-UD-Q4_K_XL-00001-of-00002.gguf"

MODELS_PATH="/home/kyouma/ML/models"

LLAMA_ROCM="/home/kyouma/ML/llama.cpp/04_10_2025/llama.cpp/build/bin"
LLAMA_PATH=$LLAMA_ROCM  #"/home/kyouma/ML/llama.cpp/b6550/build/bin"
BATCH_SIZE=8192

$LLAMA_PATH/llama-cli \
    --model $MODELS_PATH/$MODEL \
    --ctx-size 131072 \
    --n-gpu-layers 999 \
    --batch-size $BATCH_SIZE \
    --threads 2 \
    --temp 1.0 \
    --top-p 1.0 \
    --top-k 0 \
    --batch-size 131072 \
    --split-mode layer
```

But on prompt I just get garbage (see logs)

Steps to Reproduce

Install Ubuntu Server 24.04.
Install rocm from apt.
Build llama.cpp according to the build instructions in the official documentation for gfx906.
Try to run llama-cli with --split-mode layer.

### Relevant log output

```shell
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 3 ROCm devices:
  Device 0: AMD Instinct MI50/MI60, gfx906:sramecc+:xnack- (0x906), VMM: no, Wave Size: 64
  Device 1: AMD Instinct MI50/MI60, gfx906:sramecc+:xnack- (0x906), VMM: no, Wave Size: 64
  Device 2: AMD Instinct MI50/MI60, gfx906:sramecc+:xnack- (0x906), VMM: no, Wave Size: 64
build: 6688 (898acba6) with cc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0 for x86_64-linux-gnu
main: llama backend init
main: load the model and apply lora adapter, if any
llama_model_load_from_file_impl: using device ROCm0 (AMD Instinct MI50/MI60) (0000:04:00.0) - 32704 MiB free
llama_model_load_from_file_impl: using device ROCm1 (AMD Instinct MI50/MI60) (0000:07:00.0) - 32704 MiB free
llama_model_load_from_file_impl: using device ROCm2 (AMD Instinct MI50/MI60) (0000:83:00.0) - 32704 MiB free
llama_model_loader: additional 1 GGUFs metadata loaded.
llama_model_loader: loaded meta data with 40 key-value pairs and 687 tensors from /home/kyouma/ML/models/unsloth/gpt-oss-120b-GGUF/UD-Q4_K_XL/gpt-oss-120b-UD-Q4_K_XL-00001-of-00002.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = gpt-oss
llama_model_loader: - kv   1:                               general.type str              = model
llama_model_loader: - kv   2:                               general.name str              = Gpt-Oss-120B
llama_model_loader: - kv   3:                           general.basename str              = Gpt-Oss-120B
llama_model_loader: - kv   4:                       general.quantized_by str              = Unsloth
llama_model_loader: - kv   5:                         general.size_label str              = 120B
llama_model_loader: - kv   6:                            general.license str              = apache-2.0
llama_model_loader: - kv   7:                           general.repo_url str              = https://huggingface.co/unsloth
llama_model_loader: - kv   8:                               general.tags arr[str,2]       = ["vllm", "text-generation"]
llama_model_loader: - kv   9:                        gpt-oss.block_count u32              = 36
llama_model_loader: - kv  10:                     gpt-oss.context_length u32              = 131072
llama_model_loader: - kv  11:                   gpt-oss.embedding_length u32              = 2880
llama_model_loader: - kv  12:                gpt-oss.feed_forward_length u32              = 2880
llama_model_loader: - kv  13:               gpt-oss.attention.head_count u32              = 64
llama_model_loader: - kv  14:            gpt-oss.attention.head_count_kv u32              = 8
llama_model_loader: - kv  15:                     gpt-oss.rope.freq_base f32              = 150000,000000
llama_model_loader: - kv  16:   gpt-oss.attention.layer_norm_rms_epsilon f32              = 0,000010
llama_model_loader: - kv  17:                       gpt-oss.expert_count u32              = 128
llama_model_loader: - kv  18:                  gpt-oss.expert_used_count u32              = 4
llama_model_loader: - kv  19:               gpt-oss.attention.key_length u32              = 64
llama_model_loader: - kv  20:             gpt-oss.attention.value_length u32              = 64
llama_model_loader: - kv  21:           gpt-oss.attention.sliding_window u32              = 128
llama_model_loader: - kv  22:         gpt-oss.expert_feed_forward_length u32              = 2880
llama_model_loader: - kv  23:                  gpt-oss.rope.scaling.type str              = yarn
llama_model_loader: - kv  24:                gpt-oss.rope.scaling.factor f32              = 32,000000
llama_model_loader: - kv  25: gpt-oss.rope.scaling.original_context_length u32              = 4096
llama_model_loader: - kv  26:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  27:                         tokenizer.ggml.pre str              = gpt-4o
llama_model_loader: - kv  28:                      tokenizer.ggml.tokens arr[str,201088]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  29:                  tokenizer.ggml.token_type arr[i32,201088]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  30:                      tokenizer.ggml.merges arr[str,446189]  = ["Ġ Ġ", "Ġ ĠĠĠ", "ĠĠ ĠĠ", "...
llama_model_loader: - kv  31:                tokenizer.ggml.bos_token_id u32              = 199998
llama_model_loader: - kv  32:                tokenizer.ggml.eos_token_id u32              = 200002
llama_model_loader: - kv  33:            tokenizer.ggml.padding_token_id u32              = 200017
llama_model_loader: - kv  34:                    tokenizer.chat_template str              = {# Chat template fixes by Unsloth #}\n...
llama_model_loader: - kv  35:               general.quantization_version u32              = 2
llama_model_loader: - kv  36:                          general.file_type u32              = 15
llama_model_loader: - kv  37:                                   split.no u16              = 0
llama_model_loader: - kv  38:                        split.tensors.count i32              = 687
llama_model_loader: - kv  39:                                split.count u16              = 2
llama_model_loader: - type  f32:  433 tensors
llama_model_loader: - type q5_0:   90 tensors
llama_model_loader: - type q8_0:   20 tensors
llama_model_loader: - type q4_K:   26 tensors
llama_model_loader: - type q6_K:   10 tensors
llama_model_loader: - type mxfp4:  108 tensors
print_info: file format = GGUF V3 (latest)
print_info: file type   = Q4_K - Medium
print_info: file size   = 58,68 GiB (4,31 BPW) 
load: printing all EOG tokens:
load:   - 199999 ('<|endoftext|>')
load:   - 200002 ('<|return|>')
load:   - 200007 ('<|end|>')
load:   - 200012 ('<|call|>')
load: special_eog_ids contains both '<|return|>' and '<|call|>' tokens, removing '<|end|>' token from EOG list
load: special tokens cache size = 21
load: token to piece cache size = 1,3332 MB
print_info: arch             = gpt-oss
print_info: vocab_only       = 0
print_info: n_ctx_train      = 131072
print_info: n_embd           = 2880
print_info: n_layer          = 36
print_info: n_head           = 64
print_info: n_head_kv        = 8
print_info: n_rot            = 64
print_info: n_swa            = 128
print_info: is_swa_any       = 1
print_info: n_embd_head_k    = 64
print_info: n_embd_head_v    = 64
print_info: n_gqa            = 8
print_info: n_embd_k_gqa     = 512
print_info: n_embd_v_gqa     = 512
print_info: f_norm_eps       = 0,0e+00
print_info: f_norm_rms_eps   = 1,0e-05
print_info: f_clamp_kqv      = 0,0e+00
print_info: f_max_alibi_bias = 0,0e+00
print_info: f_logit_scale    = 0,0e+00
print_info: f_attn_scale     = 0,0e+00
print_info: n_ff             = 2880
print_info: n_expert         = 128
print_info: n_expert_used    = 4
print_info: causal attn      = 1
print_info: pooling type     = 0
print_info: rope type        = 2
print_info: rope scaling     = yarn
print_info: freq_base_train  = 150000,0
print_info: freq_scale_train = 0,03125
print_info: n_ctx_orig_yarn  = 4096
print_info: rope_finetuned   = unknown
print_info: model type       = 120B
print_info: model params     = 116,83 B
print_info: general.name     = Gpt-Oss-120B
print_info: n_ff_exp         = 2880
print_info: vocab type       = BPE
print_info: n_vocab          = 201088
print_info: n_merges         = 446189
print_info: BOS token        = 199998 '<|startoftext|>'
print_info: EOS token        = 200002 '<|return|>'
print_info: EOT token        = 199999 '<|endoftext|>'
print_info: PAD token        = 200017 '<|reserved_200017|>'
print_info: LF token         = 198 'Ċ'
print_info: EOG token        = 199999 '<|endoftext|>'
print_info: EOG token        = 200002 '<|return|>'
print_info: EOG token        = 200012 '<|call|>'
print_info: max token length = 256
load_tensors: loading model tensors, this can take a while... (mmap = true)
load_tensors: offloading 36 repeating layers to GPU
load_tensors: offloading output layer to GPU
load_tensors: offloaded 37/37 layers to GPU
load_tensors:        ROCm0 model buffer size = 21263,21 MiB
load_tensors:        ROCm1 model buffer size = 19634,98 MiB
load_tensors:        ROCm2 model buffer size = 18599,65 MiB
load_tensors:   CPU_Mapped model buffer size =   586,82 MiB
....................................................................................................
llama_context: constructing llama_context
llama_context: n_seq_max     = 1
llama_context: n_ctx         = 131072
llama_context: n_ctx_per_seq = 131072
llama_context: n_batch       = 131072
llama_context: n_ubatch      = 512
llama_context: causal_attn   = 1
llama_context: flash_attn    = auto
llama_context: kv_unified    = false
llama_context: freq_base     = 150000,0
llama_context: freq_scale    = 0,03125
llama_context:  ROCm_Host  output buffer size =     0,77 MiB
llama_kv_cache_iswa: creating non-SWA KV cache, size = 131072 cells
llama_kv_cache:      ROCm0 KV buffer size =  1536,00 MiB
llama_kv_cache:      ROCm1 KV buffer size =  1536,00 MiB
llama_kv_cache:      ROCm2 KV buffer size =  1536,00 MiB
llama_kv_cache: size = 4608,00 MiB (131072 cells,  18 layers,  1/1 seqs), K (f16): 2304,00 MiB, V (f16): 2304,00 MiB
llama_kv_cache_iswa: creating     SWA KV cache, size = 768 cells
llama_kv_cache:      ROCm0 KV buffer size =    10,50 MiB
llama_kv_cache:      ROCm1 KV buffer size =     9,00 MiB
llama_kv_cache:      ROCm2 KV buffer size =     7,50 MiB
llama_kv_cache: size =   27,00 MiB (   768 cells,  18 layers,  1/1 seqs), K (f16):   13,50 MiB, V (f16):   13,50 MiB
llama_context: pipeline parallelism enabled (n_copies=4)
llama_context: Flash Attention was auto, set to enabled
llama_context:      ROCm0 compute buffer size =  1276,07 MiB
llama_context:      ROCm1 compute buffer size =   646,82 MiB
llama_context:      ROCm2 compute buffer size =   958,45 MiB
llama_context:  ROCm_Host compute buffer size =  1035,71 MiB
llama_context: graph nodes  = 2024
llama_context: graph splits = 4
common_init_from_params: added <|endoftext|> logit bias = -inf
common_init_from_params: added <|return|> logit bias = -inf
common_init_from_params: added <|call|> logit bias = -inf
common_init_from_params: setting dry_penalty_last_n to ctx_size = 131072
common_init_from_params: warming up the model with an empty run - please wait ... (--no-warmup to disable)
main: llama threadpool init, n_threads = 2
main: chat template is available, enabling conversation mode (disable it with -no-cnv)
main: chat template example:
<|start|>system<|message|>You are a helpful assistant<|end|><|start|>user<|message|>Hello<|end|><|start|>assistant<|message|>Hi there<|return|><|start|>user<|message|>How are you?<|end|><|start|>assistant

system_info: n_threads = 2 (n_threads_batch = 2) / 64 | ROCm : NO_VMM = 1 | PEER_MAX_BATCH_SIZE = 128 | CPU : SSE3 = 1 | SSSE3 = 1 | AVX = 1 | AVX2 = 1 | F16C = 1 | FMA = 1 | BMI2 = 1 | LLAMAFILE = 1 | OPENMP = 1 | REPACK = 1 | 

main: interactive mode on.
sampler seed: 3597113008
sampler params: 
	repeat_last_n = 64, repeat_penalty = 1,000, frequency_penalty = 0,000, presence_penalty = 0,000
	dry_multiplier = 0,000, dry_base = 1,750, dry_allowed_length = 2, dry_penalty_last_n = 131072
	top_k = 0, top_p = 1,000, min_p = 0,050, xtc_probability = 0,000, xtc_threshold = 0,100, typical_p = 1,000, top_n_sigma = -1,000, temp = 1,000
	mirostat = 0, mirostat_lr = 0,100, mirostat_ent = 5,000
sampler chain: logits -> logit-bias -> penalties -> dry -> top-n-sigma -> top-k -> typical -> top-p -> min-p -> xtc -> temp-ext -> dist 
generate: n_ctx = 131072, n_batch = 131072, n_predict = -1, n_keep = 0

== Running in interactive mode. ==
 - Press Ctrl+C to interject at any time.
 - Press Return to return control to the AI.
 - To return control without starting a new line, end your input with '/'.
 - If you want to submit another line, end your input with '\'.
 - Not using system message. To change it, set a different value via -sys PROMPT


> hi
ర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్తర్త
```

**Comment by IMbackK** [comment]
This is a well known bug that affects some rocm setups. There is evidence that its caused by buggy pcie hardware implementations on the host systems, but the exact cause has not been pinned down, regardless it is not a bug in llamacpp.

llamacpp includes a performance decreasing workaround when compiled with `-DGGML_CUDA_NO_PEER_COPY=On` however this is a bug on your platform and affects every user of pcie p2p copies not just llamacpp.

To avoid this bug you can also disabling pcie p2p in your kernel.

If some of your gpus are behind a pcie bridge chip you may be able to avoid this bug by moving to a different pcie slot so that they are not behind this chip, avoiding the hardware bug.

**Comment by thor171** [comment]
@IMbackK Thanks, your solution works. However, I found out, the problem was caused my IOMMU, or Vt-D how Intel labeled it.
If I disable Vt-D everything works without additional compile flags.

Only thing which does not work is using --split-mode row. I always get the following error in starting llama-bench or cli:

"Memory access fault by GPU node-4 (Agent handle: 0x5aa51f0e9050) on address 0x32161000. Reason: Page not present or supervisor privilege."

I tested peer to peer sample:

```
currentGpu#1 canAccessPeer: peerGpu#0=1
currentGpu#2 canAccessPeer: peerGpu#0=1
currentGpu#2 canAccessPeer: peerGpu#1=1
currentGpu=0 peerGpu=1 (Total no. of gpu = 3)
Peer2Peer PASSED!
```

**Comment by Black6spdZ** [comment]
https://github.com/lemonade-sdk/llamacpp-rocm/issues/75
