### ISSUE TITLE
Eval bug: ROCm illegal memory access with `-sm row`

### ISSUE THREAD

**Issue by MagoDelBlocco** [ggml-org/llama.cpp#16799]
### Name and Version

./llama-cli --version                        
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 5090, compute capability 12.0, VMM: yes
load_backend: loaded CUDA backend from /bank/llama.cpp/libggml-cuda.so
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 ROCm devices:
  Device 0: AMD Radeon Graphics, gfx906:sramecc+:xnack- (0x906), VMM: no, Wave Size: 64
load_backend: loaded ROCm backend from /bank/llama.cpp/libggml-hip.so
load_backend: loaded CPU backend from /bank/llama.cpp/libggml-cpu-haswell.so
version: 6853 (945501f5e)
built with cc (Debian 14.2.0-19) 14.2.0 for x86_64-linux-gnu

### Operating systems

Linux

### GGML backends

HIP

### Hardware

CPU: Threadripper 5975wx
GPU 1: RTX 5090
GPU 2: AMD Instinct MI50 32GB (gfx906)

### Models

Unsloth's `gpt-oss-120b-UD-Q6_K_XL`

### Problem description & steps to reproduce

Running the model with `-sm row` crashes at warmup. With `-sm layer` this does not reproduce. When running the model on the gfx906 alone this does not reproduce.

Steps to reproduce:
- Compiled with ```cmake -B build \
-DGGML_NATIVE=ON \
-DGGML_CUDA=ON \
-DGGML_CUDA_USE_GRAPHS=ON \
-DGGML_CUBLAS=ON \
-DCMAKE_CUDA_ARCHITECTURES="120" \
-DGGML_CUDA_F16=ON \
-DGGML_BACKEND_DL=ON \
-DGGML_HIP=ON \
-DGGML_HIP_GRAPHS=ON \
-DGPU_TARGETS=gfx906 \
-DCMAKE_BUILD_TYPE=Release \
-DGGML_CPU_ALL_VARIANTS=ON```

ROCm version is 7.0.1 in this case, using the tensiles for gfx906 of ROCm 6.4.3.

- Ran with ```./llama-cli -m gpt-oss-120b-UD-Q6_K_XL-00001-of-00002.gguf -c 2048 -dev CUDA0,ROCm0 -sm row```

### First Bad Commit

[b6841](https://github.com/ggml-org/llama.cpp/releases/tag/b6841)

### Relevant log output

```shell
: offloaded 37/37 layers to GPU
load_tensors:  CUDA0_Split model buffer size =   485.98 MiB
load_tensors:        CUDA0 model buffer size = 30740.94 MiB
load_tensors:        ROCm0 model buffer size = 27505.06 MiB
load_tensors:  ROCm0_Split model buffer size =  1021.64 MiB
load_tensors:   CPU_Mapped model buffer size =   586.82 MiB
....................................................................................................
llama_context: constructing llama_context
llama_context: n_seq_max     = 1
llama_context: n_ctx         = 2048
llama_context: n_ctx_per_seq = 2048
llama_context: n_batch       = 2048
llama_context: n_ubatch      = 512
llama_context: causal_attn   = 1
llama_context: flash_attn    = auto
llama_context: kv_unified    = false
llama_context: freq_base     = 150000.0
llama_context: freq_scale    = 0.03125
llama_context: n_ctx_per_seq (2048) < n_ctx_train (131072) -- the full capacity of the model will not be utilized
llama_context:  ROCm_Host  output buffer size =     0.77 MiB
llama_kv_cache_iswa: creating non-SWA KV cache, size = 2048 cells
llama_kv_cache:      ROCm0 KV buffer size =    36.00 MiB
llama_kv_cache:      CUDA0 KV buffer size =    36.00 MiB
llama_kv_cache: size =   72.00 MiB (  2048 cells,  18 layers,  1/1 seqs), K (f16):   36.00 MiB, V (f16):   36.00 MiB
llama_kv_cache_iswa: creating     SWA KV cache, size = 768 cells
llama_kv_cache:      ROCm0 KV buffer size =    12.00 MiB
llama_kv_cache:      CUDA0 KV buffer size =    15.00 MiB
llama_kv_cache: size =   27.00 MiB (   768 cells,  18 layers,  1/1 seqs), K (f16):   13.50 MiB, V (f16):   13.50 MiB
llama_context: Flash Attention was auto, set to enabled
llama_context:      CUDA0 compute buffer size =    95.02 MiB
llama_context:      ROCm0 compute buffer size =   398.38 MiB
llama_context:  CUDA_Host compute buffer size =    11.15 MiB
llama_context: graph nodes  = 2024
llama_context: graph splits = 3
common_init_from_params: added <|endoftext|> logit bias = -inf
common_init_from_params: added <|return|> logit bias = -inf
common_init_from_params: added <|call|> logit bias = -inf
common_init_from_params: setting dry_penalty_last_n to ctx_size = 2048
common_init_from_params: warming up the model with an empty run - please wait ... (--no-warmup to disable)
/bank/llama.cpp/source/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:88: ROCm error
ROCm error: an illegal memory access was encountered
  current device: -1, in function ggml_backend_cuda_synchronize at /bank/llama.cpp/source/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:2787
  hipStreamSynchronize(cuda_ctx->stream())
[New LWP 49691]
[New LWP 49666]
[New LWP 49665]
[New LWP 49664]
[New LWP 49661]
[New LWP 49657]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
__syscall_cancel_arch () at ../sysdeps/unix/sysv/linux/x86_64/syscall_cancel.S:56
warning: 56	../sysdeps/unix/sysv/linux/x86_64/syscall_cancel.S: No such file or directory
#0  __syscall_cancel_arch () at ../sysdeps/unix/sysv/linux/x86_64/syscall_cancel.S:56
56	in ../sysdeps/unix/sysv/linux/x86_64/syscall_cancel.S
#1  0x00007fd662899668 in __internal_syscall_cancel (a1=<optimized out>, a2=<optimized out>, a3=<optimized out>, a4=<optimized out>, a5=a5@entry=0, a6=a6@entry=0, nr=61) at ./nptl/cancellation.c:49
warning: 49	./nptl/cancellation.c: No such file or directory
#2  0x00007fd6628996ad in __syscall_cancel (a1=<optimized out>, a2=<optimized out>, a3=<optimized out>, a4=<optimized out>, a5=a5@entry=0, a6=a6@entry=0, nr=61) at ./nptl/cancellation.c:75
75	in ./nptl/cancellation.c
#3  0x00007fd662904787 in __GI___wait4 (pid=<optimized out>, stat_loc=<optimized out>, options=<optimized out>, usage=<optimized out>) at ../sysdeps/unix/sysv/linux/wait4.c:30
warning: 30	../sysdeps/unix/sysv/linux/wait4.c: No such file or directory
#4  0x00007fd662ee3d6b in ggml_print_backtrace () from libggml-base.so
#5  0x00007fd662ee3ebe in ggml_abort () from libggml-base.so
#6  0x00007fd423b1ea12 in ggml_cuda_error(char const*, char const*, char const*, int, char const*) () from /bank/llama.cpp/libggml-hip.so
#7  0x00007fd423b23af4 in ggml_backend_cuda_synchronize(ggml_backend*) () from /bank/llama.cpp/libggml-hip.so
#8  0x00007fd662efa4fe in ggml_backend_sched_synchronize () from libggml-base.so
#9  0x00007fd66300a270 in llama_context::synchronize() () from libllama.so
#10 0x000055c9a157c55a in common_init_from_params(common_params&) ()
#11 0x000055c9a147fc1c in main ()
[Inferior 1 (process 49643) detached]
[1]    49643 IOT instruction  ./llama-cli -m /bank/models/openai/gpt-oss-120b-UD-Q6_K_XL-00001-of-00002.gguf
```

**Comment by IMbackK** [comment]
There is a well known issue with gfx906 on newer versions of rocr/ kernel that causes failures in p2p dma.
It is very likely you are hitting this. This is a bug in rocm/the linux kernel and not a llamacpp bug.

**Comment by MagoDelBlocco** [comment]
It is possible this is true, but I have been using ROCm 7.0.1 since releases b66xx and this only surfaced after commit f77c13b.

**Comment by IMbackK** [comment]
ok, could be our issue, but i cant repoduce atm with my hardware.

dose it still happen with p2p copies disabled? `GGML_CUDA_NO_PEER_COPY`?
what dose  `rocm-smi --showtopo` show for you?

**Comment by MagoDelBlocco** [comment]
I retried by adding the `-DGGML_CUDA_NO_PEER_COPY=ON` option to the compile flags, it still crashed.

```
rocm-smi --showtopo


============================ ROCm System Management Interface ============================
================================ Weight between two GPUs =================================
       GPU0         
GPU0   0            

================================= Hops between two GPUs ==================================
       GPU0         
GPU0   0            

=============================== Link Type between two GPUs ===============================
       GPU0         
GPU0   0            

======================================= Numa Nodes =======================================
GPU[0]		: (Topology) Numa Node: 1
GPU[0]		: (Topology) Numa Affinity: 1
================================== End of ROCm SMI Log ===================================```

**Comment by IMbackK** [comment]
Ok, hmm its going to be petty difficult do debug this without having a a mixed vendor setup (which are rare after all) rocr/amdhsa uses dmabuf to share buffers between devices. dmabuf is desinged to be vendor neutral but the nvidia implementation has been known to be extremely bad (see constant wayland problems that also use the same mechanism). I acutally not sure what happens exactly with the buffers in a mixed backend setup, presumably they are simply copied to a cpu buffer and imported i will take a look at that to see if i can find anything wrong.

**Comment by MagoDelBlocco** [comment]
If I can help with any tests, I would happly do so. I don't have the bandwidth to get to look into the code, unfortunately, so I really appreciate the help here.

**Comment by radiskulldevildoll** [comment]
I can confirm b6841 as first bad commit, though with more pedestrian hardware. Fails with `-sm row`

```
CUDA_VISIBLE_DEVICES="1,2"
  Device 0: Tesla P40, compute capability 6.1, VMM: yes
  Device 1: Tesla P40, compute capability 6.1, VMM: yes
```
and
```
 Device 0: NVIDIA GeForce RTX 2070, compute capability 7.5, VMM: yes
  Device 1: Tesla P40, compute capability 6.1, VMM: yes
  Device 2: Tesla P40, compute capability 6.1, VMM: yes
```

**Comment by gm-stack** [comment]
I was experiencing this across a fairly wide range of versions from about a few months ago up to now. Similar issues with `-sm row`

However, it went away when I compiled with `-DGGML_BACKEND_DL=ON -DGGML_CPU_ALL_VARIANTS=ON` in order to get ROCm and CUDA support at the same time, and now `-sm row` works. 

I've tested with no CUDA compiled in, just ROCm, and it's definitely broken without `-DGGML_BACKEND_DL=ON` and working with it.

Maybe that narrows things down?

**Comment by MagoDelBlocco** [comment]
> I've tested with no CUDA compiled in, just ROCm, and it's definitely broken without `-DGGML_BACKEND_DL=ON` and working with it.

The flags I used to compile can be seen in the original comment, this is not the issue.

**Comment by gm-stack** [comment]
Sorry, I missed the `-DGGML_BACKEND_DL=ON` was already there. 

I'm also running on Debian 14 with gfx906 cards, and it's working - but I'm running ROCm 6.4.3, not 7. I'll give 7 a go when I get some time, and see if it also breaks for me.

**Comment by luminous-ibz** [comment]
i can confirm this issue with rocm only build, I am running 2 radeon pro r9700's.

ROCBLAS_USE_HIPBLASLT=1 cmake -B build -DCMAKE_BUILD_TYPE=Release -DLLAMA_CURL=ON -DGGML_BF16=ON -DGGML_CUDA_NO_PEER_COPY=ON -DGGML_HIP_ROCWMMA_FATTN=ON -DGGML_HIP=ON -DGGML_HIPBLAS=ON  -DCMAKE_HIP_ARCHITECTURES="gfx1201" -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DGGML_HIP_GRAPHS=ON

is my cmake config.

```
Oct 30 02:36:27 llm start-llama.sh[262515]: /home/luminous/projects/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:88: ROCm error
Oct 30 02:36:27 llm start-llama.sh[262515]: ROCm error: an illegal memory access was encountered
Oct 30 02:36:27 llm start-llama.sh[262515]:   current device: -1, in function ggml_backend_cuda_synchronize at /home/luminous/projects/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:2787
Oct 30 02:36:27 llm start-llama.sh[262515]:   hipStreamSynchronize(cuda_ctx->stream())
Oct 30 02:36:27 llm start-llama.sh[262700]: [New LWP 262658]
Oct 30 02:36:27 llm start-llama.sh[262700]: [New LWP 262657]
Oct 30 02:36:27 llm start-llama.sh[262700]: [New LWP 262656]
Oct 30 02:36:27 llm start-llama.sh[262700]: [New LWP 262655]
Oct 30 02:36:27 llm start-llama.sh[262700]: [New LWP 262654]
Oct 30 02:36:27 llm start-llama.sh[262700]: [New LWP 262653]
Oct 30 02:36:27 llm start-llama.sh[262700]: [New LWP 262652]
Oct 30 02:36:27 llm start-llama.sh[262700]: [New LWP 262651]
Oct 30 02:36:27 llm start-llama.sh[262700]: [New LWP 262650]
Oct 30 02:36:27 llm start-llama.sh[262700]: [New LWP 262649]
Oct 30 02:36:27 llm start-llama.sh[262700]: [New LWP 262648]
Oct 30 02:36:27 llm start-llama.sh[262700]: [New LWP 262635]
Oct 30 02:36:27 llm start-llama.sh[262700]: [New LWP 262582]
Oct 30 02:36:27 llm start-llama.sh[262700]: [New LWP 262581]
Oct 30 02:36:27 llm start-llama.sh[262700]: [New LWP 262580]
Oct 30 02:36:27 llm start-llama.sh[262700]: [New LWP 262579]
Oct 30 02:36:27 llm start-llama.sh[262700]: [New LWP 262578]
Oct 30 02:36:27 llm start-llama.sh[262700]: [New LWP 262577]
Oct 30 02:36:27 llm start-llama.sh[262700]: [New LWP 262576]
Oct 30 02:36:27 llm start-llama.sh[262700]: [New LWP 262575]
Oct 30 02:36:27 llm start-llama.sh[262700]: [New LWP 262574]
Oct 30 02:36:27 llm start-llama.sh[262700]: [New LWP 262573]
Oct 30 02:36:27 llm start-llama.sh[262700]: [New LWP 262572]
Oct 30 02:36:27 llm start-llama.sh[262700]: [New LWP 262571]
Oct 30 02:36:27 llm start-llama.sh[262700]: [New LWP 262570]
Oct 30 02:36:27 llm start-llama.sh[262700]: [New LWP 262569]
Oct 30 02:36:27 llm start-llama.sh[262700]: [New LWP 262568]
Oct 30 02:36:27 llm start-llama.sh[262700]: [New LWP 262567]
Oct 30 02:36:27 llm start-llama.sh[262700]: [New LWP 262566]
Oct 30 02:36:27 llm start-llama.sh[262700]: [New LWP 262563]
Oct 30 02:36:29 llm start-llama.sh[262700]: warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/liblber.so.2
Oct 30 02:36:29 llm start-llama.sh[262700]: warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libbrotlidec.so.1
Oct 30 02:36:30 llm start-llama.sh[262700]: warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libbrotlicommon.so.1
Oct 30 02:36:31 llm start-llama.sh[262700]: [Thread debugging using libthread_db enabled]
Oct 30 02:36:31 llm start-llama.sh[262700]: Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Oct 30 02:36:31 llm start-llama.sh[262700]: 0x00007c508e310813 in __GI___wait4 (pid=262700, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
Oct 30 02:36:31 llm start-llama.sh[262700]: warning: 30        ../sysdeps/unix/sysv/linux/wait4.c: No such file or directory
Oct 30 02:36:31 llm start-llama.sh[262700]: #0  0x00007c508e310813 in __GI___wait4 (pid=262700, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
Oct 30 02:36:31 llm start-llama.sh[262700]: 30        in ../sysdeps/unix/sysv/linux/wait4.c
Oct 30 02:36:31 llm start-llama.sh[262700]: #1  0x00006470a986d093 in ggml_print_backtrace ()
Oct 30 02:36:31 llm start-llama.sh[262700]: #2  0x00006470a986d23b in ggml_abort ()
Oct 30 02:36:31 llm start-llama.sh[262700]: #3  0x00006470a931edc2 in ggml_cuda_error(char const*, char const*, char const*, int, char const*) ()
Oct 30 02:36:31 llm start-llama.sh[262700]: #4  0x00006470a9323e54 in ggml_backend_cuda_synchronize(ggml_backend*) ()
Oct 30 02:36:31 llm start-llama.sh[262700]: #5  0x00006470a9888364 in ggml_backend_sched_graph_compute_async ()
Oct 30 02:36:31 llm start-llama.sh[262700]: #6  0x00006470a9164841 in llama_context::graph_compute(ggml_cgraph*, bool) ()
Oct 30 02:36:31 llm start-llama.sh[262700]: #7  0x00006470a916627c in llama_context::process_ubatch(llama_ubatch const&, llm_graph_type, llama_memory_context_i*, ggml_status&) ()
Oct 30 02:36:31 llm start-llama.sh[262700]: #8  0x00006470a916c59f in llama_context::decode(llama_batch const&) ()
Oct 30 02:36:31 llm start-llama.sh[262700]: #9  0x00006470a916d4bf in llama_decode ()
Oct 30 02:36:31 llm start-llama.sh[262700]: #10 0x00006470a8f56d57 in server_context::update_slots() ()
Oct 30 02:36:31 llm start-llama.sh[262700]: #11 0x00006470a8f14702 in server_queue::start_loop() ()
Oct 30 02:36:31 llm start-llama.sh[262700]: #12 0x00006470a8ec5dba in main ()
Oct 30 02:36:31 llm start-llama.sh[262700]: [Inferior 1 (process 262515) detached]
```

**Comment by IMbackK** [comment]
I can now reproduce this problem, im not sure that the issue comes from llamacpp, but the fact that it has been repduced with both amd and nvidia hardware makes it likely.

**Comment by DrVonSinistro** [comment]
I also get illegal memory access when splitting rows with 2x P40 and 1x A2000. All is fine if I split layers instead of rows.

**Comment by 65a** [comment]
Is this the same thing as #15829 ? Does ubatch affect the problem?

**Comment by luminous-ibz** [comment]
i tried -ub 128, 256, 512, and 2048. all still crash.

**Comment by LostRuins** [comment]
Any idea which commit causes it? Been reported in nvidia row split as well

**Comment by radiskulldevildoll** [comment]
I think it was b6841 that broke row.

https://github.com/ggml-org/llama.cpp/releases/tag/b6841

CUDA: General GEMV fusion (#16715)

**Comment by LostRuins** [comment]
Indeed the case, after reverting it, it works fine again

**Comment by IMbackK** [comment]
Yeah so in the operator fusion case we are calling https://github.com/ggml-org/llama.cpp/blob/76af40aaaad78c42faecd8016a88362c788b84b0/ggml/src/ggml-cuda/vecdotq.cuh#L641 with `vbq` a pointer invalid on the device we are running on, which is already wrong in `src0` when we jump from the graph dispatch at https://github.com/ggml-org/llama.cpp/blob/76af40aaaad78c42faecd8016a88362c788b84b0/ggml/src/ggml-cuda/mmvq.cu#L605 

paging @am17an

**Comment by am17an** [comment]
Please check if #16935 fixes this

**Comment by TinyServal** [comment]
Can reproduce with a CUDA only multi-GPU setup, tested #16935 and it did not help.


```
$ llama-cli -m ggml-org_gpt-oss-120b-GGUF_gpt-oss-120b-mxfp4-00001-of-00003.gguf -sm row

/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:90: CUDA error
CUDA error: an illegal memory access was encountered
  current device: 0, in function launch_mul_mat_q at /llama.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:3559
  cudaFuncSetAttribute((mul_mat_q<type, mmq_x, false>), cudaFuncAttributeMaxDynamicSharedMemorySize, nbytes_shared)
/llama.cpp/build/bin/libggml-base.so(+0x1819b)[0x7f953405919b]
/llama.cpp/build/bin/libggml-base.so(ggml_print_backtrace+0x21c)[0x7f95340595fc]
/llama.cpp/build/bin/libggml-base.so(ggml_abort+0x15b)[0x7f95340597db]
/llama.cpp/build/bin/libggml-cuda.so(_Z15ggml_cuda_errorPKcS0_S0_iS0_+0xb7)[0x7f9531ea7fe7]
/llama.cpp/build/bin/libggml-cuda.so(+0x501c8a)[0x7f9532248c8a]
/llama.cpp/build/bin/libggml-cuda.so(_Z19ggml_cuda_mul_mat_qR25ggml_backend_cuda_contextPK11ggml_tensorS3_S3_PS1_+0x760)[0x7f9531ec98f0]
/llama.cpp/build/bin/libggml-cuda.so(+0x17411e)[0x7f9531ebb11e]
/llama.cpp/build/bin/libggml-cuda.so(+0x1746dc)[0x7f9531ebb6dc]
/llama.cpp/build/bin/libggml-base.so(ggml_backend_sched_graph_compute_async+0x817)[0x7f9534074d97]
/llama.cpp/build/bin/libllama.so(_ZN13llama_context13graph_computeEP11ggml_cgraphb+0xa1)[0x7f953419a521]
/llama.cpp/build/bin/libllama.so(_ZN13llama_context14process_ubatchERK12llama_ubatch14llm_graph_typeP22llama_memory_context_iR11ggml_status+0x11c)[0x7f953419bf5c]
/llama.cpp/build/bin/libllama.so(_ZN13llama_context6decodeERK11llama_batch+0x3df)[0x7f95341a227f]
/llama.cpp/build/bin/libllama.so(llama_decode+0xf)[0x7f95341a319f]
build/bin/llama-cli(+0x155c4d)[0x5595868e7c4d]
build/bin/llama-cli(+0x45cba)[0x5595867d7cba]
/lib/x86_64-linux-gnu/libc.so.6(+0x2a1ca)[0x7f95339fc1ca]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b)[0x7f95339fc28b]
build/bin/llama-cli(+0x4ba35)[0x5595867dda35]
Aborted (core dumped)
```

**Comment by am17an** [comment]
@TinyServal is that your complete command? I could reproduce the original error and it was fixed by #16935, but can't replicate this one. Also fusion only interferers with the GEMV path (batch_size = 1), whereas this crash is in mmq which is a GEMM.

**Comment by TinyServal** [comment]
Yes, that is the complete command, I only shortened the paths of the executable and model to make it more readable. No relevant environment variables are set, and llama.cpp was built with `cmake -B build -DGGML_CUDA=ON && cmake --build build --config Release` in `nvidia/cuda:13.0.1-devel-ubuntu24.04` from Docker Hub. Perhaps this is an unrelated bug, I'll do a proper bisect now.

**Comment by DrVonSinistro** [comment]
I do not know how to test #16935 other than look at the mods and go do them in my local copy of the source code. 

But here is my command to make:

cmake -B build -DGGML_OPENSSL=ON -DGGML_CUDA=ON -DGGML_CUDA_FA_ALL_QUANTS=ON -DGGML_CUDA_FORCE_MMQ=ON -DGGML_CUDA_FORCE_CUBLAS=ON -DLLAMA_CURL=OFF -DCMAKE_CUDA_ARCHITECTURES="61;86"

and I compile with Visual Studio 2022, I switch to release and edit few options in project like making it full optimization, set compute to 61 and 86 because I have 2x P40 and 1x A2000.

I'm a very old coder from the 80s and never got to study how you guys collaborate with GitHub. 

I'm on CUDA 12.9 because support for PASCAL is dropped with newer versions.

**Comment by TinyServal** [comment]
To check out a pull request locally, you can follow the instructions in the docs: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally

Alternatively if you'd rather just download a patch, add .diff at the end of the URL of a pull request, and GitHub will return a diff that you can apply directly. This works for commits as well.

- `https://github.com/ggml-org/llama.cpp/pull/16935` -> `https://github.com/ggml-org/llama.cpp/pull/16935.diff`
- `https://github.com/ggml-org/llama.cpp/pull/16935/commits/1d3a6152cac4a5798cf1bd1d04198284cddadb09` -> `https://github.com/ggml-org/llama.cpp/pull/16935/commits/1d3a6152cac4a5798cf1bd1d04198284cddadb09.diff`

**Comment by DrVonSinistro** [comment]
Alright, I just tried https://github.com/ggml-org/llama.cpp/pull/16935, compiled it like I always do and set back my models (QWEN3 30B-A3B and 235-A22B) to row mode and its working ! No more illegal memory access.

**Comment by TinyServal** [comment]
Bisect results below, `GGML_CUDA_DISABLE_FUSION` is unset unless explicitly mentioned. Looks like what I'm seeing is a different bug.

- f77c13b91f4d25754b6a0b857f98a6bc922a0aa7 was the first bad commit
```
/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:88: CUDA error
CUDA error: an illegal memory access was encountered
  current device: 0, in function ggml_backend_cuda_buffer_clear at /llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:661
  cudaStreamSynchronize(((cudaStream_t)0x2))
/llama.cpp/build/bin/libggml-base.so(+0x1819b)[0x7f5538ea719b]
/llama.cpp/build/bin/libggml-base.so(ggml_print_backtrace+0x21c)[0x7f5538ea75fc]
/llama.cpp/build/bin/libggml-base.so(ggml_abort+0x15b)[0x7f5538ea77db]
/llama.cpp/build/bin/libggml-cuda.so(_Z15ggml_cuda_errorPKcS0_S0_iS0_+0xb7)[0x7f5536d3e5c7]
/llama.cpp/build/bin/libggml-cuda.so(+0x15eb59)[0x7f5536d3eb59]
/llama.cpp/build/bin/libllama.so(_ZN14llama_kv_cache5clearEb+0x183)[0x7f5539024e13]
/llama.cpp/build/bin/libllama.so(_ZN19llama_kv_cache_iswa5clearEb+0x1d)[0x7f55390345ad]
build/bin/llama-cli(+0x14f39d)[0x55578f6d939d]
build/bin/llama-cli(+0x4497a)[0x55578f5ce97a]
/lib/x86_64-linux-gnu/libc.so.6(+0x2a1ca)[0x7f553884a1ca]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b)[0x7f553884a28b]
build/bin/llama-cli(+0x4a6f5)[0x55578f5d46f5]
Aborted (core dumped)
```
- `GGML_CUDA_DISABLE_FUSION=1` at f77c13b91f4d25754b6a0b857f98a6bc922a0aa7 -> no crash
- Applying #16935 on f77c13b91f4d25754b6a0b857f98a6bc922a0aa7 -> no crash
- `GGML_CUDA_DISABLE_FUSION=1` at ee3a5a10adf9e83722d1914dddc56a0623ececaf (current master) -> no crash
- Applying #16935 on ee3a5a10adf9e83722d1914dddc56a0623ececaf (current master) -> different crash
```
/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:90: CUDA error
CUDA error: an illegal memory access was encountered
  current device: 0, in function launch_mul_mat_q at /llama.cpp/ggml/src/ggml-cuda/template-instances/../mmq.cuh:3559
  cudaFuncSetAttribute((mul_mat_q<type, mmq_x, false>), cudaFuncAttributeMaxDynamicSharedMemorySize, nbytes_shared)
/llama.cpp/build/bin/libggml-base.so(+0x1819b)[0x7fb64ab0019b]
/llama.cpp/build/bin/libggml-base.so(ggml_print_backtrace+0x21c)[0x7fb64ab005fc]
/llama.cpp/build/bin/libggml-base.so(ggml_abort+0x15b)[0x7fb64ab007db]
/llama.cpp/build/bin/libggml-cuda.so(_Z15ggml_cuda_errorPKcS0_S0_iS0_+0xb7)[0x7fb64894b397]
/llama.cpp/build/bin/libggml-cuda.so(+0x503faa)[0x7fb648cedfaa]
/llama.cpp/build/bin/libggml-cuda.so(_Z19ggml_cuda_mul_mat_qR25ggml_backend_cuda_contextPK11ggml_tensorS3_S3_PS1_+0x760)[0x7fb64896cc90]
/llama.cpp/build/bin/libggml-cuda.so(+0x17449e)[0x7fb64895e49e]
/llama.cpp/build/bin/libggml-cuda.so(+0x174a7c)[0x7fb64895ea7c]
/llama.cpp/build/bin/libggml-base.so(ggml_backend_sched_graph_compute_async+0x817)[0x7fb64ab1bd97]
/llama.cpp/build/bin/libllama.so(_ZN13llama_context13graph_computeEP11ggml_cgraphb+0xa1)[0x7fb64ac41571]
/llama.cpp/build/bin/libllama.so(_ZN13llama_context14process_ubatchERK12llama_ubatch14llm_graph_typeP22llama_memory_context_iR11ggml_status+0x11c)[0x7fb64ac42fcc]
/llama.cpp/build/bin/libllama.so(_ZN13llama_context6decodeERK11llama_batch+0x3df)[0x7fb64ac493df]
/llama.cpp/build/bin/libllama.so(llama_decode+0xf)[0x7fb64ac4a2ff]
build/bin/llama-cli(+0x1560bd)[0x5655212450bd]
build/bin/llama-cli(+0x45daa)[0x565521134daa]
/lib/x86_64-linux-gnu/libc.so.6(+0x2a1ca)[0x7fb64a4a31ca]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b)[0x7fb64a4a328b]
build/bin/llama-cli(+0x4bb25)[0x56552113ab25]
Aborted (core dumped)
```

**Comment by am17an** [comment]
@TinyServal thank you for narrowing it down. It would be great if you can do another git bisect using #16715 + #16935 as base, because on my setup I can't replicate this

**Comment by TinyServal** [comment]
Sure, I'll do another bisect between f77c13b91f4d25754b6a0b857f98a6bc922a0aa7 and ee3a5a1 (master), with 1d3a6152cac4a5798cf1bd1d04198284cddadb09 (#16935) applied on top as a patch.

**Comment by TinyServal** [comment]
9a3ea685b937c0f0cbfda2e50004ea54bf187512 is the first bad commit, every step in the bisect process has 1d3a6152cac4a5798cf1bd1d04198284cddadb09 applied on top as a patch before compiling. `GGML_CUDA_DISABLE_FUSION` is never used during this process. The full command used for testing is still `llama-cli -m ggml-org_gpt-oss-120b-GGUF_gpt-oss-120b-mxfp4-00001-of-00003.gguf -sm row` as previously mentioned.

**Comment by am17an** [comment]
This PR enables the topk-moe fusion for gpt-oss.I think we don't check if any of the `srcs` involved in fusion are in split buffers (except GEMV), so possibly `weights` coming into the topk-moe path is split. Can you check if this diff fixes it 

```diff
diff --git a/ggml/src/ggml-cuda/ggml-cuda.cu b/ggml/src/ggml-cuda/ggml-cuda.cu
index fb4ee785d..7da0bb7c5 100644
--- a/ggml/src/ggml-cuda/ggml-cuda.cu
+++ b/ggml/src/ggml-cuda/ggml-cuda.cu
@@ -3019,7 +3019,9 @@ static bool ggml_cuda_can_fuse(const struct ggml_cgraph * cgraph, int node_idx,
         ggml_tensor * softmax = cgraph->nodes[node_idx + 4];
         ggml_tensor * weights = cgraph->nodes[node_idx + 5];

-        if (ggml_cuda_should_use_topk_moe(softmax, weights)) {
+        const bool split = ggml_backend_buft_is_cuda_split(weights->buffer->buft) || ggml_backend_buft_is_cuda_split(softmax->buffer->buft);
+
+        if (ggml_cuda_should_use_topk_moe(softmax, weights) && !split) {
             return true;
         }
     }
```

If it does, then we need to guard against fusing any split buffers

**Comment by TinyServal** [comment]
Applied that on top of 9a3ea685b937c0f0cbfda2e50004ea54bf187512 (in addition to 1d3a6152cac4a5798cf1bd1d04198284cddadb09) and crash persisted.

**Comment by am17an** [comment]
Hmm okay, I cannot reproduce this. Can you paste your output with GGML_SCHED_DEBUG=2 and I'll try to reproduce.

**Comment by TinyServal** [comment]
The `--verbose` option is required in addition to `GGML_SCHED_DEBUG=2` to get the full output. Attached the logs as a text file as it's way too much text to paste into a comment directly.

[logs.txt](https://github.com/user-attachments/files/23298051/logs.txt)

<details>

<summary>Full diff of what's applied on top of 9a3ea685b937c0f0cbfda2e50004ea54bf187512</summary>

```diff
diff --git a/ggml/src/ggml-cuda/ggml-cuda.cu b/ggml/src/ggml-cuda/ggml-cuda.cu
index fcff5d7cd..43b4c6ea9 100644
--- a/ggml/src/ggml-cuda/ggml-cuda.cu
+++ b/ggml/src/ggml-cuda/ggml-cuda.cu
@@ -2114,6 +2114,14 @@ static bool ggml_cuda_should_fuse_mul_mat_vec_f(const ggml_tensor * tensor) {
     const int cc      = ggml_cuda_info().devices[ggml_cuda_get_device()].cc;
     use_mul_mat_vec_f = use_mul_mat_vec_f && ggml_cuda_should_use_mmvf(src0->type, cc, src0->ne, is_mul_mat_id ? src1->ne[2] : src1->ne[1]);

+    const bool split = ggml_backend_buft_is_cuda_split(src0->buffer->buft) ||
+                       ggml_backend_buft_is_cuda_split(src1->buffer->buft);
+
+    //TODO: add support for fusion for split buffers
+    if (split) {
+        return false;
+    }
+
     //we only support fusion for ncols_dst = 1
     if (tensor->op == GGML_OP_MUL_MAT && dst->ne[1] != 1) {
         return false;
@@ -2153,6 +2161,15 @@ static bool ggml_cuda_should_fuse_mul_mat_vec_q(const ggml_tensor * tensor) {
         return false;
     }

+
+    const bool split = ggml_backend_buft_is_cuda_split(src0->buffer->buft) ||
+                       ggml_backend_buft_is_cuda_split(src1->buffer->buft);
+
+    //TODO: add support for fusion for split buffers
+    if (split) {
+        return false;
+    }
+
     return use_mul_mat_vec_q;
 }

@@ -3001,7 +3018,9 @@ static bool ggml_cuda_can_fuse(const struct ggml_cgraph * cgraph, int node_idx,
         ggml_tensor * softmax = cgraph->nodes[node_idx + 4];
         ggml_tensor * weights = cgraph->nodes[node_idx + 5];

-        if (ggml_cuda_should_use_topk_moe(softmax, weights)) {
+        const bool split = ggml_backend_buft_is_cuda_split(weights->buffer->buft) || ggml_backend_buft_is_cuda_split(softmax->buffer->buft);
+
+        if (ggml_cuda_should_use_topk_moe(softmax, weights) && !split) {
             return true;
         }
     }
```

</details>

**Comment by am17an** [comment]
@TinyServal thanks, could you post one with GGML_CUDA_DISABLE_FUSION=1 also?

**Comment by TinyServal** [comment]
Sure, here's the output with fusion disabled: [logs_nofusion.txt](https://github.com/user-attachments/files/23298608/logs_nofusion.txt)

**Comment by TinyServal** [comment]
@am17an should we keep this one open, or should I file a new issue to track the other crash?

**Comment by IMbackK** [comment]
new issue, it looks like not necessarily the same problem

**Comment by DrVonSinistro** [comment]
For 235B-A22B I usually get 5 to 6.3 t/s gen in row mode and 3.5 to 4.5 in layer mode.

The fix did make row mode work but suspiciously I get 4.5 t/s. 

Writing this in relation to coolestmage that wrote:

«Things are working but performance has tanked.»

**Comment by am17an** [comment]
You can perhaps try the fix mentioned in #16912, namely reverting the llama-graph changes which might affect splits
