### ISSUE TITLE
Eval bug:  ggml_cuda_compute_forward: SOLVE_TRI failed  on ROCm 6.4.3  2 X gfx906 GPU 32Gb - on  Qwen3-Coder-Next

### ISSUE THREAD

**Issue by crysolut** [ggml-org/llama.cpp#19442]
### Name and Version

root@llmback-r643-g906:/opt/build/llama.cpp/build/bin# ./llama-cli --version
ggml_cuda_init: found 2 ROCm devices:
  Device 0: AMD Radeon Graphics, gfx906:sramecc+:xnack- (0x906), VMM: no, Wave Size: 64
  Device 1: AMD Radeon Graphics, gfx906:sramecc+:xnack- (0x906), VMM: no, Wave Size: 64
version: 7972 (e06088da0)
built with Clang 19.0.0 for Linux x86_64

### Operating systems

Linux

### GGML backends

HIP

### Hardware

2xAMD Radeon Instinct Mi50 32 gb
root@llmback-r643-g906:/opt/build/llama.cpp/build/bin# ./llama-bench --list-devices
ggml_cuda_init: found 2 ROCm devices:
  Device 0: AMD Radeon Graphics, gfx906:sramecc+:xnack- (0x906), VMM: no, Wave Size: 64
  Device 1: AMD Radeon Graphics, gfx906:sramecc+:xnack- (0x906), VMM: no, Wave Size: 64
Available devices:
  ROCm0: AMD Radeon Graphics (32752 MiB, 32732 MiB free)
  ROCm1: AMD Radeon Graphics (32752 MiB, 32732 MiB free)

### Models

Qwen3-Coder-Next-80b 

### Problem description & steps to reproduce

build config:
cmake .     -DGGML_HIP=ON     -DCMAKE_HIP_ARCHITECTURES=gfx906     -DAMDGPU_TARGETS=gfx906     -DCMAKE_PREFIX_PATH="/opt/rocm;/opt/rocm/lib/cmake"     -Dhipblas_DIR=/opt/rocm/lib/cmake/hipblas     -DCMAKE_HIP_COMPILER=/opt/rocm/llvm/bin/clang     -B build

cmake --build build --config Release -j $(nproc)

lunch:

./llama-server   -m /opt/models/Qwen3-Coder-Next-MXFP4_MOE.gguf --jinja  --metrics --slots  -fa 1    -c 50000    -n -1  -ngl -1       --host 0.0.0.0   --port 8000

error:
common_init_from_params: warming up the model with an empty run - please wait ... (--no-warmup to disable)
rocBLAS error from hip error code: 'hipErrorInvalidDeviceFunction':98
/opt/build/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:97: ROCm error
ggml_cuda_compute_forward: SOLVE_TRI failed
ROCm error: invalid device function
  current device: 0, in function ggml_cuda_compute_forward at /opt/build/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:2758
  err
[New LWP 260524]
[New LWP 260522]
[New LWP 260521]
[New LWP 260520]
[New LWP 260519]
[New LWP 260518]
[New LWP 260517]
[New LWP 260516]
[New LWP 260515]
[New LWP 260514]
[New LWP 260513]
[New LWP 260512]
[New LWP 260511]
[New LWP 260510]
[New LWP 260509]
[New LWP 260508]
[New LWP 260507]
[New LWP 260506]
[New LWP 260505]
[New LWP 260504]
[New LWP 260503]
[New LWP 260502]
[New LWP 260501]
[New LWP 260500]
[New LWP 260499]
[New LWP 260498]
[New LWP 260497]
[New LWP 260494]

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.ubuntu.com>
Enable debuginfod for this session? (y or [n]) [answered N; input not from terminal]
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x000071aaf7710813 in __GI___wait4 (pid=260525, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
warning: 30	../sysdeps/unix/sysv/linux/wait4.c: No such file or directory
#0  0x000071aaf7710813 in __GI___wait4 (pid=260525, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30	in ../sysdeps/unix/sysv/linux/wait4.c
#1  0x000071aafb56dd26 in ggml_print_backtrace () from libggml-base.so.0
#2  0x000071aafb56df79 in ggml_abort () from libggml-base.so.0
#3  0x000071aaf8000e62 in ggml_cuda_error(char const*, char const*, char const*, int, char const*) () from libggml-hip.so.0
#4  0x000071aaf800aa63 in ggml_cuda_graph_evaluate_and_capture(ggml_backend_cuda_context*, ggml_cgraph*, bool, bool, void const*) () from libggml-hip.so.0
#5  0x000071aaf80063f1 in ggml_backend_cuda_graph_compute(ggml_backend*, ggml_cgraph*) () from libggml-hip.so.0
#6  0x000071aafb58d0bd in ggml_backend_sched_graph_compute_async () from libggml-base.so.0
#7  0x000071aafb30b811 in llama_context::graph_compute(ggml_cgraph*, bool) () from libllama.so.0
#8  0x000071aafb30b397 in llama_context::process_ubatch(llama_ubatch const&, llm_graph_type, llama_memory_context_i*, ggml_status&) () from libllama.so.0
#9  0x000071aafb30cb61 in llama_context::decode(llama_batch const&) () from libllama.so.0
#10 0x000071aafb31162b in llama_decode () from libllama.so.0
#11 0x0000000000554290 in common_init_from_params(common_params&) ()
#12 0x000000000039453a in server_context_impl::load_model(common_params const&) ()
#13 0x00000000002db107 in main ()
[Inferior 1 (process 260493) detached]
Aborted

### Relevant log output

<details>
<summary>Logs</summary>

```console

```
</details>

**Comment by matalama80td3l** [comment]
I'm on a single mi50 and I have the same error with ROCm 7.0.2. I think this error may related to all models using linear attention because Qwen-3 Next series and Kimi Linear all report this error on my machine.

**Comment by am17an** [comment]
@IMbackK if you access to hardware, could you please look at this?

**Comment by crysolut** [comment]
I can provide remote access to a container with 2 gfx906

**Comment by IMbackK** [comment]
I cant reproduce this on gfx908, thats not a surprise since the problem is likely in rocblas_strsm_batched and gfx908 has a unrelated solution pool.

@crysolut, @matalama80td3l you recompiled rocblas/tensile with gfx906 enabled right or are using 3rd party distro packages with gfx906 tensile objects? Since amd has not compiled rocblas for gfx906 since rocm 6.3.

**Comment by crysolut** [comment]
These components are either compiled by the ArchLinux team or come from earlier versions of RocBlas. Do you recommend rolling back RocBlas to earlier versions? I'll do that and get back to you with a report.

**Comment by crysolut** [comment]
The fact is, more recent ROCM builds provide a significant performance boost on GFX906 cards. Mi50 cards, especially those with 32GB of memory, are very popular among enthusiasts because they're very affordable and offer generation performance comparable to the GFX908, with a slight weakness in prompt processing. A model like the QWEN CODER NEXT, comparable in speed to the 30B but significantly more powerful, is a must-have for these accelerators. It's practically a killer model for them, as it fits on two cards. I'll conduct tests with earlier ROCM versions, and if the model launches and performance drops significantly, the entire GFX906 community, represented by me, will beg you to pay attention to this issue.

**Comment by IMbackK** [comment]
> These components are either compiled by the ArchLinux team or come from earlier versions of RocBlas. Do you recommend rolling back RocBlas to earlier versions? I'll do that and get back to you with a report.

that thats invalid, tensile dosent have a stable abi at all, in fact its violently unstable with symbol names generated by a python script at build time, you cant mix different builds like that.
The only valid way to generate those files is to build rocblas from scratch with gfx906 enabled and then use the resulting tensile and rocblas files together.

Without this being reproduced on a non-frankenstein build of rocm there is nothing more for us to do here - nor are we able to report upstream where the issue would lie otherwise if its not tensile abi related.

**Comment by IMbackK** [comment]
if you dont want to build rocm yourself for your architecture i would recommend trying in an arch linux container.

**Comment by crysolut** [comment]
To start, I'll launch a container with 6.3 where the gfx906 cores are still compiled by AMD itself. Please don't close this issue yet, I'll try to provide the data quickly

**Comment by crysolut** [comment]
Okay, you were absolutely right, it was a Frankenstein issue. After building on rocm 6.3.4, the error disappeared. There was a slight performance drop of 4-5% on two cards, and on one card, performance remained unchanged. For me, the issue is closed, thank you for your help getting the model running. The model outputs about 35 tokens in MXFP4 quantization, which is significantly slower than 30B, but it's something to work with.


main: model loaded
main: server is listening on http://0.0.0.0:8000
main: starting the main loop...
srv  update_slots: all slots are idle

;)

**Comment by IMbackK** [comment]
Ok, great.
There could still be an issue here: that there is a regression in a later version of rocblas. If so, we could report this upstream with a short reproducer, the rocblas team has been receptive to fixing issues on unsupported devices in the past - so this could be valuable. 
To do this you could try an arch linux docker and install rocm 7.2 there as the version in arch linuxes repos is built for gfx906.

Im going to close this issue, as its not a problem in llamacpp, but feel free to continue posting here if you want my help attempting to reproduce the potential upstream issue.

**Comment by crysolut** [comment]
Thanks! I'll move on, first the Arch container, then TheRock build.

**Comment by jhstatewide** [comment]
I wanted to add one more data point before this is fully considered closed: I can still reproduce the failure on my MI50 setup (`gfx906`, ROCm `7.0.2`, Ubuntu `24.04.3`, kernel `6.17.0-14-generic`) on llama.cpp commit `9a9635272`.

Error path is still `GGML_OP_SOLVE_TRI` with `hipErrorInvalidDeviceFunction` in the HIP route for Qwen3-Next-like shapes (`n=64, k=64`).

Suspected cause (from local debugging)
- In `ggml/src/ggml-cuda/solve_tri.cu`, the custom fast kernel is used only for `k <= 32`.
- For larger RHS widths (`k > 32`), `solve_tri` falls back to batched TRSM (`cublasStrsmBatched`, HIP-mapped on ROCm).
- Qwen3-Next commonly triggers `solve_tri` with `n=64, k=64` (via chunk size 64 path), so it enters that fallback route.
- On my MI50/gfx906 + ROCm 7.0.2 environment, that route fails at runtime with `hipErrorInvalidDeviceFunction`.
- The attached patch avoids that fallback for this shape class by tiling RHS columns into <=32 chunks and reusing the existing fast kernel path.

I may be wrong on exact HIP/rocBLAS internals, but this behavior has been reproducible in my environment.

I attached a local workaround patch that tiles the RHS (`<=32` columns) and avoids the failing HIP BLAS route in this case. I’ve been using that patch for several days without seeing the crash.

Not trying to push a specific implementation choice here, only sharing a reproducible report + a tested workaround in case it helps triage. If you prefer, I can also test any maintainer-proposed alternative on this hardware.

[mi50_solve_tri_fix_main.patch](https://github.com/user-attachments/files/25215350/mi50_solve_tri_fix_main.patch)

**Comment by crysolut** [comment]
> Ok, great. There could still be an issue here: that there is a regression in a later version of rocblas. If so, we could report this upstream with a short reproducer, the rocblas team has been receptive to fixing issues on unsupported devices in the past - so this could be valuable. To do this you could try an arch linux docker and install rocm 7.2 there as the version in arch linuxes repos is built for gfx906.
> 
> Im going to close this issue, as its not a problem in llamacpp, but feel free to continue posting here if you want my help attempting to reproduce the potential upstream issue.

Hello! Perhaps you should take a look at the patch in the previous post? It solves this problem.

**Comment by AlphaUrsaeMinoris** [comment]
I have the same hardware and a similar frankenstein rocm build to crysolut and the patch solved the issue for me without changing my rocm. So thank you for the intermediate fix, until I have the time to fix my rocm situation!

**Comment by IMbackK** [comment]
Its not a valid patch, the patch simply avoids using rocblas in this case. You are simply sweeping the fact that your rocblas installation is fundamentally broken under the rug, it **will** bite you again somewhere else.

**Comment by crysolut** [comment]
> Its not a valid patch, the patch simply avoids using rocblas in this case. You are simply sweeping the fact that your rocblas installation is fundamentally broken under the rug, it **will** bite you again somewhere else.

Have you tried this model on your GFX908? Can you run it using an OpenCode-like agent? What's the performance like on these GPUs? Compared to the Qw3-coder 30B, is there a performance drop on Next, and does it crash when working with context? The problem is, even on a supported build with ROCKM 634, this model is impossible to run. It constantly segfaults.

**Comment by zeus** [comment]
> Okay, you were absolutely right, it was a Frankenstein issue. After building on rocm 6.3.4, the error disappeared. There was a slight performance drop of 4-5% on two cards, and on one card, performance remained unchanged. For me, the issue is closed, thank you for your help getting the model running. The model outputs about 35 tokens in MXFP4 quantization, which is significantly slower than 30B, but it's something to work with.
> 
> main: model loaded main: server is listening on http://0.0.0.0:8000 main: starting the main loop... srv update_slots: all slots are idle
> 
> ;)

Can you please provide Dockerfile to build llama-cpp with rocm 6.3.4?

**Comment by CoreRasurae** [comment]
I will build robblas for ROCm 7.2.0 and confirm if it works or not. i am using compiled binaries from Arch but from the same ROCm 7.2.0. i will compile it from scratch and leave a feedback here.

**Comment by thejacer** [comment]
Built a docker container with Arch Linux, installed ROCm using pacman, compiled llama.cpp with gfx906 and Qwen3.5 35b ran perfect.

**Comment by zeus** [comment]
> Built a docker container with Arch Linux, installed ROCm using pacman, compiled llama.cpp with gfx906 and Qwen3.5 35b ran perfect.

Can you share Dockerfile?

**Comment by thejacer** [comment]
Full disclosure, Gemini provided all of this. I also see that the AMDGPU_TARGETS appears in both the Dockerfile and docker-compose.yml. In the Dockerfile Gemini provied a list of targets while in the compose it had just gfx906. But since I don't know what I'm doing really I reduced the list in the Dockerfile to just gfx906. Hopefully you're able to use this and pasting this here isn't totally inappropriate.

Dockerfile
```
FROM archlinux:base-devel

# Update the system and install necessary ROCm dependencies, Git, and CMake
RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm git cmake python rocm-hip-sdk rocblas hipblas

WORKDIR /app

# Clone the official llama.cpp repository
RUN git clone https://github.com/ggml-org/llama.cpp.git .

ARG AMDGPU_TARGETS="gfx906"

# ------------------------------------------------------------------
# THE FIX: Explicitly set Arch Linux ROCm paths so CMake can find it
# ------------------------------------------------------------------
ENV ROCM_PATH=/opt/rocm
ENV HIP_PATH=/opt/rocm
ENV PATH="/opt/rocm/bin:${PATH}"
ENV LD_LIBRARY_PATH="/opt/rocm/lib:${LD_LIBRARY_PATH}"

# Configure and compile llama.cpp.
# We use `hipconfig` to explicitly pass the AMD Clang compiler to CMake.
RUN HIPCXX="$(hipconfig -l)/clang" HIP_PATH="$(hipconfig -R)" \
    cmake -B build \
    -DGGML_HIP=ON \
    -DAMDGPU_TARGETS="${AMDGPU_TARGETS}" \
    -DCMAKE_BUILD_TYPE=Release \
    && cmake --build build --config Release -j$(nproc)

EXPOSE 8080

ENTRYPOINT ["/app/build/bin/llama-server"]
```

docker-compose.yml
```
# docker-compose.yml
services:
  llama-cpp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Update this if you are using a very specific AMD architecture
        - AMDGPU_TARGETS=gfx906
    image: llama-cpp-arch-rocm:latest
    container_name: llama-rocm-server
    restart: unless-stopped
    ports:
      - "8080:8080"

    # CRITICAL: Pass the AMD GPU kernel interfaces to the container
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri

    # Required for the container user to access the GPU devices
    group_add:
      - video
      - render

    # Mount the local models folder to /models inside the container
    volumes:
      - /home/thejacer/DS08002:/models

    # The default command arguments sent to llama-server
    # -m: path to your GGUF model
    # --host 0.0.0.0: binds to all interfaces so you can access it outside the container
    # -ngl 99: offloads layers to the GPU (99 forces all layers for maximum speed)
    command: >
      -m /models/Qwen3.5-35B-A3B-UD-Q4_K_XL.gguf
      --host 0.0.0.0
      --port 8080
      -ngl 99
      --mmproj /models/mmproj_Qwen3_5-F32.gguf
      --no-mmap
      -fa on
```

**Comment by issuj** [comment]
Re. building ROCm, I discovered that TheRock's [nightly builds](https://rocm.nightlies.amd.com/tarball/) include a build for gfx906 (link is on https://github.com/ROCm/TheRock/blob/main/RELEASES.md). I managed to build a llamacpp with 7.12 nightly ROCm that works with qwen 3.5 models.

Of course it's not a stable release so YMMV.

**Comment by jhstatewide** [comment]
> Of course it's not a stable release so YMMV.

Thanks for the tip. I will keep my eye on it to try it when it is stable. Good to know this hardware still has a bit of life left in it after all, thanks to the community, and not AMD :)
