### ISSUE TITLE
Misc. bug: Device Lost on Intel dGPU using Vulkan backend

### ISSUE THREAD

**Issue by rillomas** [ggml-org/llama.cpp#22034]
### Name and Version

λ llama-cli.exe --version
version: 8827 (5e6c0e18b)
built with MSVC 19.50.35728.0 for x64

### Operating systems

Windows

### Which llama.cpp modules do you know to be affected?

Vulkan backend

### Command line

```shell
llama-bench.exe -m Qwen3-30B-A3B-Instruct-2507-Q4_K_M.gguf -n 0 -b 32 -ub 32
```

### Problem description & steps to reproduce
I was trying to benchmark the smaller warptile pipelines (`*aligned_s` pipelines) when I found this. Reproduction is 100% when running llama-bench but may not occur on llama-cli and llama-completion.

1. [Download model](https://huggingface.co/unsloth/Qwen3-30B-A3B-Instruct-2507-GGUF/blob/main/Qwen3-30B-A3B-Instruct-2507-Q4_K_M.gguf)
2. Execute `llama-bench.exe -m Qwen3-30B-A3B-Instruct-2507-Q4_K_M.gguf -n 0 -b 32 -ub 32` . `llama-bench.exe -m Qwen3-30B-A3B-Instruct-2507-Q4_K_M.gguf -n 0` does **not** crash on the same environment

#### Environment
- i9-13900K + Arc B580, Graphics driver 32.0.101.8724, 32GB RAM 5600MT, Win 11 24H2 10.0.26100.8246

### First Bad Commit

Unknown

### Relevant log output

<details>
<summary>Logs (Vulkan Validation ON)</summary>

```console
λ build_vk_validation\bin\Release\llama-bench.exe -m ../../Qwen3-30B-A3B-Instruct-2507-Q4_K_M.gguf -n 0 -b 32 -ub 32
ggml_vulkan: Found 1 Vulkan devices:
ggml_vulkan: 0 = Intel(R) Arc(TM) B580 Graphics (Intel Corporation) | uma: 0 | fp16: 1 | bf16: 0 | warp size: 32 | shared memory: 49152 | int dot: 1 | matrix cores: KHR_coopmat
| model                          |       size |     params | backend    | ngl | n_batch | n_ubatch |            test |                  t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ------: | -------: | --------------: | -------------------: |
Validation Warning: [ BestPractices-deprecated-extension ] | MessageID = 0xda8260ba
vkCreateDevice(): Attempting to enable deprecated extension VK_EXT_pipeline_robustness, but this extension has been promoted to 1.4.0 (0x00404000).
Objects: 1
    [0] VkInstance 0x1b3a5ead980

Validation Warning: [ BestPractices-deprecated-extension ] | MessageID = 0xda8260ba
vkCreateDevice(): Attempting to enable deprecated extension VK_KHR_maintenance4, but this extension has been promoted to 1.3.0 (0x00403000).
Objects: 1
    [0] VkInstance 0x1b3a5ead980

Validation Warning: [ BestPractices-deprecated-extension ] | MessageID = 0xda8260ba
vkCreateDevice(): Attempting to enable deprecated extension VK_KHR_shader_integer_dot_product, but this extension has been promoted to 1.3.0 (0x00403000).
Objects: 1
    [0] VkInstance 0x1b3a5ead980

Validation Warning: [ BestPractices-specialuse-extension ] | MessageID = 0x675dc32e
vkCreateDevice(): Attempting to enable extension VK_KHR_pipeline_executable_properties, but this extension is intended to support developer tools such as capture-replay libraries and it is strongly recommended that it be otherwise avoided.
Objects: 1
    [0] VkInstance 0x1b3a5ead980

Validation Warning: [ BestPractices-deprecated-extension ] | MessageID = 0xda8260ba
vkCreateDevice(): Attempting to enable deprecated extension VK_EXT_subgroup_size_control, but this extension has been promoted to 1.3.0 (0x00403000).
Objects: 1
    [0] VkInstance 0x1b3a5ead980

Validation Warning: [ BestPractices-deprecated-extension ] | MessageID = 0xda8260ba
vkCreateDevice(): Attempting to enable deprecated extension VK_KHR_16bit_storage, but this extension has been promoted to 1.1.0 (0x00401000).
Objects: 1
    [0] VkInstance 0x1b3a5ead980

Validation Warning: [ BestPractices-deprecated-extension ] | MessageID = 0xda8260ba
vkCreateDevice(): Attempting to enable deprecated extension VK_KHR_shader_non_semantic_info, but this extension has been promoted to 1.3.0 (0x00403000).
Objects: 1
    [0] VkInstance 0x1b3a5ead980

Validation Warning: [ BestPractices-deprecated-extension ] | MessageID = 0xda8260ba
vkCreateDevice(): Attempting to enable deprecated extension VK_KHR_shader_float16_int8, but this extension has been promoted to 1.2.0 (0x00402000).
Objects: 1
    [0] VkInstance 0x1b3a5ead980

Validation Warning: [ BestPractices-SpirvDeprecated_WorkgroupSize ] | MessageID = 0xd8a870c
vkCreateComputePipelines(): pCreateInfos[0].stage is using the SPIR-V Workgroup built-in which SPIR-V 1.6 deprecated. When using VK_KHR_maintenance4 or Vulkan 1.3+, the new SPIR-V LocalSizeId execution mode should be used instead. This can be done by recompiling your shader and targeting Vulkan 1.3+.

Validation Warning: [ BestPractices-SpirvDeprecated_WorkgroupSize ] | MessageID = 0xd8a870c
vkCreateComputePipelines(): pCreateInfos[0].stage is using the SPIR-V Workgroup built-in which SPIR-V 1.6 deprecated. When using VK_KHR_maintenance4 or Vulkan 1.3+, the new SPIR-V LocalSizeId execution mode should be used instead. This can be done by recompiling your shader and targeting Vulkan 1.3+.

Validation Warning: [ BestPractices-SpirvDeprecated_WorkgroupSize ] | MessageID = 0xd8a870c
vkCreateComputePipelines(): pCreateInfos[0].stage is using the SPIR-V Workgroup built-in which SPIR-V 1.6 deprecated. When using VK_KHR_maintenance4 or Vulkan 1.3+, the new SPIR-V LocalSizeId execution mode should be used instead. This can be done by recompiling your shader and targeting Vulkan 1.3+.

Validation Warning: [ BestPractices-SpirvDeprecated_WorkgroupSize ] | MessageID = 0xd8a870c
vkCreateComputePipelines(): pCreateInfos[0].stage is using the SPIR-V Workgroup built-in which SPIR-V 1.6 deprecated. When using VK_KHR_maintenance4 or Vulkan 1.3+, the new SPIR-V LocalSizeId execution mode should be used instead. This can be done by recompiling your shader and targeting Vulkan 1.3+.

Validation Warning: [ BestPractices-SpirvDeprecated_WorkgroupSize ] | MessageID = 0xd8a870c
vkCreateComputePipelines(): pCreateInfos[0].stage is using the SPIR-V Workgroup built-in which SPIR-V 1.6 deprecated. When using VK_KHR_maintenance4 or Vulkan 1.3+, the new SPIR-V LocalSizeId execution mode should be used instead. This can be done by recompiling your shader and targeting Vulkan 1.3+.

Validation Warning: [ BestPractices-SpirvDeprecated_WorkgroupSize ] | MessageID = 0xd8a870c
vkCreateComputePipelines(): pCreateInfos[0].stage is using the SPIR-V Workgroup built-in which SPIR-V 1.6 deprecated. When using VK_KHR_maintenance4 or Vulkan 1.3+, the new SPIR-V LocalSizeId execution mode should be used instead. This can be done by recompiling your shader and targeting Vulkan 1.3+.

Validation Warning: [ BestPractices-SpirvDeprecated_WorkgroupSize ] | MessageID = 0xd8a870c
vkCreateComputePipelines(): pCreateInfos[0].stage is using the SPIR-V Workgroup built-in which SPIR-V 1.6 deprecated. When using VK_KHR_maintenance4 or Vulkan 1.3+, the new SPIR-V LocalSizeId execution mode should be used instead. This can be done by recompiling your shader and targeting Vulkan 1.3+.

Validation Warning: [ BestPractices-SpirvDeprecated_WorkgroupSize ] | MessageID = 0xd8a870c
vkCreateComputePipelines(): pCreateInfos[0].stage is using the SPIR-V Workgroup built-in which SPIR-V 1.6 deprecated. When using VK_KHR_maintenance4 or Vulkan 1.3+, the new SPIR-V LocalSizeId execution mode should be used instead. This can be done by recompiling your shader and targeting Vulkan 1.3+.

Validation Warning: [ BestPractices-SpirvDeprecated_WorkgroupSize ] | MessageID = 0xd8a870c
vkCreateComputePipelines(): pCreateInfos[0].stage is using the SPIR-V Workgroup built-in which SPIR-V 1.6 deprecated. When using VK_KHR_maintenance4 or Vulkan 1.3+, the new SPIR-V LocalSizeId execution mode should be used instead. This can be done by recompiling your shader and targeting Vulkan 1.3+.

Validation Warning: [ BestPractices-SpirvDeprecated_WorkgroupSize ] | MessageID = 0xd8a870c
(Warning - This VUID has now been reported 10 times, which is the duplicated_message_limit value, this will be the last time reporting it).
vkCreateComputePipelines(): pCreateInfos[0].stage is using the SPIR-V Workgroup built-in which SPIR-V 1.6 deprecated. When using VK_KHR_maintenance4 or Vulkan 1.3+, the new SPIR-V LocalSizeId execution mode should be used instead. This can be done by recompiling your shader and targeting Vulkan 1.3+.

Validation Warning: [ BestPractices-Error-Result ] | MessageID = 0x53c1342f
vkGetFenceStatus(): Returned error VK_ERROR_DEVICE_LOST.
```
</details>

**Comment by mamama1** [comment]
Also experiencing this on Intel Arc Pro B70 (Windows Server 2022)

Running into intermittent VK_ERROR_DEVICE_LOST / full system hang on Vulkan with Intel Arc Pro B70 on Windows Server 2022

Setup:

GPU: Intel Arc Pro B70 (32 GB)
OS: Windows Server 2022
Driver version: 32.0.101.8515
llama.cpp build: b8850-4eac5b450 (self-built)
Model: Qwen3-Coder-30B-A3B-Instruct-Q4_K_M.gguf (Q4_K_M, MoE architecture, 30B/3B active)
Vulkan SDK version: 1.4.341.1

Symptoms:
Crash is intermittent - several prompts complete successfully, then the process hard-crashes (and takes the VM with it on Proxmox) although it depends on the parameters a bit. flash attention and context quant seems to make it trigger faster.

TDR is disabled (TdrLevel=0 in registry) - crash still occurs

graph splits = 2 visible in startup log

Flash attention enabled (-fa on)

Key observation: Build b8555 (the version shipped with Intel AI Playground) does not exhibit this crash on identical hardware with the same model. The regression appears somewhere between b8555 and b8850.

cmake flags used for b8850 build:

> -DGGML_NATIVE=OFF -DGGML_VULKAN=ON -DLLAMA_BUILD_TESTS=OFF
> -DGGML_BACKEND_DL=ON -DGGML_CPU_ALL_VARIANTS=ON
> -DGGML_VULKAN_COOPMAT=OFF -DGGML_VULKAN_COOPMAT2=OFF

(coopmat explicitly disabled - crash persists regardless)

Startup log excerpt showing the crash context:

> sched_reserve: graph splits = 2
> llama_context: flash_attn    = enabled

[crash occurs mid-inference with no error output system just freezes completely]

Happy to provide additional logs or test specific builds/flags if it helps narrow down the regression.

edit:
apparently, this has fixed it:
```
set GGML_VK_DISABLE_COOPMAT=1
set GGML_VK_DISABLE_COOPMAT2=1
```

no more freezes...

**Comment by rillomas** [comment]
Thanks for the info. Disabling coopmat with `set GGML_VK_DISABLE_COOPMAT=1` does actually work on my case as well, so probably an issue in the coopmat shader or the driver. I'll see if I can look deeper.

Update: So far I've confirmed that the crash happens when running the following two pipelines in MUL_MAT operator. The number of calls required for crashing is random (sometimes it doesn't crash) so possibly a race condition within these shaders?

```
matmul_q4_k_f32_f16acc_aligned_s
matmul_q6_k_f32_f16acc_aligned_s
```

Update2: Seems like device lost occurs on other pipelines as well, so likely a compiler/driver issue. Currently checking internally.

**Comment by tbsecurity29** [comment]
Adding a data point from an Arc Pro B70 on a newer driver and build — this still reproduces, and I'm seeing it surface as a host-side STATUS_STACK_BUFFER_OVERRUN rather than "Device Lost," which may be the same coopmat bug manifesting through a second fault path.
Environment

Build: b9245 (b39a7bf1b), Clang 19.1.5, Windows x86_64
GPU: Intel Arc Pro B70 (Vulkan0, 32 GB); AMD Radeon iGPU at Vulkan1 (not targeted)
Driver: 32.0.101.8737 (2026-04-28), DRIVER_ID_INTEL_PROPRIETARY_WINDOWS — newer than the .8724 reported above, still broken
Vulkan: Instance 1.4.313, device 1.4.344; VK_KHR_cooperative_matrix rev 2, cooperativeMatrix=true, cooperativeMatrixRobustBufferAccess=true; no VK_NV_cooperative_matrix2 (so this is the KHR coopmat path)

Symptom (host-side, complements the "Device Lost" reports)
Crash fires ~15–28 s after launch, mid-decode (passes warmup; no generation output):
Faulting module: ucrtbase.dll, version 10.0.26100.8521
Exception code:  0xc0000409  (STATUS_STACK_BUFFER_OVERRUN)
Fault offset:    0x00000000000a527e
Bucket:          BEX64
The fault offset 0xa527e is identical across every crash and across two different models.
Server-free repro (llama-cli, no server, ~80%):
:: coopmat ENABLED (env vars unset)
llama-cli.exe -m Qwen3-32B-Q4_K_M.gguf -p "<any prompt>" -n 200 -ngl 999 --device Vulkan0 -no-cnv

Qwen3-32B Q4_K_M: 4/5 crash
Hermes-35B-A3B (Qwen3.5 MoE) Q4_K_M: 2/5 crash, same 0xa527e offset → not model-specific
llama-server (10 chat requests) did not reproduce for me this session — consistent with the reported intermittency / "may not occur on llama-cli"

Workaround confirmed: GGML_VK_DISABLE_COOPMAT=1 + GGML_VK_DISABLE_COOPMAT2=1 → same config ran 4/4 clean. (Cost on this card: ~12 tok/s vs ~17–22 with coopmat on.)
Happy to run anything that would help narrow it — a debug/validation-layer build, GGML_VULKAN_CHECK_RESULTS, or specific shader toggles.

**Comment by TomTheHand** [comment]
# Intel Arc B60 — Vulkan MoE `VK_ERROR_DEVICE_LOST` confirmed + workaround (`GGML_VK_DISABLE_COOPMAT=1`)

## Environment

| Item | Details |
|---|---|
| GPU | Intel Arc B60 (BMG-G21), 24 GB VRAM |
| Driver | 32.0.101.6870 (Intel Arc Control reports 1.13.684.081) |
| OS | Windows 11 24H2 (Build 22631) |
| llama.cpp | Official prebuilt release `b9196`, build `9592 (ac4cdde)` |
| Backend | Vulkan |

## Models tested

| Model | Quant | Size | MoE experts |
|---|---|---|---|
| Qwen3.6-35B-A3B (Heretic/MTP variant) | `IQ3_M` | ~15 GB | 40 active / 64 total |
| Qwen3.6-28B-REAP (20% expert prune) | `Q4_K_M` | ~17.3 GB | 32 active / 64 total |

## Reproduction on official release binary

Both models crash with `VK_ERROR_DEVICE_LOST` using the **stock release binary** — no custom build, no debug hooks.

### IQ3_M (35B)
- Launch params: `--ctx-size 262144 --cache-type-k q8_0 --cache-type-v q8_0 --kv-unified --flash-attn on --parallel 1 --n-gpu-layers 9999 --verbose`
- Result: **Crashed on the first inference request** (exit code 1)
- Server loads, reports healthy, processes one prompt batch, then dies mid-decode

### Q4_K_M REAP (28B)
- Same launch params
- Result: Survived one simple request, **crashed on the second** (longer prompt, more MoE expert activation)
- Exit code 1, no explicit Vulkan error in log — process just terminates

### Key observation
IQ3_M crashes *faster* than Q4_K_M. Both crash. The bug is not quant-specific.

## Workaround: `GGML_VK_DISABLE_COOPMAT=1`

Setting `GGML_VK_DISABLE_COOPMAT=1` **completely eliminates the crash** on both models, same official binary.

### Stability test results (IQ3_M, no-coopmat)

| Test | Concurrent workers | Total requests | OK | Fail | Timeout | Duration |
|---|---|---|---|---|---|---|
| Warmup | 1 | 3 | 3 | 0 | 0 | ~30s |
| Chaos round 1 | 3 | 18 | 18 | 0 | 0 | ~98s |
| Chaos round 2 | 4 | 40 | 40 | 0 | 0 | ~236s |
| **Total** | — | **61** | **61** | **0** | **0** | ~6 min |

Chaos tests used varied prompt sizes (short one-liners to 500-word essay requests), random temperatures, and concurrent workers hitting different MoE expert pathways.

### Performance (no-coopmat, IQ3_M)
- Completion throughput: **~66 tok/s** average
- Prompt processing: **~56 tok/s** average (varies with prompt length and concurrency)
- Usable and stable for sustained serving.

## Additional diagnosis (custom debug build)

After confirming the bug on the release binary, I built from source (`d73cd07`) with symbols to dig deeper.

### `--cpu-moe` survives, all-GPU crashes

With `--cpu-moe` (MoE expert computation on CPU, everything else GPU): survived the same chaos pattern until manually stopped.

With all-GPU (default): crashed consistently within 1–2 requests.

This confirms the crash is in GPU-side MoE expert computation, not in attention, KV management, or general Vulkan infrastructure.

### Crash stack (CDB / WinDbg)

```
vk::detail::throwResultException  (throws VK_ERROR_DEVICE_LOST)
vk::Device::getFenceStatus
ggml_vk_wait_for_fence
ggml_vk_synchronize
ggml_backend_vk_synchronize
ggml_backend_sched_compute_splits
server_context_impl::update_slots
```

The fence wait is where device loss is *detected*, not necessarily where it is *caused*. The actual GPU fault occurs earlier in the submission pipeline.

### Shader/kernel correlation

Debug logging identifies the failing operation family:
- Op: `MUL_MAT_ID` (MoE expert matmul)
- Shaders: `mul_mat_vec_id_iq3_s_f32`, `mul_mat_vec_id_q4_k_q8_1_f32`
- Dispatch name: `matmul_id_subgroup_iq3_s_f32_f16acc_aligned_l`
- Tensors: `ffn_moe_up` / `ffn_moe_down` (the MoE feed-forward layers)

### Expert-ID bounds guard did not fix it

I patched `ggml-vulkan.cpp` and `mul_mat_vec_base.glsl` to pass `n_experts` as a push constant, validate expert IDs against `n_experts`, and clamp out-of-bounds IDs to expert 0. **The crash still occurred.** Invalid expert IDs / simple `data_ids` OOB are not the sole (or root) cause.

### Other axes ruled out

| Axis tested | Result |
|---|---|
| `--ctx-checkpoints 0` | Crashed faster |
| `--no-kv-unified` | Crashed immediately |
| `--parallel 1` (serial) | Still crashed |
| `--batch-size 2048 --ubatch-size 512` | Still crashed |
| Expert-ID guard/clamp patch | Still crashed |

## Cross-reference

- **#22034** (this issue) — Same crash on Arc B580 with Qwen3-30B-A3B Q4_K_M.
- **#20554** — `GGML_VK_DISABLE_COOPMAT=1` resolved GPU TDR on Intel Arc 140V iGPU. The same workaround works here on Arc B60 dGPU.
- **#22275** — Arc Pro B70, different manifestation (silent exit during prompt_save with large KV state), but also Intel Arc + Vulkan.

## Hypothesis

The `VK_KHR_cooperative_matrix` implementation on Intel Arc (Battlemage and possibly Alchemist/Xe2-LPG) produces a GPU fault when used by llama.cpp's `MUL_MAT_ID` / `mul_mat_vec_id` shader family during MoE expert matmuls. Disabling cooperative matrix forces a fallback path that is stable.

The fact that `--cpu-moe` survives and the crash correlates with `MUL_MAT_ID` / MoE-specific shaders (not attention or KV shaders) further narrows the scope.

## Crash dumps available

I have full process dumps (~17.6 GB) from the custom debug build crash. Happy to provide smaller minidumps or specific analysis on request — the full dump is too large to attach directly.

## Summary

- ✅ Reproduced on official release binary (no custom build artifacts)
- ✅ Reproduced on two different quants (IQ3_M and Q4_K_M)
- ✅ `GGML_VK_DISABLE_COOPMAT=1` is a clean workaround (61/61 requests, zero failures)
- ✅ `--cpu-moe` survives, confirming GPU-side MoE as the crash locus
- ✅ Crash is in `MUL_MAT_ID` / cooperative matrix shaders, not expert-ID OOB
- ✅ Consistent with #20554 (Arc 140V TDR fix via same workaround)

**Comment by rillomas** [comment]
This is fixed with latest graphics driver [32.0.101.8860](https://www.intel.com/content/www/us/en/download/785597/intel-arc-graphics-windows.html)

**Comment by bishopkennedy39-ops** [comment]
Thanks for the update and confirmation. I upgraded to driver 32.0.101.8860
and can confirm the issue no longer reproduces on my setup. The previous
VK_ERROR_DEVICE_LOST crashes with cooperative matrix enabled appear to be
resolved with this driver version.

**Comment by TomTheHand** [comment]
For anyone wanting to run Arc Pro drivers (B60/B70/whatever), the slightly older, Arc Pro-targeted 32.0.101.8804 _also_ seems to have the issue resolved.
