### ISSUE TITLE
Gemma 4 31B: illegal memory access after SWA KV cache checkpoint with Flash Attention enabled

### ISSUE THREAD

**Issue by Xuan-GUo** [ggml-org/llama.cpp#22527]
Body:
Environment:

OS: Windows 10 26200.7462
GPU: NVIDIA GeForce RTX 4060 Ti (16GB VRAM)
Driver: 596.36 / CUDA 13.2
llama.cpp build: b8975-59237bfbb (compiled with MSVC 19.42.34436.0, GGML_CUDA_GRAPHS=OFF)

Model:

gemma-4-31B-it-heretic.i1-IQ3_XXS.gguf (Gemma 4 31B, IQ3_XXS quantization, 11.23 GiB)

Command:
bashllama-server -m gemma-4-31B-it-heretic.i1-IQ3_XXS.gguf --port 8080 -b 512 -ub 512 -c 10240 -ngl 99 --flash-attn on -ctk f16 -ctv f16 --threads 6 --jinja -np 1 --cache-ram 0
Describe the bug:
The server crashes with CUDA error: an illegal memory access was encountered consistently after the second SWA KV cache context checkpoint is created, during the first completion request. The crash occurs every time without exception, regardless of prompt content.
The crash always happens at:
C:\Users\User\llama.cpp\ggml\src\ggml-cuda\ggml-cuda.cu:3083
current device: 0, in function ggml_backend_cuda_synchronize
cudaStreamSynchronize(cuda_ctx->stream())
Observed pattern:
The server always crashes immediately after these two log lines appear:
slot create_check: id  0 | task 0 | created context checkpoint 1 of 32 (pos_min = 2364, pos_max = 3899, n_tokens = 3900, size = 1200.019 MiB)
slot create_check: id  0 | task 0 | created context checkpoint 2 of 32 (pos_min = 2872, pos_max = 4407, n_tokens = 4408, size = 1200.019 MiB)
Note that the SWA KV cache is always 1200 MiB regardless of context size:
llama_kv_cache: size = 1200.00 MiB (1536 cells, 50 layers, 1/1 seqs)
Things tried (all failed):

Disabling Flash Attention (--flash-attn off) → server fails to allocate VRAM due to V cache padding for mismatched layer sizes
Reducing context size (-c 8192, -c 6144, -c 10240) → same crash
Adding --cache-ram 0 → crash delayed by ~2 turns but still occurs
Disabling CUDA Graphs (GGML_CUDA_GRAPHS=OFF) → same crash
Using q8_0 KV cache with Flash Attention off → OOM due to V cache padding

Additional notes:
This model uses a mixed SWA + Full Attention architecture (Gemma 4 specific). The non-SWA layers use n_embd_head_k = 512 while SWA layers use n_embd_head_k_swa = 256. When Flash Attention is disabled, llama.cpp pads the V cache to the maximum size across all layers, causing excessive VRAM usage. When Flash Attention is enabled, the server crashes after the SWA checkpoint.

**Comment by arie-s** [comment]
Possibly related (same head-512 root cause), reporting in case it helps: on **Gemma 4 31B with `draft-mtp` speculative decoding** + flash-attn + q8_0 KV cache + `--split-mode tensor`, I get a hard `GGML_ABORT("fatal error")` in `ggml_cuda_flash_attn_ext` — a clean abort rather than an illegal access.

Backtrace (top frames):
```
ggml_abort
ggml_cuda_flash_attn_ext
ggml_backend_cuda_graph_compute
...
llama_decode
common_speculative_impl_draft_mtp::draft(...)
server_context_impl::update_slots()
```

Root cause: `ggml_cuda_get_best_fattn_kernel()` returns `BEST_FATTN_KERNEL_NONE` for the head-dim-512 full-attention layers when `gqa_opt_applies == false`. The main-model decode always reaches these layers with `gqa_opt_applies == true` (→ MMA), but the **MTP draft decode** can present the same 512/512 layer with `gqa_opt_applies == false`, for which no kernel exists → abort. (Hard to hit on demand — `K->ne[1]` is usually padded to a multiple of `FATTN_KQ_STRIDE`.)

Build: master `f0156d140` (b9550), CUDA 12.8, sm_89, 2×16GB.

Local fix that resolves it for me with no observed regression (gated on head==512, so Qwen and other models are untouched):
- route head-512 + non-gqa to the **tile** kernel instead of returning `NONE`;
- add the missing `(512, 512, cols_per_block=2)` tile config (small-batch draft decodes land in that branch).

Verified by forcing all head-512 dispatches through the tile path: output stays coherent and there's no IMA/abort. Happy to open a PR if that'd be useful.
