### ISSUE TITLE
[CANN] Qwen3-ASR fails at aclnn_roll with BinaryGetFunction failed

### ISSUE THREAD

**Issue by rainbend** [ggml-org/llama.cpp#22784]
### Name and Version

Not sure of the exact llama.cpp build number. Built from source with the CANN backend enabled.

Build configuration used:

```bash
cmake -S . -B build-cann \
  -DCMAKE_BUILD_TYPE=Release \
  -DGGML_NATIVE=OFF \
  -DGGML_CANN=ON \
  -DBUILD_SHARED_LIBS=OFF \
  -DLLAMA_BUILD_TESTS=OFF \
  -DLLAMA_CURL=OFF \
  -DCMAKE_CXX_FLAGS="-Wno-pedantic -Wno-zero-length-array" \
  -DCMAKE_EXE_LINKER_FLAGS="-L/usr/local/Ascend/cann-9.0.0/x86_64-linux/lib64 -L/usr/local/Ascend/cann-9.0.0/x86_64-linux/devlib -Wl,-rpath,/usr/local/Ascend/cann-9.0.0/x86_64-linux/lib64"

cmake --build build-cann -j4
```

### Operating systems

Linux x86_64

Kernel:

```bash
uname -r
# 5.15.0-177-generic
```

### GGML backends

CANN

### Hardware

Ascend NPU. Exact chip model can be provided if needed.

The runtime log shows multiple CANN devices and the failure happened on device 1:

```text
new_pool_for_device: device 0 use vmm pool
new_pool_for_device: device 1 use vmm pool
...
current device: 1
```

### CANN environment

CANN version/path:

```text
/usr/local/Ascend/cann-9.0.0
```

CANN libraries found under:

```text
/usr/local/Ascend/cann-9.0.0/x86_64-linux/devlib/libascendcl.so
/usr/local/Ascend/cann-9.0.0/x86_64-linux/devlib/linux/x86_64/libascendcl.so
/usr/local/Ascend/cann-9.0.0/x86_64-linux/devlib/linux/aarch64/libascendcl.so
/usr/local/Ascend/cann-9.0.0/x86_64-linux/lib64/libascendcl.so
```

### Models

Qwen3-ASR, running through the llama.cpp multimodal/audio path with the CANN backend.

### Problem description & steps to reproduce

After successfully building llama.cpp with `GGML_CANN=ON`, running Qwen3-ASR reaches model warmup / inference and then fails in the CANN backend at `aclnn_roll`.

The error looks like CANN runtime cannot locate the binary kernel for an ACLNN op:

```text
common_init_from_params: warming up the model with an empty run - please wait ... (--no-warmup to disable)
new_pool_for_device: device 0 use vmm pool
new_pool_for_device: device 1 use vmm pool
/data/src/llama.cpp/ggml/src/ggml-cann/ggml-cann.cpp:70: CANN error
CANN error: [PID: 208804] 2026-05-07-13:53:10.696.973 Invalid_Argument(EE1001): The argument is invalid.Reason: BinaryGetFunction failed, kernel_name=, retCode=0x7080001
        Solution: 1.Check the input parameter range of the function. 2.Check the function invocation relationship.
        TraceBack (most recent call last):
        Can not find kernel by name = .[FUNC:BinaryGetFunctionByName][FILE:runtime.cc][LINE:5430]
        The argument is invalid.Reason: BinaryGetFunction failed, kernel_name=, retCode=0x7080001
        The argument is invalid.Reason: rtsFuncGetByName execution failed.
        rtBinaryGetFunction failed, runtime result = 107000.[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:148]
        aclrtBinaryGetFunction failed, kernel name:
        Update function handle failed
        Kernel launch from cache failed.
        OpExecCache run fail.

  current device: 1, in function aclnn_roll at /data/src/llama.cpp/ggml/src/ggml-cann/aclnn_ops.cpp:2402
  aclnnRoll(workspaceAddr, workspaceSize, executor, ctx.stream())
```

### Expected behavior

Qwen3-ASR should complete warmup/inference on the CANN backend, or the backend should fall back / report a clear unsupported-op message if `aclnnRoll` is unsupported on the current CANN/chip combination.

### Actual behavior

Runtime fails with `BinaryGetFunction failed` inside `aclnn_roll`.

### Notes

This may be related to a missing or incompatible CANN ops/kernels package, but the error happens inside the llama.cpp CANN backend when launching `aclnnRoll`. It would be helpful to know whether `aclnn_roll` is expected to work for Qwen3-ASR on Ascend/CANN, and whether this op should have a fallback path or a compatibility guard.

I can provide additional information such as `npu-smi info`, `acl.get_soc_name()`, `ASCEND_OPP_PATH`, exact runtime command, and ops package version if needed.

**Comment by yaoshengcn** [comment]
I can confirm came problem on my side.



```
common_init_result: added </s> logit bias = -inf
common_init_result: added <|endoftext|> logit bias = -inf
common_init_result: added <|im_end|> logit bias = -inf
common_init_result: added <|fim_pad|> logit bias = -inf
common_init_result: added <|repo_name|> logit bias = -inf
common_init_result: added <|file_sep|> logit bias = -inf
llama_context: constructing llama_context
llama_context: n_seq_max     = 4
llama_context: n_ctx         = 262144
llama_context: n_ctx_seq     = 262144
llama_context: n_batch       = 2048
llama_context: n_ubatch      = 512
llama_context: causal_attn   = 1
llama_context: flash_attn    = auto
llama_context: kv_unified    = true
llama_context: freq_base     = 5000000.0
llama_context: freq_scale    = 1
llama_context:  CANN_Host  output buffer size =     2.32 MiB
llama_kv_cache:      CANN0 KV buffer size =  2048.00 MiB
llama_kv_cache:      CANN1 KV buffer size =  2048.00 MiB
llama_kv_cache:        CPU KV buffer size =  2048.00 MiB
llama_kv_cache: size = 6144.00 MiB (262144 cells,  12 layers,  4/1 seqs), K (f16): 3072.00 MiB, V (f16): 3072.00 MiB
llama_kv_cache: attn_rot_k = 0, n_embd_head_k_all = 256
llama_kv_cache: attn_rot_v = 0, n_embd_head_k_all = 256
llama_memory_recurrent:      CANN0 RS buffer size =   108.88 MiB
llama_memory_recurrent:      CANN1 RS buffer size =    92.12 MiB
llama_memory_recurrent:        CPU RS buffer size =   100.50 MiB
llama_memory_recurrent: size =  301.50 MiB (     4 cells,  48 layers,  4 seqs), R (f32):   13.50 MiB, S (f32):  288.00 MiB
sched_reserve: reserving ...
sched_reserve: layer 19 is assigned to device CANN0 but the Flash Attention tensor is assigned to device CPU (usually due to missing support)
sched_reserve: Flash Attention was auto, set to disabled
sched_reserve: resolving fused Gated Delta Net support:
sched_reserve: layer 16 is assigned to device CANN0 but the fused Gated Delta Net tensor is assigned to device CPU (usually due to missing support)
sched_reserve: fused Gated Delta Net (autoregressive) not supported, set to disabled
sched_reserve: layer 16 is assigned to device CANN0 but the fused Gated Delta Net tensor is assigned to device CPU (usually due to missing support)
sched_reserve: fused Gated Delta Net (chunked) not supported, set to disabled
sched_reserve:      CANN0 compute buffer size =  8996.00 MiB
sched_reserve:      CANN1 compute buffer size =  8996.00 MiB
sched_reserve:  CANN_Host compute buffer size =  8992.01 MiB
sched_reserve: graph nodes  = 8816 (with bs=512), 6008 (with bs=1)
sched_reserve: graph splits = 472 (with bs=512), 300 (with bs=1)
sched_reserve: reserve took 741.10 ms, sched copies = 1
common_init_from_params: warming up the model with an empty run - please wait ... (--no-warmup to disable)
new_pool_for_device: device 0 use vmm pool
new_pool_for_device: device 1 use vmm pool
/home/user/llama.cpp/ggml/src/ggml-cann/ggml-cann.cpp:70: CANN error
CANN error: [PID: 137255] 2026-05-10-03:24:52.869.056 Invalid_Argument(EE1001): The argument is invalid.Reason: BinaryGetFunction failed, kernel_name=AsStrided_5187ae8ece50f86cefb93a1f6d687ca8_high_performance__kernel0, retCode=0x7080001
        Solution: 1.Check the input parameter range of the function. 2.Check the function invocation relationship.
        TraceBack (most recent call last):
        Can not find kernel by name = AsStrided_5187ae8ece50f86cefb93a1f6d687ca8_high_performance__kernel0.[FUNC:BinaryGetFunctionByName][FILE:runtime.cc][LINE:5430]
        The argument is invalid.Reason: BinaryGetFunction failed, kernel_name=AsStrided_5187ae8ece50f86cefb93a1f6d687ca8_high_performance__kernel0, retCode=0x7080001
        The argument is invalid.Reason: rtsFuncGetByName execution failed.
        rtBinaryGetFunction failed, runtime result = 107000.[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:148]
        aclrtBinaryGetFunction failed, kernel name: AsStrided_5187ae8ece50f86cefb93a1f6d687ca8_high_performance__kernel0
        Update function handle failed
        Kernel launch from cache failed.
        OpExecCache run fail.

  current device: 1, in function cann_copy at /home/user/llama.cpp/ggml/src/ggml-cann/aclnn_ops.cpp:1074
  aclnnInplaceCopy(workspaceAddr, workspaceSize, executor, ctx.stream())
/home/user/llama.cpp/build/bin/libggml-base.so.0(+0x18948)[0x7f1f1758c948]
/home/user/llama.cpp/build/bin/libggml-base.so.0(ggml_print_backtrace+0x1e4)[0x7f1f1758cd24]
/home/user/llama.cpp/build/bin/libggml-base.so.0(ggml_abort+0x11e)[0x7f1f1758ceae]
/home/user/llama.cpp/build/bin/libggml-cann.so.0(+0x310f3)[0x7f1f1765f0f3]
/home/user/llama.cpp/build/bin/libggml-cann.so.0(+0x124fd)[0x7f1f176404fd]
/home/user/llama.cpp/build/bin/libggml-cann.so.0(_Z13ggml_cann_dupR25ggml_backend_cann_contextP11ggml_tensor+0x3b2)[0x7f1f1764e2c2]
/home/user/llama.cpp/build/bin/libggml-cann.so.0(+0x3800f)[0x7f1f1766600f]
/home/user/llama.cpp/build/bin/libggml-base.so.0(ggml_backend_sched_graph_compute_async+0x817)[0x7f1f175a8f17]
/home/user/llama.cpp/build/bin/libllama.so.0(_ZN13llama_context13graph_computeEP11ggml_cgraphb+0xa1)[0x7f1f178c4021]
/home/user/llama.cpp/build/bin/libllama.so.0(_ZN13llama_context14process_ubatchERK12llama_ubatch14llm_graph_typeP22llama_memory_context_iR11ggml_status+0xe4)[0x7f1f178c6544]
/home/user/llama.cpp/build/bin/libllama.so.0(_ZN13llama_context6decodeERK11llama_batch+0x36e)[0x7f1f178cd69e]
/home/user/llama.cpp/build/bin/libllama.so.0(llama_decode+0xb)[0x7f1f178ced1b]
/home/user/llama.cpp/build/bin/libllama-common.so.0(_Z23common_init_from_paramsR13common_params+0x3c8)[0x7f1f17dd5d48]
./llama-server[0x4f91df]
./llama-server[0x45f194]
/usr/lib64/libc.so.6(+0x23ad0)[0x7f1f16a4bad0]
/usr/lib64/libc.so.6(__libc_start_main+0x89)[0x7f1f16a4bb89]

```

**Comment by KokerZhou** [comment]
As a workaround, could you please try to disable kernel caching by setting the following environment variable:

```sh
export ACLNN_CACHE_LIMIT=0
```

**Comment by yaoshengcn** [comment]
> As a workaround, could you please try to disable kernel caching by setting the following environment variable:
> 
> export ACLNN_CACHE_LIMIT=0

Yes, this works for me. Thank you!
