### ISSUE TITLE
Misc. bug: llama-server vram usage gradually increasing each run until OOM

### ISSUE THREAD

**Issue by SarcasticBaka29** [ggml-org/llama.cpp#23446]
### Name and Version

version: 9261 (ad2775726)                                      │
built with GNU 14.2.0 for Linux x86_64  

### Operating systems

Linux

### Which llama.cpp modules do you know to be affected?

llama-server

### Command line

```shell
llama-server --device CUDA0 --host 0.0.0.0 --port ${PORT} -ngl 999  -fa on  --jinja --no-mmap -cram 2048 --ctx-checkpoints 1 --no-warmup -np 1
      --model ${host_model_dir}/Qwen3.6-27B-MTP/Qwen3.6-27B-UD-Q4_K_XL.gguf
      --no-mmproj
      --spec-type draft-mtp --spec-draft-n-max 3 --spec-draft-p-min 0.0 
      --spec-type ngram-mod --spec-ngram-mod-n-match 24 --spec-ngram-mod-n-min 48 --spec-ngram-mod-n-max 64
      --spec-type ngram-map-k4v --spec-ngram-map-k4v-size-n 16 --spec-ngram-map-k4v-size-m 24 --spec-ngram-map-k4v-min-hits 1
      --ctx-size 80000
      -n 32768
      --cache-type-k q8_0
      --cache-type-v q8_0
      --temp 0.6
      --presence-penalty 0.0
      --repeat-penalty 1.0
      --min-p 0.0
      --top-k 20
      --top-p 0.95
      --fit off
      --reasoning on
      --reasoning-budget -1
      --chat-template-kwargs '{"preserve_thinking":true}'
```

### Problem description & steps to reproduce

Let me say upfront that I'm not even sure if this is actually a bug or normal behavior I was not aware of. I'm currently running the MTP enabled Qwen3.6-27B-UD-Q4_K_XL on a 22GB 2080TI GPU using the CUDA backend and I can just about fit 80k context which uses 21.05GB after the model is fully loaded.

The issue I'm facing is that once I start running  prompts the VRAM usage will start steadily increasing until it eventually OOMs.  

To give specific numbers : VRAM usage immediately jumps from 21.05 to 21.5 when launching the first prompt, then it will slowly but surely increase as tokens are being generated, reaching 21.75 at 5k tokens and hits the OOM error at around 10k tokens.

The additional VRAM is not freed after the generation fully finishes either. It just keeps adding up for every new prompt I run.b

I thought this might be an MTP related bug since I had never noticed this before and I'm aware that MTP in general requires more VRAM so I tried the non mtp version of the same Qwen3.6-27B model and although the steady increase in VRAM usage does still happen, it does tend to go up much slower.

I thought this might be related to checkpoints but setting the number of checkpoints to 1 makes no difference whatsoever.

Thanks for any help.

### Relevant log output

<details>
<summary>Logs</summary>

```console

```
</details>

**Comment by paradigm** [comment]
I'm also seeing this.  I suspect it occurred after 3a9c1b8, as I either did not run into or did not notice the issue there.

**Comment by ddh0** [comment]
I see this same issue too, I can't tell what causes it.

EDIT: I do notice that when it _does_ happen, VRAM increases over time during token generation. But I don't know which combination of options/models/features cause the issue to appear... :/

**Comment by paradigm** [comment]
Relevant MR has merged: https://github.com/ggml-org/llama.cpp/pull/23461

Unfortunately the issue remains for me.

**Comment by SarcasticBaka29** [comment]
> Relevant MR has merged: [#23461](https://github.com/ggml-org/llama.cpp/pull/23461)
> 
> Unfortunately the issue remains for me.

Same here. Just rebuilt and retested and the same behavior occurs.

**Comment by am17an** [comment]
Can you identify which parameters cause this? Perhaps remove all `-spec-type` and check, and then add `draft-mtp` and then later add `ngram-mod` etc. I tried reproducing this and I can't

**Comment by SarcasticBaka29** [comment]
> Can you identify which parameters cause this? Perhaps remove all `-spec-type` and check, and then add `draft-mtp` and then later add `ngram-mod` etc. I tried reproducing this and I can't

I tried to test the various scenarios using the same Qwen3.6-27-MTP quant and my results were as follows:
- No speculative decoding of any kind :  Vram usage stays pretty much the exact same after 10k tokens generated.
- Using "--spec-type draft-mtp" only : Immediate 500mb increase on the first prompt (pp buffer?) then keeps increasing relatively slowly as tokens are generated.
- Using "ngram-mod" and "ngram-map-k4v" only : initial increase of about 150mb after about 1k tokens generated followed by a steady increase at about the same rate as MTP.
- Using both speculative decoding methods together aka the worst of both worlds scenario: Getting the initial 500mb bump on pp followed by the second 150mb increase after about 1k tokens then a steady increase at a faster rate than when using each method individually.

Hope this will be helpful to you.

**Comment by rafalhao** [comment]
Hi, I'm having the same issue, somewhere along the lines of commits in the master branch, the VRAM usage shot up straight away on the first prompt, something like 400 to 500 MB, I also run out of VRAM much faster leading to OOM errors well before my context window is full.

Before I didn't have this issue, meaning launching llama-server with the same set of flags, wouldn't cause this problem. (I was using draft-mtp both before and at the moment).

I'm using Ubuntu Server 26.04 LTS RTX 3090.

If in the meantime this issue is fixed, I'll signal it here.

**Comment by paradigm** [comment]
I attempted to find the minimum set of flags which reliably reproduce the issue:

- #23461 appears to have resolved the original MTP memory leak I was running into.  At the time of my original report I was under the impression I had reproduced this without `--split-mode tensor`.
- After initially reproducing an issue with MTP but before #23461 merged, I added in `--split-mode tensor`, which [introduced a separate, currently known memory leak](https://github.com/ggml-org/llama.cpp/issues/23486) that I didn't detect due to the preexisting MTP leak covering it.
- Post-#23461, removing `--split-mode tensor` resolves the issue, irrelevant of MTP flags.

Thus I'm withdrawing my reported ability to reproduce a memory leak with the OP's described set of flags.

I encourage others here that reproduce the issue to follow am17an's advice and attempt to find a minimum set of flags that reproduce the issue.

**Comment by SarcasticBaka29** [comment]
Since the issue still persists and makes using any kind of speculative decoding impossible, I decided to do some more testing by switching to the vulkan backend to see if there's any difference. Unfortunately the same exact behavior is observed so whatever the issue is, it's not cuda specific. 

Edit: Also tried Bartowski's Q4_K_M quant instead of unsloth's thinking it might be a quantization issue but I'm still seeing the same thing happen.

Edit 2: Further testing indicates that this issue is in some way related to kv-cache quantization. When I get rid of the --cache-type-k q8_0 and --cache-type-v q8_0 parameters (Thus having to lower my context to 45000), the initial +650mb bump in vram usage on first prompt still occurs, but after that vram does not grow significantly as tokens are generated like it did before. It only goes up by 11mb after generating 30k tokens.

So the issue I'm facing seems to perhaps stem from a combination of speculative decoding and kv-cache quantization.

**Comment by noodleprincss-ai** [comment]
I am also able to reproduce this on Windows 11 with llama.cpp build 9275 using qwen3.6-27b Q6K on an RTX 5090 with CUDA 13.1 with the following launch parameters (this is where I discovered it being an issue) - also if it matters, the GGUF I'm using is the Unsloth MTP variety (https://huggingface.co/unsloth/Qwen3.6-27B-MTP-GGUF?show_file_info=Qwen3.6-27B-Q6_K.gguf):

```
& "C:\llama.cpp\b9275\build\bin\Release\llama-server.exe" `
  --model "C:\llama.cpp\models\Qwen3.6-27B-Q6_K.gguf" `
  --mmproj "C:\llama.cpp\models\Qwen-3.6-27B-mmproj-BF16.gguf" `
  --image-min-tokens 1024 `
  --no-mmproj-offload `
  --n-gpu-layers 999 `
  --ctx-size 131072 `
  --fit off `
  --parallel 1 `
  --threads 16 `
  --temp 0.7 `
  --top-p 0.95 `
  --min-p 0.00 `
  --top-k 20 `
  --presence_penalty 0.0 `
  --chat-template-kwargs '{\"preserve_thinking\": true}' `
  --flash-attn on `
  --spec-type draft-mtp `
  --spec-draft-n-max 3 `
  --cache-type-k-draft q4_0 `
  --cache-type-v-draft q4_0 `
  --batch-size 4096 `
  --ubatch-size 1024 `
  --cache-type-k q8_0 `
  --cache-type-v q8_0 `
  --checkpoint-every-n-tokens 16384 `
  --cache-ram 0 `
  --ctx-checkpoints 2 `
  --no-mmap `
  --host 0.0.0.0 `
  --port 8083 `
  --log-file $logFile
```

I do not have any --split-mode tensor setup for this system and the symptom I see is a regular growth of 4\~6MiB chunks of VRAM being utilized during both prompt processing and token generation.  (When deeper in the context window, it can jump by 4 to approx 32MiB per prompt, but early in context the 4\~16MiB-per-growth seems to be mostly consistent).

Observations running a quick AI-written script to test multiple turns using a fairly standard "the quick brown fox..." type seed and then a "please continue" for further turns (pasted at the bottom since I can't attach .ps1 files) -- each turn sees a + delta VRAM change.  This is the condition that eventually leads to an OOM:

Idle VRAM: 28734 MiB
Turn  1 (msgs=  3):  28734 ->  29752 MiB  (delta +1018)
Turn  2 (msgs=  5):  29752 ->  29772 MiB  (delta +20)
Turn  3 (msgs=  7):  29772 ->  29780 MiB  (delta +8)
Turn  4 (msgs=  9):  29780 ->  29796 MiB  (delta +16)
Turn  5 (msgs= 11):  29796 ->  29812 MiB  (delta +16)
Turn  6 (msgs= 13):  29812 ->  29828 MiB  (delta +16)
Turn  7 (msgs= 15):  29828 ->  29844 MiB  (delta +16)
Turn  8 (msgs= 17):  29844 ->  29852 MiB  (delta +8)
Turn  9 (msgs= 19):  29852 ->  29864 MiB  (delta +12)
Turn 10 (msgs= 21):  29864 ->  29876 MiB  (delta +12)
[...eventually this will OOM with enough turns... which is the issue at hand...]

-----------

[No recreate] Using a minimal launch parameter setup does NOT reproduce the issue:

```
& "C:\llama.cpp\b9275\build\bin\Release\llama-server.exe" `
  --model "C:\llama.cpp\models\Qwen3.6-27B-Q6_K.gguf" `
  --n-gpu-layers 999 `
  --ctx-size 131072 `
  --threads 16 `
  --host 0.0.0.0 `
  --port 8083 `
  --log-file $logFile

```
Minimal Scenario Observation: In this one, I see 30624MiB initially, then +88MiB on the first turn to 30712MiB and then +0 for all subsequent test turns.

Idle VRAM: 30624 MiB
Turn  1:  30624 ->  30712 MiB  (delta +88)
Turn  2:  30712 ->  30712 MiB  (delta +0)
Turn  3:  30712 ->  30712 MiB  (delta +0)
Turn  4:  30712 ->  30712 MiB  (delta +0)
Turn  5:  30712 ->  30712 MiB  (delta +0)
Turn  6:  30712 ->  30712 MiB  (delta +0)
Turn  7:  30712 ->  30712 MiB  (delta +0)
Turn  8:  30712 ->  30712 MiB  (delta +0)
Turn  9:  30712 ->  30712 MiB  (delta +0)
Turn 10:  30712 ->  30712 MiB  (delta +0)

-----------

[No recreate] MTP Spec Dec ONLY - Adding in speculative decoding (MTP) only, using this launch parameter setup (note: I had to reduce the context window to fit to VRAM size on my 5090 because the cache is not quantized with these launch parameters, so it overruns with the 'W common_fit_params: failed to fit params to free device memory: n_gpu_layers already set by user to 999, abort' error):

```
& "C:\llama.cpp\b9275\build\bin\Release\llama-server.exe" `
  --model "C:\llama.cpp\models\Qwen3.6-27B-Q6_K.gguf" `
  --n-gpu-layers 999 `
  --ctx-size 50000 `
  --threads 16 `
  --spec-type draft-mtp `
  --spec-draft-n-max 3 `
  --cache-type-k-draft q4_0 `
  --cache-type-v-draft q4_0 `
  --host 0.0.0.0 `
  --port 8083 `
  --log-file $logFile
```

MTP Spec Dec Observation: Initial load RAM utilization is 28066MiB, turn 1 is +626MiB, all subsequent turns are +0.

Idle VRAM: 28066 MiB
Turn  1:  28066 ->  28692 MiB  (delta +626)
Turn  2:  28692 ->  28692 MiB  (delta +0)
Turn  3:  28692 ->  28692 MiB  (delta +0)
Turn  4:  28692 ->  28692 MiB  (delta +0)
Turn  5:  28692 ->  28692 MiB  (delta +0)
Turn  6:  28692 ->  28692 MiB  (delta +0)
Turn  7:  28692 ->  28692 MiB  (delta +0)
Turn  8:  28692 ->  28692 MiB  (delta +0)
Turn  9:  28692 ->  28692 MiB  (delta +0)
Turn 10:  28692 ->  28692 MiB  (delta +0)

-----------

[No recreate] Context Checkpoints ONLY - Next I tried to check and see if the context checkpoints was the isolated cause of the issue and used this setup (note: I left the context window at 50000):

```
& "C:\llama.cpp\b9275\build\bin\Release\llama-server.exe" `
  --model "C:\llama.cpp\models\Qwen3.6-27B-Q6_K.gguf" `
  --n-gpu-layers 999 `
  --ctx-size 50000 `
  --threads 16 `
  --checkpoint-every-n-tokens 16384 `
  --ctx-checkpoints 2 `
  --cache-ram 0 `
  --host 0.0.0.0 `
  --port 8083 `
  --log-file $logFile
```

Context Checkpoints Observation: I see 25568MiB initially, then +86MiB on the first turn, +2MiB on the second turn, and then +0 for all subsequent test turns. No recreate.

PS C:\llama.cpp> pwsh -File C:\llama.cpp\vram-leak-harness-appending.ps1 -Tag B-checkpoints -Turns 20 -Tokens 2048
Idle VRAM: 25568 MiB
Turn  1 (msgs=  3):  25568 ->  25654 MiB  (delta +86)
Turn  2 (msgs=  5):  25654 ->  25656 MiB  (delta +2)
Turn  3 (msgs=  7):  25656 ->  25656 MiB  (delta +0)
Turn  4 (msgs=  9):  25656 ->  25656 MiB  (delta +0)
Turn  5 (msgs= 11):  25656 ->  25656 MiB  (delta +0)
Turn  6 (msgs= 13):  25656 ->  25656 MiB  (delta +0)
Turn  7 (msgs= 15):  25656 ->  25656 MiB  (delta +0)
Turn  8 (msgs= 17):  25656 ->  25656 MiB  (delta +0)
Turn  9 (msgs= 19):  25656 ->  25656 MiB  (delta +0)
Turn 10 (msgs= 21):  25656 ->  25656 MiB  (delta +0)
[...remainder of turns truncated...]

----------

[Recreate?!] KV Cache Quantization - Next I tested KV cache quantization using this script (note: the context window went back up to 131072 here because it fits in VRAM now and I left the remainder of the header env variables here in case someone wants to use this verbatim):

```
$env:PATH = "C:\llama.cpp\b9275\build\bin\Release;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v13.1\bin;" + $env:PATH
$env:CUDA_PATH = "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v13.1"

$logFile = "C:\llama.cpp\logs\serve-D-kvq-$(Get-Date -Format yyyyMMdd-HHmmss).log"
New-Item -ItemType Directory -Force -Path (Split-Path $logFile) | Out-Null

& "C:\llama.cpp\b9275\build\bin\Release\llama-server.exe" `
  --model "C:\llama.cpp\models\Qwen3.6-27B-Q6_K.gguf" `
  --n-gpu-layers 999 `
  --ctx-size 131072 `
  --threads 16 `
  --cache-type-k q8_0 `
  --cache-type-v q8_0 `
  --host 0.0.0.0 `
  --port 8083 `
  --log-file $logFile

```
KV Cache Quantization Observation: I definitely see VRAM usage creep up here **(recreate?!)**. I'm not sure if this is expected or not, but I believe it is likely not since VRAM usage should be stable. One thing that is important to note is that I see the VRAM usage creep up right at the turn boundary (so I think it probably has to do with prompt processing side on the new turn). It is mildly interesting that this recreates without the MTP enablement...but perhaps it is worse when combined with MTP? I will test this out on the same script next, but wanted to share findings and possibly combine MTP with different KV cache quantization settings to see if there's an effect.

PS C:\llama.cpp> pwsh -File C:\llama.cpp\vram-leak-harness-appending.ps1 -Tag B-checkpoints -Turns 10 -Tokens 4096
Idle VRAM: 26882 MiB
Turn  1 (msgs=  3):  26882 ->  26906 MiB  (delta +24)
Turn  2 (msgs=  5):  26906 ->  26912 MiB  (delta +6)
Turn  3 (msgs=  7):  26912 ->  26918 MiB  (delta +6)
Turn  4 (msgs=  9):  26918 ->  26926 MiB  (delta +8)
Turn  5 (msgs= 11):  26926 ->  26934 MiB  (delta +8)
Turn  6 (msgs= 13):  26934 ->  26940 MiB  (delta +6)
Turn  7 (msgs= 15):  26940 ->  26946 MiB  (delta +6)
Turn  8 (msgs= 17):  26946 ->  26952 MiB  (delta +6)
Turn  9 (msgs= 19):  26952 ->  26958 MiB  (delta +6)
Turn 10 (msgs= 21):  26958 ->  26958 MiB  (delta +0)

-----------

Appendix:

Script used to generate the test data above (powershell):


```
param(
  [string]$Endpoint = "http://127.0.0.1:8083/v1/chat/completions",
  [int]$Turns       = 30,
  [int]$Tokens      = 512,
  [string]$Tag      = "run"
)

$stamp   = Get-Date -Format yyyyMMdd-HHmmss
$outDir  = "C:\llama.cpp\logs\vram-$Tag-$stamp"
New-Item -ItemType Directory -Force -Path $outDir | Out-Null
$vramCsv  = Join-Path $outDir "vram.csv"
$turnsCsv = Join-Path $outDir "turns.csv"

$smi = Start-Process -FilePath "nvidia-smi" `
  -ArgumentList "--query-gpu=timestamp,memory.used,memory.free","--format=csv,noheader,nounits","-l","1" `
  -RedirectStandardOutput $vramCsv -NoNewWindow -PassThru

function Get-VramMiB {
  $line = & nvidia-smi --query-gpu=memory.used --format=csv,noheader,nounits | Select-Object -First 1
  [int]($line.Trim())
}

# Seed prompt — long-ish, ~1.5k tokens, so 30 turns covers ~45k+ tokens of context.
$seed = "You are an assistant. Discuss the following passage in detail. " + ("The quick brown fox jumps over the lazy dog. " * 40)

$messages = @(@{ role = "user"; content = $seed })

"turn,ctx_messages,vram_before_mib,vram_after_mib,delta_mib" | Out-File -FilePath $turnsCsv -Encoding ascii

Start-Sleep -Seconds 3
$baseline = Get-VramMiB
Write-Host "Idle VRAM: $baseline MiB"

for ($i = 1; $i -le $Turns; $i++) {
  $before = Get-VramMiB
  $body = @{
    model       = "local"
    max_tokens  = $Tokens
    temperature = 0
    messages    = $messages
  } | ConvertTo-Json -Depth 10

  try {
    $resp = Invoke-RestMethod -Uri $Endpoint -Method Post -ContentType "application/json" -Body $body -TimeoutSec 600
    $assistantReply = $resp.choices[0].message.content
    $messages += @{ role = "assistant"; content = $assistantReply }
    $messages += @{ role = "user"; content = "Please continue elaborating with more detail and examples." }
  } catch {
    Write-Warning "Turn $i request failed: $($_.Exception.Message)"
  }

  Start-Sleep -Seconds 1
  $after = Get-VramMiB
  $delta = $after - $before
  "$i,$($messages.Count),$before,$after,$delta" | Add-Content -Path $turnsCsv
  $sign = if ($delta -ge 0) { "+" } else { "" }
  Write-Host ("Turn {0,2} (msgs={1,3}): {2,6} -> {3,6} MiB  (delta {4}{5})" -f $i, $messages.Count, $before, $after, $sign, $delta)
}

Stop-Process -Id $smi.Id -Force -ErrorAction SilentlyContinue
Write-Host "Per-turn CSV: $turnsCsv"
Write-Host "1Hz VRAM CSV: $vramCsv"
```

**Comment by noodleprincss-ai** [comment]
I went back to my original launcher script and changed the KV cache from q8_0 on both to f16 on both (and reduced my context window from 131072 to 50000 to fit in VRAM) and I can see that the issue does _not_ entirely go away, but is greatly reduced. 

Here's the based-on-my-original launcher script with the KV cache and context window changed:

```
. "C:\llama.cpp\gpu-config.ps1"
$env:PATH = "C:\llama.cpp\b9275\build\bin\Release;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v13.1\bin;" + $env:PATH
$env:CUDA_PATH = "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v13.1"

$logFile = "C:\llama.cpp\logs\qwen3.6-27b-mtp-$(Get-Date -Format 'yyyyMMdd-HHmm').log"
New-Item -ItemType Directory -Force -Path "C:\llama.cpp\logs" | Out-Null
Write-Host "Logging to: $logFile"

& "C:\llama.cpp\b9275\build\bin\Release\llama-server.exe" `
  --model "C:\llama.cpp\models\Qwen3.6-27B-Q6_K.gguf" `
  --mmproj "C:\llama.cpp\models\Qwen-3.6-27B-mmproj-BF16.gguf" `
  --image-min-tokens 1024 `
  --no-mmproj-offload `
  --n-gpu-layers 999 `
  --ctx-size 50000 `
  --fit off `
  --parallel 1 `
  --threads 16 `
  --temp 0.7 `
  --top-p 0.95 `
  --min-p 0.00 `
  --top-k 20 `
  --presence_penalty 0.0 `
  --chat-template-kwargs '{\"preserve_thinking\": true}' `
  --flash-attn on `
  --spec-type draft-mtp `
  --spec-draft-n-max 3 `
  --cache-type-k-draft q4_0 `
  --cache-type-v-draft q4_0 `
  --batch-size 4096 `
  --ubatch-size 1024 `
  --cache-type-k f16 `
  --cache-type-v f16 `
  --checkpoint-every-n-tokens 16384 `
  --cache-ram 0 `
  --ctx-checkpoints 2 `
  --no-mmap `
  --host 0.0.0.0 `
  --port 8083 `
  --log-file $logFile
```

And the output of my previous comment's script to test multiple message turns for VRAM usage deltas:

PS C:\llama.cpp> pwsh -File C:\llama.cpp\vram-leak-harness-appending.ps1 -Tag full-minus-kvq -Turns 10 -Tokens 4096
Idle VRAM: 27280 MiB
Turn  1 (msgs=  3):  27280 ->  28392 MiB  (delta +1112)
Turn  2 (msgs=  5):  28392 ->  28392 MiB  (delta +0)
Turn  3 (msgs=  7):  28392 ->  28392 MiB  (delta +0)
Turn  4 (msgs=  9):  28392 ->  28392 MiB  (delta +0)
**Turn  5 (msgs= 11):  28392 ->  28400 MiB  (delta +8)**
Turn  6 (msgs= 13):  28400 ->  28400 MiB  (delta +0)
Turn  7 (msgs= 15):  28400 ->  28400 MiB  (delta +0)
Turn  8 (msgs= 17):  28400 ->  28400 MiB  (delta +0)
Turn  9 (msgs= 19):  28400 ->  28400 MiB  (delta +0)
Turn 10 (msgs= 21):  28400 ->  28400 MiB  (delta +0)

It seems like >90% of the issue is related to KV cache quantization causing the VRAM leak (?)... I did still see one turn where there was a +8MiB delta though... mostly isolating to KV cache quantization is great and terrible because that greatly reduces the available context window, but it's good that it seems to be mostly confined to one issue (though perhaps there is a second one lurking out there, just not nearly as severe).  I have a mild hypothesis that the draft model's quantization may be the contributor for that single +8MiB I saw in this most recent run, but unconfirmed.

TL;DR seems to be  `--cache-type-k q8_0 & --cache-type-v q8_0 ` cause >90% of this issue based on my observations / setup.

**Comment by noodleprincss-ai** [comment]
I don't know the llama.cpp code at all, but using Claude, I think I was able to pinpoint this issue (note: AI generated code here, so not well reviewed yet) and I'm now testing on my personal setup, but the first few rounds of testing seem legitimately better _with the caveat that it eats more VRAM up front on first message turn, but I think that's more truthful than simply growing VRAM forever and eventually OOMing:_

- Repro: quantized KV cache (--cache-type-k/v q8_0 or any non-fp16) + flash attention (default auto enables on modern hardware) + long-output decoding. VRAM grows monotonically by Δ_context × n_kv_heads × head_dim × sizeof(half) × 2 (K+V) per turn.

- Mechanism: launch_fattn in ggml/src/ggml-cuda/fattn-common.cuh (lines 975, 1008 on master c0c7e14) allocates K_f16/V_f16 dequant workspaces sized by current ggml_nelements(K/V), which grows with context. The legacy CUDA pool allocator (ggml_cuda_pool_leg::alloc in ggml-cuda.cu) requires b.size >= request_size for reuse, so older smaller buffers strand in buffer_pool[] as context grows.

```
Two lines changed in substance:

Line 975: K_f16.alloc(ggml_nelements(K)); → K_f16.alloc(ggml_nelements(K->view_src ? K->view_src : K));
Line 1008: V_f16.alloc(ggml_nelements(V)); → V_f16.alloc(ggml_nelements(V->view_src ? V->view_src : V));
```
 
- Validating on my local build: Change eliminates per-turn growth; costs ~1 GiB additional upfront committed for a Qwen3.6-27B/131k-ctx with MTP config but no longer grows forever unbounded to OOM. Performance also seems unaffected, getting ~95-125tok/s TG but have not rigorously tested PP. 

Early tests using my original launch parameters:

Idle VRAM: 28734 MiB
Turn  1 (msgs=  3):  28734 ->  30772 MiB  (delta +2038)
Turn  2 (msgs=  5):  30772 ->  30772 MiB  (delta +0)
Turn  3 (msgs=  7):  30772 ->  30772 MiB  (delta +0)
Turn  4 (msgs=  9):  30772 ->  30772 MiB  (delta +0)
Turn  5 (msgs= 11):  30772 ->  30772 MiB  (delta +0)
Turn  6 (msgs= 13):  30772 ->  30772 MiB  (delta +0)
Turn  7 (msgs= 15):  30772 ->  30772 MiB  (delta +0)
Turn  8 (msgs= 17):  30772 ->  30772 MiB  (delta +0)
Turn  9 (msgs= 19):  30772 ->  30772 MiB  (delta +0)
Turn 10 (msgs= 21):  30772 ->  30772 MiB  (delta +0)

11.39.780.578 I slot print_timing: id  0 | task 3948 | n_decoded =    100, tg = 100.89 t/s
11.42.802.896 I slot print_timing: id  0 | task 3948 | n_decoded =    399, tg =  99.40 t/s
11.45.826.802 I slot print_timing: id  0 | task 3948 | n_decoded =    725, tg = 103.02 t/s
11.48.848.485 I slot print_timing: id  0 | task 3948 | n_decoded =   1116, tg = 110.94 t/s
11.51.870.240 I slot print_timing: id  0 | task 3948 | n_decoded =   1521, tg = 116.27 t/s
11.54.896.055 I slot print_timing: id  0 | task 3948 | n_decoded =   1896, tg = 117.71 t/s
11.57.908.274 I slot print_timing: id  0 | task 3948 | n_decoded =   2313, tg = 120.98 t/s
12.00.914.412 I slot print_timing: id  0 | task 3948 | n_decoded =   2661, tg = 120.27 t/s
12.03.925.418 I slot print_timing: id  0 | task 3948 | n_decoded =   3007, tg = 119.63 t/s
12.06.936.874 I slot print_timing: id  0 | task 3948 | n_decoded =   3328, tg = 118.23 t/s
12.09.973.894 I slot print_timing: id  0 | task 3948 | n_decoded =   3696, tg = 118.52 t/s
12.12.996.514 I slot print_timing: id  0 | task 3948 | n_decoded =   4032, tg = 117.87 t/s
12.16.004.529 I slot print_timing: id  0 | task 3948 | n_decoded =   4369, tg = 117.40 t/s
12.19.028.156 I slot print_timing: id  0 | task 3948 | n_decoded =   4721, tg = 117.33 t/s
12.22.049.990 I slot print_timing: id  0 | task 3948 | n_decoded =   5099, tg = 117.87 t/s
12.25.067.039 I slot print_timing: id  0 | task 3948 | n_decoded =   5472, tg = 118.24 t/s
12.28.082.592 I slot print_timing: id  0 | task 3948 | n_decoded =   5817, tg = 118.01 t/s
12.31.085.322 I slot print_timing: id  0 | task 3948 | n_decoded =   6175, tg = 118.08 t/s
12.34.112.720 I slot print_timing: id  0 | task 3948 | n_decoded =   6541, tg = 118.23 t/s
12.37.115.602 I slot print_timing: id  0 | task 3948 | n_decoded =   6871, tg = 117.80 t/s
12.40.142.380 I slot print_timing: id  0 | task 3948 | n_decoded =   7264, tg = 118.40 t/s
12.43.159.595 I slot print_timing: id  0 | task 3948 | n_decoded =   7639, tg = 118.67 t/s
12.46.169.148 I slot print_timing: id  0 | task 3948 | n_decoded =   8039, tg = 119.31 t/s
12.49.170.028 I slot print_timing: id  0 | task 3948 | n_decoded =   8418, tg = 119.61 t/s
12.52.182.545 I slot print_timing: id  0 | task 3948 | n_decoded =   8791, tg = 119.78 t/s
12.55.203.220 I slot print_timing: id  0 | task 3948 | n_decoded =   9145, tg = 119.68 t/s
12.58.221.349 I slot print_timing: id  0 | task 3948 | n_decoded =   9510, tg = 119.73 t/s
13.01.229.171 I slot print_timing: id  0 | task 3948 | n_decoded =   9898, tg = 120.07 t/s
13.04.251.455 I slot print_timing: id  0 | task 3948 | n_decoded =  10261, tg = 120.07 t/s
13.07.267.187 I slot print_timing: id  0 | task 3948 | n_decoded =  10596, tg = 119.76 t/s
13.10.281.389 I slot print_timing: id  0 | task 3948 | n_decoded =  10907, tg = 119.21 t/s

**Comment by rafalhao** [comment]
@noodleprincss-ai good findings.

Just another anecdote,

When the MTP PR was first merged, I remember I could fill 128k context window without OOM errors on my RTX 3090 with q8 KV cache. (with maybe 100mb vram left, when the context was full).

Now in the past 4 or 5 days, not sure about the exact time frame, I pulled all the changes from main/master and I noticed that running llama-server with the exact same flags, changed two things:

1. First prompt consumed 600mb vram, maybe this is some kind of early allocation, not sure, I'll need to verify the PR's that were merged in the meantime.
2. Most importantly, I was always getting OOM errors, before filling my context window.

I also noticed that the VRAM usage increases as the context window fills up, but I think that's the expected behaviour, because this was also happening in the first few days MTP was merged. Although I think that now the increase of VRAM is bigger than before, but again not sure.

Whenever I get time, I'll mess around backtracking several commits in order to find the one, that caused this change of behaviour regarding the VRAM.

**Comment by noodleprincss-ai** [comment]
> Can you identify which parameters cause this? Perhaps remove all `-spec-type` and check, and then add `draft-mtp` and then later add `ngram-mod` etc. I tried reproducing this and I can't

@am17an - Based on quite a bit of testing now (see previous comments), I'm _very_ sure that this is now related to KV cache quantization. I am able to reproduce it on demand now and after a couple of AI generated code changes, I was able to validate that this behavior can be stopped, with the side effect of a larger Turn 1 upfront VRAM price (so, initial model load for me loads ~28.7GiB + turn 1 allocates ~2GiB but no additional allocation after.) See previous comments for what I did to test / potentially fix (maybe not optimally, but at least lets us hunt in the right area I think).

I've poked at this for an hour using that 2 line change from my previous comment ( https://github.com/ggml-org/llama.cpp/issues/23446#issuecomment-4526691301 ) and I'm pretty confident in it now. The real problem with it is the fact that when you load the server and it gets to the standard "all slots are idle" state, that is _still_ not the actual VRAM price - you have to do a message turn to get the real VRAM price and I think that probably breaks --fit and requires a lot of hand fine tuning of the context window size.

**Comment by AbdulrahmanHashem** [comment]
After suspicting that quantizations + speculative decoding are play a role in the memory leak after removing the flags i run one by one i ran some tests to see thier effect on the VRAM during the llm operation
I put the conclusions first and you'll find the tests uder.

# Conclusion

quantizations cause a cumulative VRAM allocations
draft-mtp reserves big buffers after the model fitting is done causing a sure crach is the fit is tite


1: small once
2: large once
3: grows with context
4: small once then grows with context
5: large once then grows with context


| case                                                         | leak |
| -------- | ------- |
| --spec-type ngram-mod                                        | 1 |
| --spec-type draft-mtp                                        | 2 |
| --spec-type draft-mtp,ngram-mod                              | 2 |
| q4_0                                                         | 3 |
| q4_1                                                         | 3 |
| q5_1                                                         | 3 |
| q8_0                                                         | 3 |
| --spec-type ngram-mod with kv q4_0                           | 4 |
| --spec-type ngram-mod with kv q4_1                           | 4 |
| --spec-type ngram-mod with kv q5_1                           | 4 |
| --spec-type ngram-mod with kv q8_0                           | 4 |
| --spec-type draft-mtp with kv q4_1                           | 5 |
| --spec-type draft-mtp with kv q5_1                           | 5 |
| --spec-type draft-mtp with kv q8_0                           | 5 |
| --spec-type draft-mtp,ngram-mod with kv q4_0                 | 5 |


./build/bin/llama-server \
--verbosity 4 \
-m /home/abdulrahman/Personal/Programs/llama/models/Qwen/Qwen3.6-35B-A3B-UD-Q4_K_M_MTP.gguf \
--chat_template_kwargs '{"preserve_thinking": "True"}' \
--jinja \
--temperature 0.6 --top-p 0.95 --top-k 20 --min-p 0.00 --presence-penalty 0.0 --repeat-penalty 1.0 \
--host 0.0.0.0 --port 8080 \
-c 100000 \
--cache-type-k q4_0 --cache-type-v q4_0 \
--spec-type draft-mtp,ngram-mod --spec-draft-n-max 2 --spec-ngram-mod-n-match 24 --spec-ngram-mod-n-min 16 --spec-ngram-mod-n-max 64


# Tests

system
Ryzen 5 3600
32GB DDR4 RAM
RTX 5060ti 16GB
RTX 2060 Super 8GB

all test are done with and old convos of 28,581 and 47,326 tokens

without spec or kv quantizations

--spec-type ngram-mod
--spec-type draft-mtp
--spec-type draft-mtp,ngram-mod

q4_0
q4_1
q5_1
q8_0

--spec-type ngram-mod with kv q4_0
--spec-type ngram-mod with kv q4_1
--spec-type ngram-mod with kv q5_1
--spec-type ngram-mod with kv q8_0

--spec-type draft-mtp with kv q4_1
--spec-type draft-mtp with kv q5_1
--spec-type draft-mtp with kv q8_0


--spec-type draft-mtp,ngram-mod with kv q4_0

# without spec or kv quantizations
after start                                         907
on first request                                    925
TG                                                  926

# ngram-mod
after start                                         897
PP                                                  915
TG                                                  no change


# draft-mtp
after start                                         329
PP                                                  346 831
TG                                                  835
835 - 329 = 506 static after that

some times it reserves very small amounts randmoly duting TG and some times doesn't change at all

this change during PP 346 -> 831 is caused by the following:

0.19.204.809 I srv  params_from_: Chat format: peg-native
0.19.204.955 I slot get_availabl: id  3 | task -1 | selected slot by LRU, t_last = -1
0.19.204.957 I srv  get_availabl: updating prompt cache
0.19.204.962 I srv          load:  - looking for better prompt, base f_keep = -1.000, sim = 0.000
0.19.204.966 I srv        update:  - cache state: 0 prompts, 0.000 MiB (limits: 8192.000 MiB, 100096 tokens, 8589934592 est)
0.19.204.966 I srv  get_availabl: prompt cache update took 0.01 ms
0.19.205.027 I slot launch_slot_: id  3 | task -1 | sampler chain: logits -> ?penalties -> ?dry -> ?top-n-sigma -> top-k -> ?typical -> top-p -> ?min-p -> ?xtc -> temp-ext -> dist
0.19.205.035 I slot launch_slot_: id  3 | task -1 | sampler params:
        repeat_last_n = 64, repeat_penalty = 1.000, frequency_penalty = 0.000, presence_penalty = 0.000
        dry_multiplier = 0.000, dry_base = 1.750, dry_allowed_length = 2, dry_penalty_last_n = 100096
        top_k = 20, top_p = 0.950, min_p = 0.000, xtc_probability = 0.000, xtc_threshold = 0.100, typical_p = 1.000, top_n_sigma = -1.000, temp = 0.600
        mirostat = 0, mirostat_lr = 0.100, mirostat_ent = 5.000, adaptive_target = -1.000, adaptive_decay = 0.900
0.19.205.036 I slot launch_slot_: id  3 | task 0 | processing task, is_child = 0
0.19.205.044 I slot update_slots: id  3 | task 0 | new prompt, n_ctx_slot = 100096, n_keep = 0, task.n_tokens = 24964
0.19.205.053 I slot update_slots: id  3 | task 0 | cached n_tokens = 0, memory_seq_rm [0, end)
0.19.205.170 I srv  log_server_r: done request: POST /v1/chat/completions 127.0.0.1 200
0.23.609.396 I sched_reserve: reserving ...
0.23.650.104 I sched_reserve:      CUDA0 compute buffer size =   324.50 MiB
0.23.650.108 I sched_reserve:      CUDA1 compute buffer size =   982.95 MiB
0.23.650.108 I sched_reserve:  CUDA_Host compute buffer size =   203.52 MiB
0.23.650.109 I sched_reserve: graph nodes  = 108
0.23.650.109 I sched_reserve: graph splits = 6 (with bs=512), 4 (with bs=1)
0.23.650.110 I sched_reserve: reserve took 40.69 ms, sched copies = 1



# draft-mtp,ngram-mod
after start                                         329
after reserving CUDA0,CUDA1 compute buffer          831
PP                                                  835 860 862
switching to a bigger convo                         887

862 - 831 = 31
887 - 862 = 25

the cause of 835 -> 860 is the following:

3.50.715.322 I slot print_timing: id  3 | task 0 | n_decoded =   1895, tg =  53.47 t/s
3.50.940.537 I ~llama_io_write_device: allocated 'CUDA0' buffer 37.688 MiB
3.50.941.287 I ~llama_io_write_device: allocated 'CUDA1' buffer 25.125 MiB
3.53.738.852 I slot print_timing: id  3 | task 0 | n_decoded =   1982, tg =  51.53 t/s



# kv quantizations
this has the same behavior of allocating more vram when getting to a chat with a bigger context

# q4_0
after start                                         860
PP                                                  868 876 885 -- 901 905 909
TG                                                  no change
909 - 860 = 49 grows with context growth

# Q4_1
after start                                         885
PP                                                  893 895 -- 919 920 -- 930 934
TG                                                  no change
934 - 885 = 50 grows with context growth

# q5_1
after start                                         932
PP                                                  940 944 948 950 -- 975 977 981
TG                                                  no change
981 - 932 = 49 grows with context growth


# q8_0
after start                                         883
PP                                                  891 893 897 -- 917 919 -- 926 932
TG                                                  no change
932 - 883 = 49 grows with context growth


# ngram-mod with kv quantizations


# ngram-mod with q4_0
after start                                         862
PP                                                  870 -- 895 -- 911
911 - 862 = 49
TG                                                  911 -> 940 942 948 -- 958 -- 966

it stayed 911 for a while after PP then changed suddenly
the cause of the change during TG 911 -> 940 is the following:

2.53.498.656 I slot print_timing: id  3 | task 0 | n_decoded =   2188, tg =  46.13 t/s
2.54.744.712 I ~llama_io_write_device: allocated 'CUDA0' buffer 39.781 MiB
2.54.745.655 I ~llama_io_write_device: allocated 'CUDA1' buffer 23.031 MiB
2.56.635.661 I slot print_timing: id  3 | task 0 | n_decoded =   2317, tg =  45.82 t/s

# ngram-mod with q4_1
after start                                         888
PP                                                  895 -- 921 -- 934 936
936 - 888 = 48
TG                                                  936 -> 964 966 970 971 973 975

it stayed 936 for a while after PP then changed suddenly
the cause of the change during TG 911 -> 940 is the following:

2.22.522.121 I slot print_timing: id  3 | task 0 | n_decoded =   1517, tg =  47.10 t/s
2.24.603.788 I ~llama_io_write_device: allocated 'CUDA0' buffer 39.781 MiB
2.24.604.937 I ~llama_io_write_device: allocated 'CUDA1' buffer 23.031 MiB
2.25.535.030 I slot print_timing: id  3 | task 0 | n_decoded =   1621, tg =  46.02 t/s

# ngram-mod with q5_1
after start                                         934
PP                                                  942 958 -- 971 973 -- 983
983 - 934 = 49
TG                                                  983 -> 1011 1014 1022 1028 1032

the cause of the change during TG 983 -> 1011 is the following:

1.37.040.788 I slot print_timing: id  3 | task 0 | n_decoded =   1447, tg =  44.61 t/s
1.38.262.933 I ~llama_io_write_device: allocated 'CUDA0' buffer 39.781 MiB
1.38.263.754 I ~llama_io_write_device: allocated 'CUDA1' buffer 23.031 MiB
1.40.046.920 I slot print_timing: id  3 | task 0 | n_decoded =   1564, tg =  44.13 t/s

# ngram-mod with q8_0
after start                                         815
PP                                                  823 929 833 835 837 839 845 -- 864
864 - 815 = 49
TG                                                  864 -> 893 897 899 901 907

the cause of the change during TG 864 -> 893 is the following:

2.15.419.609 I slot print_timing: id  3 | task 0 | n_decoded =   1214, tg =  46.26 t/s
2.16.162.010 I ~llama_io_write_device: allocated 'CUDA0' buffer 37.688 MiB
2.16.162.895 I ~llama_io_write_device: allocated 'CUDA1' buffer 25.125 MiB
2.18.482.616 I slot print_timing: id  3 | task 0 | n_decoded =   1284, tg =  43.81 t/s


# draft-mtp with kv quantizations
Did the same without quantization but during PP it constantly goes up until PP is done
It doesn't go up if i start a convo with lower context than the one before
It goes up more during PP if i start another convo with a bigger context


# draft-mtp with kv Q4_1
after start                                         231
after reserving CUDA0,CUDA1 compute buffer          715
PP                                                  719 -- 745 751 -- 766 768 772 -- 805
805 - 715 = 90 grows with context growth
TG                                                  840 - 868 - 887 - 891

# draft-mtp with kv q5_1
after start                                         290
after reserving CUDA0,CUDA1 compute buffer          774
PP                                                  778 809 819 827 835 840 -- 899
899 - 774 = 125 grows with context growth ( the number is deferent because i started with the bigger context convo this time to see what happens )
TG                                                  903 907 911 915 919 930 946

# draft-mtp with kv q8_0
after start                                         399 407
after reserving CUDA0,CUDA1 compute buffer          883
PP                                                  887 895 897 905 -- 950 960 973
973 - 883 = 90 grows with context growth
TG                                                  977 981 885


# draft-mtp,ngram-mod with kv quantizations


# draft-mtp,ngram-mod with kv Q4_0
after start                                         346 -> 352
after reserving CUDA0,CUDA1 compute buffers         539 ->> 836
PP                                                  850 842 -- 857 -- 871 926
926 - 836 = 90 grows with context growth
TG                                                  926 930 -> 959 964 967 -- 984 -- 992


4.21.254.744 I slot print_timing: id  3 | task 0 | n_decoded =   1695, tg =  52.41 t/s
4.22.915.362 I ~llama_io_write_device: allocated 'CUDA0' buffer 37.688 MiB
4.22.916.114 I ~llama_io_write_device: allocated 'CUDA1' buffer 25.125 MiB
4.24.292.759 I slot print_timing: id  3 | task 0 | n_decoded =   1897, tg =  53.62 t/s

**Comment by AbdulrahmanHashem** [comment]
Why was my report hidden as spam ?
I'm genuinely trying to help an i did some testing and posted here and it was hidden as spam and i'm not sure if that's automated so I'll add the conclusions alone here 

After suspicting that quantizations + speculative decoding are play a role in the memory leak after removing the flags i run one by one i ran some tests to see thier effect on the VRAM during the llm operation
I put the conclusions first and you'll find the tests uder.

# Conclusion

quantizations cause a cumulative VRAM allocations
draft-mtp reserves big buffers after the model fitting is done causing a sure crach is the fit is tite


1: small once
2: large once
3: grows with context
4: small once then grows with context
5: large once then grows with context


| case                                                         | leak |
| -------- | ------- |
| --spec-type ngram-mod                                        | 1 |
| --spec-type draft-mtp                                        | 2 |
| --spec-type draft-mtp,ngram-mod                              | 2 |
| q4_0                                                         | 3 |
| q4_1                                                         | 3 |
| q5_1                                                         | 3 |
| q8_0                                                         | 3 |
| --spec-type ngram-mod with kv q4_0                           | 4 |
| --spec-type ngram-mod with kv q4_1                           | 4 |
| --spec-type ngram-mod with kv q5_1                           | 4 |
| --spec-type ngram-mod with kv q8_0                           | 4 |
| --spec-type draft-mtp with kv q4_1                           | 5 |
| --spec-type draft-mtp with kv q5_1                           | 5 |
| --spec-type draft-mtp with kv q8_0                           | 5 |
| --spec-type draft-mtp,ngram-mod with kv q4_0                 | 5 |

**Comment by rafalhao** [comment]
@noodleprincss-ai 
I just used your two lines fix, and indeed the VRAM usage does not grow after the first prompt.
`K_f16.alloc(ggml_nelements(K->view_src ? K->view_src : K));`
and 
`V_f16.alloc(ggml_nelements(V->view_src ? V->view_src : V));`

However, using images as input for the model, the VRAM usage does grow, eventually leading to OOM. (do note that this happened even before applying the two lines fix).
 These are the flags I ran (**most importantly --mmproj "models/mmproj-BF16.gguf"**):

<details>
<summary>Flags</summary>


```console
  --model "models/Qwen3.6-27B-Q4_K_M.gguf" \
  --alias "qwen3.6-27b" \
  --spec-type "draft-mtp" \
  --spec-draft-n-max 2 \
  --draft-p-min 0.0 \
  --jinja \
  --reasoning-format "deepseek" \
  --chat-template-kwargs '{"preserve_thinking":true}' \
  --mmproj "models/mmproj-BF16.gguf" \
  --ctx-size 110000 \
  --fit on \
  --fit-ctx 110000 \
  --fit-target 512 \
  --cache-type-k "q8_0" \
  --cache-type-v "q8_0" \
  --flash-attn on \
  --n-gpu-layers 99 \
  --parallel 1 \
  --threads 8 \
  --threads-batch 8 \
  --no-mmap \
  --temperature 0.6 \
  --top_p 0.95 \
  --top_k 20 \
  --min_p 0.0 \
  --presence_penalty 0.0 \
  --repeat_penalty 1.0 \
  --host ::
```
</details>

<details>
<summary>Logs of the error</summary>


```console
  4.04.971.488 I srv  params_from_: Chat format: peg-native
4.04.971.618 I slot get_availabl: id  0 | task -1 | selected slot by LCP similarity, sim_best = 0.523 (> 0.100 thold), f_keep = 1.000
4.04.971.660 I slot launch_slot_: id  0 | task 1630 | processing task, is_child = 0
4.04.971.671 W slot update_slots: id  0 | task 1630 | n_past = 4455, slot.prompt.tokens.size() = 4455, seq_id = 0, pos_min = 4454, n_swa = 0
4.04.971.671 I slot update_slots: id  0 | task 1630 | Checking checkpoint with [656, 656] against 4454...
4.05.101.836 W slot update_slots: id  0 | task 1630 | restored context checkpoint (pos_min = 656, pos_max = 656, n_tokens = 657, n_past = 657, size = 151.002 MiB)
4.08.107.455 I slot print_timing: id  0 | task 1630 | prompt processing, n_tokens =   3806, progress = 0.52, t =   3.14 s / 1213.73 tokens per second
4.08.107.600 I srv  process_chun: processing image...
4.08.207.052 E CUDA error: out of memory
/home/rafa/projects/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:102: CUDA error
4.08.207.055 E   current device: 0, in function alloc at /home/rafa/projects/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:527
4.08.207.055 E   cuMemCreate(&handle, reserve_size, &prop, 0)
/home/rafa/projects/llama.cpp/build/bin/libggml-base.so.0(+0x1a7b6) [0x75cd3c3527b6]
/home/rafa/projects/llama.cpp/build/bin/libggml-base.so.0(ggml_print_backtrace+0x20d) [0x75cd3c352c3d]
/home/rafa/projects/llama.cpp/build/bin/libggml-base.so.0(ggml_abort+0x166) [0x75cd3c352e26]
/home/rafa/projects/llama.cpp/build/bin/libggml-cuda.so.0(_Z15ggml_cuda_errorPKcS0_S0_iS0_+0xb5) [0x75cd38c20205]
/home/rafa/projects/llama.cpp/build/bin/libggml-cuda.so.0(_ZN18ggml_cuda_pool_vmm5allocEmPm+0x221) [0x75cd38c39661]
/home/rafa/projects/llama.cpp/build/bin/libggml-cuda.so.0(+0x2286f5) [0x75cd38c286f5]
/home/rafa/projects/llama.cpp/build/bin/libggml-cuda.so.0(+0x22ba15) [0x75cd38c2ba15]
/home/rafa/projects/llama.cpp/build/bin/libggml-cuda.so.0(+0x236903) [0x75cd38c36903]
/home/rafa/projects/llama.cpp/build/bin/libggml-cuda.so.0(+0x2372a2) [0x75cd38c372a2]
/home/rafa/projects/llama.cpp/build/bin/libggml-base.so.0(ggml_backend_sched_graph_compute_async+0x813) [0x75cd3c370113]
/home/rafa/projects/llama.cpp/build/bin/libggml-base.so.0(ggml_backend_sched_graph_compute+0x12) [0x75cd3c3705d2]
/home/rafa/projects/llama.cpp/build/bin/libmtmd.so.0(_Z23clip_image_batch_encodeP8clip_ctxiPK20clip_image_f32_batchPf+0x780) [0x75cd3c799a00]
/home/rafa/projects/llama.cpp/build/bin/libmtmd.so.0(mtmd_encode+0x139) [0x75cd3c715b09]
/home/rafa/projects/llama.cpp/build/bin/libmtmd.so.0(mtmd_helper_eval_chunk_single+0xe4) [0x75cd3c7936f4]
/home/rafa/projects/llama.cpp/build/bin/libllama-server-impl.so(_ZNK13server_tokens13process_chunkEP13llama_contextP12mtmd_contextmiiRm+0xa2) [0x75cd3c92af22]
/home/rafa/projects/llama.cpp/build/bin/libllama-server-impl.so(_ZN19server_context_impl12update_slotsEv+0x1a0b) [0x75cd3c97f1cb]
/home/rafa/projects/llama.cpp/build/bin/libllama-server-impl.so(_ZN12server_queue10start_loopEl+0x1df2) [0x75cd3ca1e322]
/home/rafa/projects/llama.cpp/build/bin/libllama-server-impl.so(_Z12llama_serveriPPc+0x33bd) [0x75cd3c8d850d]
/usr/lib/x86_64-linux-gnu/libc.so.6(+0x2a601) [0x75cd3c02a601]
/usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x88) [0x75cd3c02a718]
./build/bin/llama-server(+0x1325) [0x647639c05325]
```
</details>


Now I do wonder, if this OOM during prompt processing is expected because the vision model requires more VRAM while PPing, or if this is bug.

**Comment by am17an** [comment]
Using the quantized KV-cache, it is expected the VRAM usage will grow as context size grows larger because of the q8->f16 de quantization inside the FA kernel. It should also happen without any spec decoding

**Comment by noodleprincss-ai** [comment]
Hmm... @am17an - so I agree that it happens with quantized KV cache without any speculative decoding (though it does seem worse with speculative decoding, but that might just be increased performance during TG showing it more).  

But something I'm not clear on - my experience is that this memory never seems to deallocate or reset in usage and so no matter what, you eventually end up at an OOM. Is that part expected because I don't think it is (or shouldn't be at least)?

I'll have to do more testing on the image input side of things to address @rafalhao's concern. I haven't observed this so I can't really comment coherently.

**Comment by AbdulrahmanHashem** [comment]
> Using the quantized KV-cache, it is expected the VRAM usage will grow as context size grows larger because of the q8->f16 de quantization inside the FA kernel. It should also happen without any spec decoding

It does it will take roughly 1 mb per 600 tokens
So the full context will allocate roughly 500 mb.

ngram-mod will take a couple mbs and nothing else

MTP will alocate about 180 mb on first prompt before PP and about 35 mb during TG once and nothing else.

**Comment by pikaxinge** [comment]
Fix PR: https://github.com/ggml-org/llama.cpp/pull/23620

**Comment by noodleprincss-ai** [comment]
@rafalhao I poked at this a lot yesterday using images and as far as I can tell, this is not the same issue as text in any way. I'm out of my depth here, but I tried isolating the VRAM usage growth by running _many_ turns of 10 image inputs into the default llama-server web gui and tried to narrow down the culprit - I was able to rule out MTP speculative decoding being on, MTP weights simply being in the model file, persistent context checkpoints, per image token allocations (i.e. '--image-min-tokens 256' vs. 1024 - same VRAM growth for both), i tried the same images vs. different images to see if those were being cached somehow and that did not pan out either, I checked the same KV cache quantization "issue" as text had, I checked flash attention in general (on vs off) [it was actually much worse with it off], and a few other harebrained ideas.

Basically, with image inputs, VRAM usage seems to grow no matter what. I think it might be worth filing a separate issue to understand this behavior better and see if it is expected or not - I simply do not know, but I was able to recreate it with:

```

& "C:\llama.cpp\b9275\build\bin\Release\llama-server.exe" `
  --model "C:\llama.cpp\models\Qwen3.6-27B-Q6_K.gguf" `
  --mmproj "C:\llama.cpp\models\Qwen-3.6-27B-mmproj-BF16.gguf" `
  --n-gpu-layers 999 `
  --ctx-size 70000 `
  --threads 16 `
  --host 0.0.0.0 `
  --port 8083 `
  --log-file $logFile

```

Initial load idle: 28076MiB
Turn 1 simple "hello": 28144MIB (known behavior of 'turn 1' allocating more VRAM)
Turn 2 10x image: 28262MiB
[Additional turns generate additional growth]

**Comment by rafalhao** [comment]
@noodleprincss-ai 
Ty for reporting your experience with images as input for the model. Just like you, I'm not 100% sure if this is expected or not, I'll probably create an issue in the next few days, after I investigate it further.

**Comment by AbdulrahmanHashem** [comment]
@am17an @ggerganov i want to know your thoughts about this issue because it bugs me so much
my system has 24gb VRAM and to utilize most of them is hard enough so it would be very nice to get this severe memory leak fixed.
I'm at a point where i don't even know if it's actually a bug or not so i'd love it if you give us a comment on the state of this issue.
And thanks for the amazing work honestly.

**Comment by am17an** [comment]
It is not a memory leak, but since --fit doesn't account for the kv cache's full context it is not correct in its calculation which leads to this OOM. It will be fixed soon

**Comment by SarcasticBaka29** [comment]
> It is not a memory leak, but since --fit doesn't account for the kv cache's full context it is not correct in its calculation which leads to this OOM. It will be fixed soon

So correct me if I'm wrong but as far as I understand it if using KV-cache quantization VRAM will continue to grow indefinitely along with context no matter what because of the dequantization process? 

After your PR #23646, and setting the draft model's kv to f16, I have noticed that the rate of increase  in VRAM usage went down which would make sense because now we're only dequantizing the main model's context instead of both models at the same time.

What I'm wondering is how the upper limit of vram growth is calculated based on full context and how that could be affected by something like context shift. As someone like me who does not use --fit would need to know the exact "margin" to provide the model in order to completely avoid OOM's.

**Comment by SarcasticBaka29** [comment]
Little update on this issue: Rebuilding after pr #23764 was merged I'm seeing substantial vram savings in 2 different ways:

- The initial vram usage once the model is loaded and before running any prompts has been reduced by about 650mb, going from 21.178gb to 20.530gb at 80k context.
- The sudden 450mb jump in vram usage that used to occur when processing the very first prompt does not happen anymore, so in practice that's about a 1GB reduction in vram usage after the first prompt which is much appreciated.

The second 180mb increase after around 1k tokens generated does still occur as well as the slower continuous increase as more tokens are being generated but I believe that is already being addressed with pr #23907 . 

Edit : I do feel it's important to mention that along with the lower vram usage I'm seeing a slight performance hit. My generation speed with MTP and --spec-draft-n-max 3 went from 47 tk/s on average to 42 tk/s.

**Comment by SarcasticBaka29** [comment]
Update N°2: pr #23907 has been merged and it seems to mostly solve this issue for me. 

With the exact same model and context I outlined in my previous comments, the vram  usage is higher on initial model load by about 260mb (20795mb vs 20531mb), it then still increases by about 180mb on the first couple of prompts. But it eventually reaches a ceiling of around 20.980mb and wont increase any further after 30k tokens generated.

Would love to see some results from the other posters on this thread who experienced the same issue in order to confirm the fix, otherwise I will mark it as solved.

**Comment by AbdulrahmanHashem** [comment]
@SarcasticBaka29  #23907 fixed the KV cache memory creep and #24108 just fixed the around 120 allocations that happen every so offten when using ngram-mod

the only runtime allocations that happen as of 9518 is roughly 100 MB allocation that happens on first prompt PP and then a total of maybe 8 MB that happen after that during TG.

so this probably solves this Issue.

**Comment by SarcasticBaka29** [comment]
> [@SarcasticBaka29](https://github.com/SarcasticBaka29) [#23907](https://github.com/ggml-org/llama.cpp/pull/23907) fixed the KV cache memory creep and [#24108](https://github.com/ggml-org/llama.cpp/pull/24108) just fixed the around 120 allocations that happen every so offten when using ngram-mod
> 
> the only runtime allocations that happen as of 9518 is roughly 100 MB allocation that happens on first prompt PP and then a total of maybe 8 MB that happen after that during TG.
> 
> so this probably solves this Issue.

Yep seeing the same here. Big thanks to @am17an and @ggerganov  for getting this solved.
