### ISSUE TITLE
Misc. bug: CUDA SOFT_MAX fails for llama-server on Ubuntu 26.04

### ISSUE THREAD

**Issue by EJainDev** [ggml-org/llama.cpp#23546]
### Name and Version

$./llama-server --version
version: 9293 (1acee6bf8)
built with GNU 15.2.0 for Linux x86_64

### Operating systems

Linux

### Which llama.cpp modules do you know to be affected?

llama-server

### Command line

```shell
./llama-server \
    -hf unsloth/Qwen3.6-35B-A3B-MTP-GGUF:UD-IQ3_XXS \
    --port 8080 \
    --n-cpu-moe 23 \
    --override-tensor "blk.(2[6-9]|3[0-9]|4[0-6]).ffn_(gate_up|down)_exps.weight=CPU" \
    --cache-type-k q4_0 \
    --cache-type-v q4_0 \
    --flash-attn on \
    --cont-batching \
    --ctx-checkpoints 2 \
    --models-max 1 \
    --spec-type draft-mtp \
    --spec-draft-n-max 2 \
    -c 131072 \
    -b 2048 \
    -ub 512 \
    --spec-draft-type-k q4_0 \
    --spec-draft-type-v q4_0 \
    --cache-ram 2048 \
    --kv-unified \
    -lv 4 \
    --kv-offload \
    -np 1 \
    --reasoning on \
    --no-mmproj
```

### Problem description & steps to reproduce

There is a crash on `llama-server` start-up when it attempts to call the forward pass. I am running the command on a NVIDIA RTX 5060 Mobile and Intel Core 7 240H.

### First Bad Commit

This issue is not present when using the Docker image with version `9191` (commit `4f13cb742`) but when I do a local build on that version (and beyond), I encounter this error.

### Relevant log output

<details>
<summary>Logs</summary>

```console
0.00.165.094 E load_backend: failed to find ggml_backend_init in /home/ejain/llama.cpp/build/bin/libggml-cuda.so
0.00.172.810 E load_backend: failed to find ggml_backend_init in /home/ejain/llama.cpp/build/bin/libggml-cpu.so
0.00.173.375 I common_params_handle_remote_preset: looking for remote preset at https://huggingface.co/unsloth/Qwen3.6-35B-A3B-MTP-GGUF/resolve/main/preset.ini
0.01.063.461 I common_download_file_single_online: HEAD failed, status: 404
0.01.065.994 I common_params_handle_remote_preset: no remote preset found, skipping
0.01.868.575 I common_params_print_info: build 9293 (1acee6bf8) with GNU 15.2.0 for Linux x86_64 (debug)
0.01.868.582 I log_info: verbosity = 4 (adjust with the `-lv N` CLI arg)
0.01.868.583 I device_info:
0.01.999.889 I   - CUDA0   : NVIDIA GeForce RTX 5060 Laptop GPU (7707 MiB, 20777 MiB free)
0.01.999.906 I   - CPU     : Intel(R) Core(TM) 7 240H (31278 MiB, 31278 MiB free)
0.02.000.098 I system_info: n_threads = 6 (n_threads_batch = 6) / 16 | CUDA : ARCHS = 1200 | USE_GRAPHS = 1 | PEER_MAX_BATCH_SIZE = 128 | BLACKWELL_NATIVE_FP4 = 1 | CPU : SSE3 = 1 | SSSE3 = 1 | AVX = 1 | AVX_VNNI = 1 | AVX2 = 1 | F16C = 1 | FMA = 1 | BMI2 = 1 | LLAMAFILE = 1 | OPENMP = 1 | REPACK = 1 | 
0.02.000.407 I srv          init: running without SSL
0.02.000.554 I srv          init: using 15 threads for HTTP server
0.02.001.503 I srv         start: binding port with default address family
0.02.002.819 I srv  llama_server: loading model
0.02.002.826 I srv    load_model: loading model '/home/ejain/.cache/huggingface/hub/models--unsloth--Qwen3.6-35B-A3B-MTP-GGUF/snapshots/5bc3e238d916f48a861bac2f8a1990a0e9b7e98d/Qwen3.6-35B-A3B-UD-IQ3_XXS.gguf'
0.02.003.190 I common_init_result: fitting params to device memory ...
0.02.003.194 I common_init_result: (for bugs during this step try to reproduce them with -fit off, or provide --verbose logs if the bug only occurs with -fit on)
0.02.003.209 I common_params_fit_impl: getting device memory data for initial parameters:
0.05.854.625 I common_memory_breakdown_print: | memory breakdown [MiB]          | total    free    self   model   context   compute    unaccounted |
0.05.854.632 I common_memory_breakdown_print: |   - CUDA0 (RTX 5060 Laptop GPU) |  7707 = 20637 + (6398 =  4979 +     908 +     511) +      -19328 |
0.05.854.633 I common_memory_breakdown_print: |   - Host                        |                  8692 =  8427 +       0 +     264                |
0.05.955.600 I common_params_fit_impl: projected to use 6398 MiB of device memory vs. 20637 MiB of free device memory
0.05.955.612 I common_params_fit_impl: will leave 14239 >= 1024 MiB of free device memory, no changes needed
0.05.955.627 I common_fit_params: successfully fit params to free device memory
0.05.955.631 I common_fit_params: fitting params to free memory took 3.95 seconds
0.06.138.077 I llama_model_loader: loaded meta data with 55 key-value pairs and 753 tensors from /home/ejain/.cache/huggingface/hub/models--unsloth--Qwen3.6-35B-A3B-MTP-GGUF/snapshots/5bc3e238d916f48a861bac2f8a1990a0e9b7e98d/Qwen3.6-35B-A3B-UD-IQ3_XXS.gguf (version GGUF V3 (latest))
0.06.138.368 I llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
0.06.138.383 I llama_model_loader: - kv   0:                       general.architecture str              = qwen35moe
0.06.138.386 I llama_model_loader: - kv   1:                               general.type str              = model
0.06.138.390 I llama_model_loader: - kv   2:                     general.sampling.top_k i32              = 20
0.06.138.400 I llama_model_loader: - kv   3:                     general.sampling.top_p f32              = 0.950000
0.06.138.403 I llama_model_loader: - kv   4:                      general.sampling.temp f32              = 1.000000
0.06.138.404 I llama_model_loader: - kv   5:                               general.name str              = Qwen3.6-35B-A3B
0.06.138.406 I llama_model_loader: - kv   6:                           general.basename str              = Qwen3.6-35B-A3B
0.06.138.408 I llama_model_loader: - kv   7:                       general.quantized_by str              = Unsloth
0.06.138.409 I llama_model_loader: - kv   8:                         general.size_label str              = 35B-A3B
0.06.138.411 I llama_model_loader: - kv   9:                            general.license str              = apache-2.0
0.06.138.416 I llama_model_loader: - kv  10:                       general.license.link str              = https://huggingface.co/Qwen/Qwen3.6-3...
0.06.138.419 I llama_model_loader: - kv  11:                           general.repo_url str              = https://huggingface.co/unsloth
0.06.138.423 I llama_model_loader: - kv  12:                   general.base_model.count u32              = 1
0.06.138.425 I llama_model_loader: - kv  13:                  general.base_model.0.name str              = Qwen3.6 35B A3B
0.06.138.427 I llama_model_loader: - kv  14:          general.base_model.0.organization str              = Qwen
0.06.138.430 I llama_model_loader: - kv  15:              general.base_model.0.repo_url str              = https://huggingface.co/Qwen/Qwen3.6-3...
0.06.138.450 I llama_model_loader: - kv  16:                               general.tags arr[str,3]       = ["qwen3_5_moe", "qwen", "image-text-t...
0.06.138.452 I llama_model_loader: - kv  17:                      qwen35moe.block_count u32              = 41
0.06.138.454 I llama_model_loader: - kv  18:                   qwen35moe.context_length u32              = 262144
0.06.138.456 I llama_model_loader: - kv  19:                 qwen35moe.embedding_length u32              = 2048
0.06.138.458 I llama_model_loader: - kv  20:             qwen35moe.attention.head_count u32              = 16
0.06.138.460 I llama_model_loader: - kv  21:          qwen35moe.attention.head_count_kv u32              = 2
0.06.138.465 I llama_model_loader: - kv  22:          qwen35moe.rope.dimension_sections arr[i32,4]       = [11, 11, 10, 0]
0.06.138.468 I llama_model_loader: - kv  23:                   qwen35moe.rope.freq_base f32              = 10000000.000000
0.06.138.471 I llama_model_loader: - kv  24: qwen35moe.attention.layer_norm_rms_epsilon f32              = 0.000001
0.06.138.473 I llama_model_loader: - kv  25:                     qwen35moe.expert_count u32              = 256
0.06.138.475 I llama_model_loader: - kv  26:                qwen35moe.expert_used_count u32              = 8
0.06.138.477 I llama_model_loader: - kv  27:             qwen35moe.attention.key_length u32              = 256
0.06.138.479 I llama_model_loader: - kv  28:           qwen35moe.attention.value_length u32              = 256
0.06.138.481 I llama_model_loader: - kv  29:       qwen35moe.expert_feed_forward_length u32              = 512
0.06.138.484 I llama_model_loader: - kv  30: qwen35moe.expert_shared_feed_forward_length u32              = 512
0.06.138.487 I llama_model_loader: - kv  31:                  qwen35moe.ssm.conv_kernel u32              = 4
0.06.138.489 I llama_model_loader: - kv  32:                   qwen35moe.ssm.state_size u32              = 128
0.06.138.491 I llama_model_loader: - kv  33:                  qwen35moe.ssm.group_count u32              = 16
0.06.138.493 I llama_model_loader: - kv  34:               qwen35moe.ssm.time_step_rank u32              = 32
0.06.138.496 I llama_model_loader: - kv  35:                   qwen35moe.ssm.inner_size u32              = 4096
0.06.138.498 I llama_model_loader: - kv  36:          qwen35moe.full_attention_interval u32              = 4
0.06.138.500 I llama_model_loader: - kv  37:             qwen35moe.rope.dimension_count u32              = 64
0.06.138.502 I llama_model_loader: - kv  38:             qwen35moe.nextn_predict_layers u32              = 1
0.06.138.516 I llama_model_loader: - kv  39:                       tokenizer.ggml.model str              = gpt2
0.06.138.519 I llama_model_loader: - kv  40:                         tokenizer.ggml.pre str              = qwen35
0.06.427.027 I llama_model_loader: - kv  41:                      tokenizer.ggml.tokens arr[str,248320]  = ["!", "\"", "#", "$", "%", "&", "'", ...
0.06.467.403 I llama_model_loader: - kv  42:                  tokenizer.ggml.token_type arr[i32,248320]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
0.06.776.575 I llama_model_loader: - kv  43:                      tokenizer.ggml.merges arr[str,247587]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
0.06.776.602 I llama_model_loader: - kv  44:                tokenizer.ggml.eos_token_id u32              = 248046
0.06.776.606 I llama_model_loader: - kv  45:            tokenizer.ggml.padding_token_id u32              = 248055
0.06.776.608 I llama_model_loader: - kv  46:                tokenizer.ggml.bos_token_id u32              = 248044
0.06.776.610 I llama_model_loader: - kv  47:               tokenizer.ggml.add_bos_token bool             = false
0.06.776.618 I llama_model_loader: - kv  48:                    tokenizer.chat_template str              = {%- set image_count = namespace(value...
0.06.776.620 I llama_model_loader: - kv  49:               general.quantization_version u32              = 2
0.06.776.622 I llama_model_loader: - kv  50:                          general.file_type u32              = 26
0.06.776.626 I llama_model_loader: - kv  51:                      quantize.imatrix.file str              = Qwen3.6-35B-A3B-GGUF/imatrix_unsloth....
0.06.776.628 I llama_model_loader: - kv  52:                   quantize.imatrix.dataset str              = unsloth_calibration_Qwen3.6-35B-A3B.txt
0.06.776.630 I llama_model_loader: - kv  53:             quantize.imatrix.entries_count u32              = 510
0.06.776.632 I llama_model_loader: - kv  54:              quantize.imatrix.chunks_count u32              = 77
0.06.776.637 I llama_model_loader: - type  f32:  368 tensors
0.06.776.638 I llama_model_loader: - type q8_0:    8 tensors
0.06.776.639 I llama_model_loader: - type q2_K:    2 tensors
0.06.776.639 I llama_model_loader: - type q3_K:    1 tensors
0.06.776.639 I llama_model_loader: - type q6_K:  252 tensors
0.06.776.640 I llama_model_loader: - type iq3_s:   39 tensors
0.06.776.640 I llama_model_loader: - type iq2_s:   78 tensors
0.06.776.641 I llama_model_loader: - type iq4_xs:    3 tensors
0.06.776.641 I llama_model_loader: - type bf16:    2 tensors
0.06.776.648 I print_info: file format = GGUF V3 (latest)
0.06.776.649 I print_info: file type   = IQ3_S - 3.4375 bpw
0.06.776.654 I print_info: file size   = 13.09 GiB (3.17 BPW) 
0.06.779.061 I llama_prepare_model_devices: using device CUDA0 (NVIDIA GeForce RTX 5060 Laptop GPU) (0000:01:00.0) - 20634 MiB free
0.07.399.826 I load: 0 unused tokens
0.07.552.393 I load: printing all EOG tokens:
0.07.552.400 I load:   - 248044 ('<|endoftext|>')
0.07.552.401 I load:   - 248046 ('<|im_end|>')
0.07.552.402 I load:   - 248063 ('<|fim_pad|>')
0.07.552.403 I load:   - 248064 ('<|repo_name|>')
0.07.552.403 I load:   - 248065 ('<|file_sep|>')
0.07.553.755 I load: special tokens cache size = 33
0.08.603.068 I load: token to piece cache size = 1.7581 MB
0.08.603.179 I print_info: arch                  = qwen35moe
0.08.603.180 I print_info: vocab_only            = 0
0.08.603.181 I print_info: no_alloc              = 0
0.08.603.182 I print_info: n_ctx_train           = 262144
0.08.603.182 I print_info: n_embd                = 2048
0.08.603.183 I print_info: n_embd_inp            = 2048
0.08.603.183 I print_info: n_layer               = 41
0.08.603.206 I print_info: n_head                = 16
0.08.603.213 I print_info: n_head_kv             = 2
0.08.603.213 I print_info: n_rot                 = 64
0.08.603.214 I print_info: n_swa                 = 0
0.08.603.233 I print_info: is_swa_any            = 0
0.08.603.234 I print_info: n_embd_head_k         = 256
0.08.603.235 I print_info: n_embd_head_v         = 256
0.08.603.241 I print_info: n_gqa                 = 8
0.08.603.247 I print_info: n_embd_k_gqa          = 512
0.08.603.254 I print_info: n_embd_v_gqa          = 512
0.08.603.255 I print_info: f_norm_eps            = 0.0e+00
0.08.603.257 I print_info: f_norm_rms_eps        = 1.0e-06
0.08.603.258 I print_info: f_clamp_kqv           = 0.0e+00
0.08.603.258 I print_info: f_max_alibi_bias      = 0.0e+00
0.08.603.259 I print_info: f_logit_scale         = 0.0e+00
0.08.603.259 I print_info: f_attn_scale          = 0.0e+00
0.08.603.265 I print_info: f_attn_value_scale    = 0.0000
0.08.603.271 I print_info: n_ff                  = 0
0.08.603.272 I print_info: n_expert              = 256
0.08.603.272 I print_info: n_expert_used         = 8
0.08.603.272 I print_info: n_expert_groups       = 0
0.08.603.273 I print_info: n_group_used          = 0
0.08.603.277 I print_info: causal attn           = 1
0.08.603.278 I print_info: pooling type          = -1
0.08.603.278 I print_info: rope type             = 40
0.08.603.279 I print_info: rope scaling          = linear
0.08.603.280 I print_info: freq_base_train       = 10000000.0
0.08.603.281 I print_info: freq_scale_train      = 1
0.08.603.282 I print_info: n_ctx_orig_yarn       = 262144
0.08.603.282 I print_info: rope_yarn_log_mul     = 0.0000
0.08.603.283 I print_info: rope_finetuned        = unknown
0.08.603.284 I print_info: mrope sections        = [11, 11, 10, 0]
0.08.603.284 I print_info: ssm_d_conv            = 4
0.08.603.285 I print_info: ssm_d_inner           = 4096
0.08.603.285 I print_info: ssm_d_state           = 128
0.08.603.285 I print_info: ssm_dt_rank           = 32
0.08.603.286 I print_info: ssm_n_group           = 16
0.08.603.286 I print_info: ssm_dt_b_c_rms        = 0
0.08.603.288 I print_info: model type            = 35B.A3B
0.08.603.290 I print_info: model params          = 35.51 B
0.08.603.291 I print_info: general.name          = Qwen3.6-35B-A3B
0.08.603.293 I print_info: vocab type            = BPE
0.08.603.294 I print_info: n_vocab               = 248320
0.08.603.295 I print_info: n_merges              = 247587
0.08.603.296 I print_info: BOS token             = 248044 '<|endoftext|>'
0.08.603.296 I print_info: EOS token             = 248046 '<|im_end|>'
0.08.603.298 I print_info: EOT token             = 248046 '<|im_end|>'
0.08.603.299 I print_info: PAD token             = 248055 '<|vision_pad|>'
0.08.603.299 I print_info: LF token              = 198 'Ċ'
0.08.603.300 I print_info: FIM PRE token         = 248060 '<|fim_prefix|>'
0.08.603.300 I print_info: FIM SUF token         = 248062 '<|fim_suffix|>'
0.08.603.301 I print_info: FIM MID token         = 248061 '<|fim_middle|>'
0.08.603.301 I print_info: FIM PAD token         = 248063 '<|fim_pad|>'
0.08.603.301 I print_info: FIM REP token         = 248064 '<|repo_name|>'
0.08.603.302 I print_info: FIM SEP token         = 248065 '<|file_sep|>'
0.08.603.308 I print_info: EOG token             = 248044 '<|endoftext|>'
0.08.603.310 I print_info: EOG token             = 248046 '<|im_end|>'
0.08.603.310 I print_info: EOG token             = 248063 '<|fim_pad|>'
0.08.603.312 I print_info: EOG token             = 248064 '<|repo_name|>'
0.08.603.312 I print_info: EOG token             = 248065 '<|file_sep|>'
0.08.603.313 I print_info: max token length      = 256
0.08.603.314 I load_tensors: loading model tensors, this can take a while... (mmap = true, direct_io = false)
0.08.623.547 W llama_model_loader: tensor overrides to CPU are used with mmap enabled - consider using --no-mmap for better performance
0.15.088.198 I load_tensors: offloading output layer to GPU
0.15.088.257 I load_tensors: offloading 40 repeating layers to GPU
0.15.088.257 I load_tensors: offloaded 42/42 layers to GPU
0.15.088.294 I load_tensors:   CPU_Mapped model buffer size = 12829.16 MiB
0.15.088.297 I load_tensors:        CUDA0 model buffer size =  4979.16 MiB
.................................................................................................
0.16.120.821 I common_init_result: added <|endoftext|> logit bias = -inf
0.16.120.865 I common_init_result: added <|im_end|> logit bias = -inf
0.16.120.874 I common_init_result: added <|fim_pad|> logit bias = -inf
0.16.120.875 I common_init_result: added <|repo_name|> logit bias = -inf
0.16.120.876 I common_init_result: added <|file_sep|> logit bias = -inf
0.16.121.665 I llama_context: constructing llama_context
0.16.121.671 I llama_context: n_seq_max     = 1
0.16.121.672 I llama_context: n_ctx         = 131072
0.16.121.672 I llama_context: n_ctx_seq     = 131072
0.16.121.673 I llama_context: n_batch       = 2048
0.16.121.673 I llama_context: n_ubatch      = 512
0.16.121.673 I llama_context: causal_attn   = 1
0.16.121.674 I llama_context: flash_attn    = enabled
0.16.121.675 I llama_context: kv_unified    = true
0.16.121.679 I llama_context: freq_base     = 10000000.0
0.16.121.680 I llama_context: freq_scale    = 1
0.16.121.681 I llama_context: n_rs_seq      = 2
0.16.121.681 W llama_context: n_ctx_seq (131072) < n_ctx_train (262144) -- the full capacity of the model will not be utilized
0.16.123.284 I llama_context:  CUDA_Host  output buffer size =     0.95 MiB
0.16.131.032 I llama_kv_cache:      CUDA0 KV buffer size =   720.00 MiB
0.16.199.159 I llama_kv_cache: size =  720.00 MiB (131072 cells,  10 layers,  1/1 seqs), K (q4_0):  360.00 MiB, V (q4_0):  360.00 MiB
0.16.199.173 I llama_kv_cache: attn_rot_k = 1, n_embd_head_k_all = 256
0.16.199.173 I llama_kv_cache: attn_rot_v = 1, n_embd_head_k_all = 256
0.16.215.654 I llama_memory_recurrent:      CUDA0 RS buffer size =   188.44 MiB
0.16.215.696 I llama_memory_recurrent: size =  188.44 MiB (     1 cells,  41 layers,  1 seqs  2 rs_seq), R (f32):    8.44 MiB, S (f32):  180.00 MiB
0.16.215.774 I sched_reserve: reserving ...
0.16.229.885 I sched_reserve: resolving fused Gated Delta Net support:
0.16.234.518 I sched_reserve: fused Gated Delta Net (autoregressive) enabled
0.16.239.821 I sched_reserve: fused Gated Delta Net (chunked) enabled
0.16.378.295 I sched_reserve:      CUDA0 compute buffer size =   511.00 MiB
0.16.378.306 I sched_reserve:  CUDA_Host compute buffer size =   264.29 MiB
0.16.378.306 I sched_reserve: graph nodes  = 4268
0.16.378.307 I sched_reserve: graph splits = 85 (with bs=512), 76 (with bs=1)
0.16.378.309 I sched_reserve: reserve took 162.53 ms, sched copies = 1
0.16.380.020 I common_init_from_params: warming up the model with an empty run - please wait ... (--no-warmup to disable)
0.26.264.012 I srv    load_model: creating MTP draft context against the target model '/home/ejain/.cache/huggingface/hub/models--unsloth--Qwen3.6-35B-A3B-MTP-GGUF/snapshots/5bc3e238d916f48a861bac2f8a1990a0e9b7e98d/Qwen3.6-35B-A3B-UD-IQ3_XXS.gguf'
0.26.264.295 I llama_context: constructing llama_context
0.26.264.299 I llama_context: n_seq_max     = 1
0.26.264.299 I llama_context: n_ctx         = 131072
0.26.264.299 I llama_context: n_ctx_seq     = 131072
0.26.264.300 I llama_context: n_batch       = 2048
0.26.264.300 I llama_context: n_ubatch      = 512
0.26.264.301 I llama_context: causal_attn   = 1
0.26.264.301 I llama_context: flash_attn    = enabled
0.26.264.302 I llama_context: kv_unified    = true
0.26.264.305 I llama_context: freq_base     = 10000000.0
0.26.264.307 I llama_context: freq_scale    = 1
0.26.264.307 I llama_context: n_rs_seq      = 0
0.26.264.308 W llama_context: n_ctx_seq (131072) < n_ctx_train (262144) -- the full capacity of the model will not be utilized
0.26.264.460 I llama_context:  CUDA_Host  output buffer size =     0.95 MiB
0.26.274.552 I llama_kv_cache:      CUDA0 KV buffer size =    72.00 MiB
0.26.280.976 I llama_kv_cache: size =   72.00 MiB (131072 cells,   1 layers,  1/1 seqs), K (q4_0):   36.00 MiB, V (q4_0):   36.00 MiB
0.26.280.984 I llama_kv_cache: attn_rot_k = 1, n_embd_head_k_all = 256
0.26.280.985 I llama_kv_cache: attn_rot_v = 1, n_embd_head_k_all = 256
0.26.281.500 I sched_reserve: reserving ...
0.26.292.917 I sched_reserve: resolving fused Gated Delta Net support:
0.26.293.605 I sched_reserve: fused Gated Delta Net (autoregressive) enabled
0.26.293.983 I sched_reserve: fused Gated Delta Net (chunked) enabled
0.26.387.809 I sched_reserve:      CUDA0 compute buffer size =   497.00 MiB
0.26.387.818 I sched_reserve:  CUDA_Host compute buffer size =   264.29 MiB
0.26.387.818 I sched_reserve: graph nodes  = 99
0.26.387.819 I sched_reserve: graph splits = 3 (with bs=512), 4 (with bs=1)
0.26.387.820 I sched_reserve: reserve took 106.32 ms, sched copies = 1
/home/ejain/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:102: CUDA error
0.26.406.535 E ggml_cuda_compute_forward: SOFT_MAX failed
0.26.406.547 E CUDA error: invalid argument
0.26.406.548 E   current device: 0, in function ggml_cuda_compute_forward at /home/ejain/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:3114
0.26.406.549 E   err
[New LWP 31660]
[New LWP 31659]
[New LWP 31658]
[New LWP 31657]
[New LWP 31656]
[New LWP 31510]
[New LWP 31509]
[New LWP 31508]
[New LWP 31507]
[New LWP 31506]
[New LWP 31505]
[New LWP 31504]
[New LWP 31503]
[New LWP 31502]
[New LWP 31501]
[New LWP 31500]
[New LWP 31499]
[New LWP 31498]
[New LWP 31497]
[New LWP 31496]
[New LWP 31495]
[New LWP 31494]
[New LWP 31486]
[New LWP 31485]
[New LWP 31455]
[New LWP 31454]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/x86_64-linux-gnu/libthread_db.so.1".
__syscall_cancel_arch () at ../sysdeps/unix/sysv/linux/x86_64/syscall_cancel.S:56
⚠️ warning: 56   ../sysdeps/unix/sysv/linux/x86_64/syscall_cancel.S: No such file or directory
#0  __syscall_cancel_arch () at ../sysdeps/unix/sysv/linux/x86_64/syscall_cancel.S:56
56      in ../sysdeps/unix/sysv/linux/x86_64/syscall_cancel.S
#1  0x000079779d8a067c in __internal_syscall_cancel (a1=<optimized out>, a2=<optimized out>, a3=<optimized out>, a4=<optimized out>, a5=0, a6=0, nr=61) at ./nptl/cancellation.c:49
⚠️ warning: 49   ./nptl/cancellation.c: No such file or directory
#2  __syscall_cancel (a1=<optimized out>, a2=<optimized out>, a3=<optimized out>, a4=<optimized out>, a5=a5@entry=0, a6=a6@entry=0, nr=61) at ./nptl/cancellation.c:75
75      in ./nptl/cancellation.c
#3  0x000079779d91cdcf in __GI___wait4 (pid=<optimized out>, stat_loc=<optimized out>, options=<optimized out>, usage=<optimized out>) at ../sysdeps/unix/sysv/linux/wait4.c:30
⚠️ warning: 30   ../sysdeps/unix/sysv/linux/wait4.c: No such file or directory
#4  0x000079779db178b5 in ggml_print_backtrace () at /home/ejain/llama.cpp/ggml/src/ggml.c:234
234             waitpid(child_pid, NULL, 0);
#5  0x000079779db17a6c in ggml_abort (file=0x7977995e4268 "/home/ejain/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu", line=102, fmt=0x7977995e425d "CUDA error") at /home/ejain/llama.cpp/ggml/src/ggml.c:268
268             ggml_print_backtrace();
#6  0x00007977984c4eeb in ggml_cuda_error (stmt=0x7977995e4838 "err", func=0x7977995e68b3 "ggml_cuda_compute_forward", file=0x7977995e4268 "/home/ejain/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu", line=3114, msg=0x797797e8c72f "invalid argument") at /home/ejain/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:102
102         GGML_ABORT(GGML_CUDA_NAME " error");
#7  0x00007977984d0a19 in ggml_cuda_compute_forward (ctx=..., dst=0x61dc7d62eaa0) at /home/ejain/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:3114
3114            CUDA_CHECK(err);
#8  0x00007977984d76c5 in ggml_cuda_graph_evaluate_and_capture (cuda_ctx=0x61dc7ce992a0, cgraph=0x61dc7ff87660, use_cuda_graph=false, cuda_graph_update_required=false, graph_key=0x61dc7d62a150) at /home/ejain/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:4388
4388                    bool ok = ggml_cuda_compute_forward(*cuda_ctx, node);
#9  0x00007977984d7e30 in ggml_backend_cuda_graph_compute (backend=0x61dc6f27a400, cgraph=0x61dc7ff87660) at /home/ejain/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:4508
4508        ggml_cuda_graph_evaluate_and_capture(cuda_ctx, cgraph, use_cuda_graph, cuda_graph_update_required, graph_key);
#10 0x000079779db35067 in ggml_backend_graph_compute_async (backend=0x61dc6f27a400, cgraph=0x61dc7ff87660) at /home/ejain/llama.cpp/ggml/src/ggml-backend.cpp:452
452         return backend->iface.graph_compute(backend, cgraph);
#11 0x000079779db3a082 in ggml_backend_sched_compute_splits (sched=0x61dc7e838400) at /home/ejain/llama.cpp/ggml/src/ggml-backend.cpp:1678
1678                enum ggml_status ec = ggml_backend_graph_compute_async(split_backend, &split->graph);
#12 0x000079779db3afed in ggml_backend_sched_graph_compute_async (sched=0x61dc7e838400, graph=0x61dc7d508c00) at /home/ejain/llama.cpp/ggml/src/ggml-backend.cpp:1901
1901        return ggml_backend_sched_compute_splits(sched);
#13 0x000079779c0d9e5b in llama_context::graph_compute (this=0x61dc6ca3c2d0, gf=0x61dc7d508c00, batched=true) at /home/ejain/llama.cpp/src/llama-context.cpp:2326
2326        auto status = ggml_backend_sched_graph_compute_async(sched.get(), gf);
#14 0x000079779c0d47c6 in llama_context::process_ubatch (this=0x61dc6ca3c2d0, ubatch=..., gtype=LLM_GRAPH_TYPE_DECODER_MTP, mctx=0x61dc7ff88c00, ret=@0x7ffeadb5ef50: 1824299776) at /home/ejain/llama.cpp/src/llama-context.cpp:1309
1309        const auto status = graph_compute(res->get_gf(), ubatch.n_tokens > 1);
#15 0x000079779c0d6a60 in llama_context::decode (this=0x61dc6ca3c2d0, batch_inp=...) at /home/ejain/llama.cpp/src/llama-context.cpp:1787
1787            const auto * res = process_ubatch(ubatch, ctx_type_to_graph_type(cparams.ctx_type), mctx.get(), status);
#16 0x000079779c0df004 in llama_decode (ctx=0x61dc6ca3c2d0, batch=...) at /home/ejain/llama.cpp/src/llama-context.cpp:3928
3928        const int ret = ctx->decode(batch);
#17 0x000079779d229d8c in common_context_can_seq_rm (ctx=0x61dc6ca3c2d0) at /home/ejain/llama.cpp/common/common.cpp:1444
1444        int ret = llama_decode(ctx, llama_batch_get_one(tmp.data(), tmp.size()));
#18 0x000079779e63106e in server_context_impl::load_model (this=0x61dc6ddd0220, params=...) at /home/ejain/llama.cpp/tools/server/server-context.cpp:874
874                 ctx_dft_seq_rm_type = common_context_can_seq_rm(ctx_dft.get());
#19 0x000079779e6081f2 in server_context::load_model (this=0x7ffeadb610b8, params=...) at /home/ejain/llama.cpp/tools/server/server-context.cpp:3363
3363        return impl->load_model(params);
#20 0x000079779e5219fd in llama_server (argc=45, argv=0x7ffeadb67b98) at /home/ejain/llama.cpp/tools/server/server.cpp:294
294             if (!ctx_server.load_model(params)) {
#21 0x000061dc61a9c34d in main (argc=45, argv=0x7ffeadb67b98) at /home/ejain/llama.cpp/tools/server/main.cpp:4
4           return llama_server(argc, argv);
[Inferior 1 (process 31452) detached]
cat../../run_qwen_debug.sh: line 25: 31452 Aborted                    (core dumped) ./llama-server -hf unsloth/Qwen3.6-35B-A3B-MTP-GGUF:UD-IQ3_XXS --port 8080 --n-cpu-moe 23 --override-tensor "blk.(2[6-9]|3[0-9]|4[0-6]).ffn_(gate_up|down)_exps.weight=CPU" --cache-type-k q4_0 --cache-type-v q4_0 --flash-attn on --cont-batching --ctx-checkpoints 2 --models-max 1 --spec-type draft-mtp --spec-draft-n-max 2 -c 131072 -b 2048 -ub 512 --spec-draft-type-k q4_0 --spec-draft-type-v q4_0 --cache-ram 2048 --kv-unified -lv 4 --kv-offload -np 1 --reasoning on --no-mmproj
```
</details>

**Comment by JonnoFTW** [comment]
I encounter the same issue. I'm running:

* OS: Ubuntu 24.04.4 LTS
* CUDA: 13.0
* Card: NVIDIA GeForce RTX 5090
* Driver: 580.159.03

Usage:

```shell
git pull
rm -rf build
CUDACXX=/usr/local/cuda/bin/nvcc cmake -B build -DGGML_BLAS=ON -DGGML_BLAS_VENDOR=OpenBLAS -DGGML_CUDA=ON
cmake --build build --config Release -j 8
./build/bin/llama-server -hf ggml-org/gemma-4-26B-A4B-it-GGUF:Q4_K_M
```

I get this error after sending a chat message via the web ui:

```
0.11.033.179 E ggml_cuda_compute_forward: SOFT_MAX failed
0.11.033.189 E CUDA error: invalid argument
0.11.033.189 E   current device: 0, in function ggml_cuda_compute_forward at /home/jonno/code/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:3120
0.11.033.190 E   err

```

**Comment by EJainDev** [comment]
After further testing, it seems to stem from `--spec-type draft-mtp` in my case, although @JonnoFTW seems to have the same issue because of the model itself.

EDIT: Building in Debug mode, the line number is 3122 in the same file.
EDIT 2: If `--spec-type draft-mtp` is removed, the error does not exist on warmup but it reappears on the first prompt.

**Comment by Cyrille37** [comment]
Hi
same error with many models with "RTX 5060 Ti" (Blackwell SM120) and CUDA 13.3 and nvidia-headless-595-server-open : SOFT_MAX failed .

Perhaps https://github.com/ggml-org/llama.cpp/issues/23385

**Comment by Cyrille37** [comment]
I came back after many tries and have success running models now, **with carefully remove & install only one cuda-toolkit**, and **compiling from fresh source** (no rebuild on a previously build version).

With "dpkg --get-selections" I saw 2 versions a cuda-toolkit, the one from ubuntu and the one from nvidia. Event if I explicitly add CUDA ENV vars for compilation, I could not have a working llama-server running.

After removed all  cuda-toolkit then install only the  cuda-toolkit-13-3 and building llama.cpp with fresh source, I got all tested models **run without SOFT_MAX error**.

- Ubuntu 26.04 LTS
- RTX 5060 Ti (Blackwell SM120)
-  "dpkg --get-selections" only show packages with "13-3" like cuda-toolkit-13-3, cuda-cudart-13-3, ...
- nvidia-headless-595-server-open

llama.cpp compilation:
```
export CUDA_VERSION=13.3 && cmake -B build \
 -DCMAKE_CUDA_ARCHITECTURES=120 \
 -DGGML_CUDA=ON \
 -DCMAKE_CUDA_COMPILER=/usr/local/cuda-${CUDA_VERSION}/bin/nvcc \
 -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON \
 -DCMAKE_INSTALL_RPATH="/usr/local/cuda-${CUDA_VERSION}/lib64;\$ORIGIN"

time cmake --build build --config Release -j 10
```

then launching the server with 
```
exec llama.cpp/build/bin/llama-server \
 -m "models/Qwen3-Coder-30B-A3B-Instruct-Q4_K_M.gguf" \
 --host 0.0.0.0 --port 8012 \
 --verbosity 4 \
 --threads-http 2 \
 --flash-attn on \
 --no-mmap \
 --cache-type-k q8_0 --cache-type-v q8_0 \
 --repeat-penalty 1.05 \
 --temp 0.2 \
 --jinja \
 -c 96000
```

```
...
0.09.366.754 I load_tensors: offloading output layer to GPU
0.09.366.757 I load_tensors: offloading 47 repeating layers to GPU
0.09.366.757 I load_tensors: offloaded 49/49 layers to GPU
0.09.366.761 I load_tensors:          CPU model buffer size =   166.92 MiB
0.09.366.763 I load_tensors:        CUDA0 model buffer size =  9585.43 MiB
0.09.366.763 I load_tensors:    CUDA_Host model buffer size =  7939.00 MiB
...
0.11.040.606 I llama_context: constructing llama_context
0.11.040.607 I llama_context: n_seq_max     = 4
0.11.040.607 I llama_context: n_ctx         = 96000
0.11.040.607 I llama_context: n_ctx_seq     = 96000
0.11.040.607 I llama_context: n_batch       = 2048
0.11.040.607 I llama_context: n_ubatch      = 512
0.11.040.607 I llama_context: causal_attn   = 1
0.11.040.607 I llama_context: flash_attn    = enabled
0.11.040.608 I llama_context: kv_unified    = true
0.11.040.610 I llama_context: freq_base     = 10000000.0
0.11.040.610 I llama_context: freq_scale    = 1
0.11.040.610 I llama_context: n_rs_seq      = 0
0.11.040.610 I llama_context: n_outputs_max = 4
0.11.040.611 W llama_context: n_ctx_seq (96000) < n_ctx_train (262144) -- the full capacity of the model will not be utilized
0.11.041.511 I llama_context:  CUDA_Host  output buffer size =     2.32 MiB
0.11.042.600 I llama_kv_cache:      CUDA0 KV buffer size =  4781.25 MiB
0.11.054.388 I llama_kv_cache: size = 4781.25 MiB ( 96000 cells,  48 layers,  4/1 seqs), K (q8_0): 2390.62 MiB, V (q8_0): 2390.62 MiB
0.11.054.389 I llama_kv_cache: attn_rot_k = 1, n_embd_head_k_all = 128
0.11.054.389 I llama_kv_cache: attn_rot_v = 1, n_embd_head_k_all = 128
0.11.054.399 I sched_reserve: reserving ...
0.11.055.228 I sched_reserve: resolving fused Gated Delta Net support:
0.11.055.750 I sched_reserve: fused Gated Delta Net (autoregressive) enabled
0.11.056.146 I sched_reserve: fused Gated Delta Net (chunked) enabled
0.11.079.499 I sched_reserve:      CUDA0 compute buffer size =   311.34 MiB
0.11.079.501 I sched_reserve:  CUDA_Host compute buffer size =   101.84 MiB
0.11.079.501 I sched_reserve: graph nodes  = 3606
0.11.079.501 I sched_reserve: graph splits = 70 (with bs=512), 50 (with bs=1)
0.11.079.502 I sched_reserve: reserve took 25.10 ms, sched copies = 1
0.11.079.551 I common_init_from_params: warming up the model with an empty run - please wait ... (--no-warmup to disable)
...
0.11.239.955 I srv  llama_server: model loaded
0.11.239.957 I srv  llama_server: server is listening on http://0.0.0.0:8012
0.11.239.962 I srv  update_slots: all slots are idle
```

**Comment by EJainDev** [comment]
This worked for me too. I think it's good to close this issue then.
